/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AddRouteGroupMembersRequest
 */
export interface AddRouteGroupMembersRequest {
    /**
     * Optional free-text note explaining why these routes were added
     * (BCP-3998). Recorded on the group, which is where membership
     * attribution lives — see the `ModelRouteGroup::attribution` docs.
     */
    changeNote?: string | null;
    /**
     * 
     */
    modelAliases: Array<string>;
}

/**
 * Check if a given object implements the AddRouteGroupMembersRequest interface.
 */
export function instanceOfAddRouteGroupMembersRequest(value: object): value is AddRouteGroupMembersRequest {
    if ((!('modelAliases' in (value as Record<string, any>)) && !('model_aliases' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAliases'] === undefined && (value as Record<string, any>)['model_aliases'] === undefined)) return false;
    return true;
}

export function AddRouteGroupMembersRequestFromJSON(json: any): AddRouteGroupMembersRequest {
    return AddRouteGroupMembersRequestFromJSONTyped(json, false);
}

export function AddRouteGroupMembersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRouteGroupMembersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'modelAliases': json['model_aliases'],
    };
}

export function AddRouteGroupMembersRequestToJSON(json: any): AddRouteGroupMembersRequest {
    return AddRouteGroupMembersRequestToJSONTyped(json, false);
}

export function AddRouteGroupMembersRequestToJSONTyped(value?: AddRouteGroupMembersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'model_aliases': value['modelAliases'],
    };
}

