/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Compact row for the affected-by preview (BCP-1686 § API Contract).
 * 
 * Just enough to render in the delete-confirmation modal — id for keying,
 * name for display, status so the UI can disambiguate active vs draft.
 * @export
 * @interface AffectedPolicyPreview
 */
export interface AffectedPolicyPreview {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    mcpServerId: string;
    /**
     * 
     */
    applicationIds?: Array<string>;
}

/**
 * Check if a given object implements the AffectedPolicyPreview interface.
 */
export function instanceOfAffectedPolicyPreview(value: object): value is AffectedPolicyPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('mcpServerId' in (value as Record<string, any>)) && !('mcp_server_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerId'] === undefined && (value as Record<string, any>)['mcp_server_id'] === undefined)) return false;
    return true;
}

export function AffectedPolicyPreviewFromJSON(json: any): AffectedPolicyPreview {
    return AffectedPolicyPreviewFromJSONTyped(json, false);
}

export function AffectedPolicyPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedPolicyPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
        'mcpServerId': json['mcp_server_id'],
        'applicationIds': json['application_ids'] == null ? undefined : json['application_ids'],
    };
}

export function AffectedPolicyPreviewToJSON(json: any): AffectedPolicyPreview {
    return AffectedPolicyPreviewToJSONTyped(json, false);
}

export function AffectedPolicyPreviewToJSONTyped(value?: AffectedPolicyPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'mcp_server_id': value['mcpServerId'],
        'application_ids': value['applicationIds'],
    };
}

