/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AffectedPolicyPreview } from './AffectedPolicyPreview.js';
import {
    AffectedPolicyPreviewFromJSON,
    AffectedPolicyPreviewFromJSONTyped,
    AffectedPolicyPreviewToJSON,
    AffectedPolicyPreviewToJSONTyped,
} from './AffectedPolicyPreview.js';

/**
 * Response shape for GET /admin/v2/policies/affected-by.
 * 
 * Mirrors the cascade-handler buckets exactly: ``archive_*`` are policies
 * that would transition to ARCHIVED, ``revise_*`` are policies that would
 * have only their application_ids set-minus'd (only possible on agent_id
 * queries — always 0/[] for mcp_server_id queries).
 * @export
 * @interface AffectedPoliciesResponse
 */
export interface AffectedPoliciesResponse {
    /**
     * 
     */
    archiveCount: number;
    /**
     * 
     */
    reviseCount: number;
    /**
     * 
     */
    archivePreview?: Array<AffectedPolicyPreview>;
    /**
     * 
     */
    revisePreview?: Array<AffectedPolicyPreview>;
}

/**
 * Check if a given object implements the AffectedPoliciesResponse interface.
 */
export function instanceOfAffectedPoliciesResponse(value: object): value is AffectedPoliciesResponse {
    if ((!('archiveCount' in (value as Record<string, any>)) && !('archive_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['archiveCount'] === undefined && (value as Record<string, any>)['archive_count'] === undefined)) return false;
    if ((!('reviseCount' in (value as Record<string, any>)) && !('revise_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['reviseCount'] === undefined && (value as Record<string, any>)['revise_count'] === undefined)) return false;
    return true;
}

export function AffectedPoliciesResponseFromJSON(json: any): AffectedPoliciesResponse {
    return AffectedPoliciesResponseFromJSONTyped(json, false);
}

export function AffectedPoliciesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedPoliciesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveCount': json['archive_count'],
        'reviseCount': json['revise_count'],
        'archivePreview': json['archive_preview'] == null ? undefined : ((json['archive_preview'] as Array<any>).map(AffectedPolicyPreviewFromJSON)),
        'revisePreview': json['revise_preview'] == null ? undefined : ((json['revise_preview'] as Array<any>).map(AffectedPolicyPreviewFromJSON)),
    };
}

export function AffectedPoliciesResponseToJSON(json: any): AffectedPoliciesResponse {
    return AffectedPoliciesResponseToJSONTyped(json, false);
}

export function AffectedPoliciesResponseToJSONTyped(value?: AffectedPoliciesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_count': value['archiveCount'],
        'revise_count': value['reviseCount'],
        'archive_preview': value['archivePreview'] == null ? undefined : ((value['archivePreview'] as Array<any>).map(AffectedPolicyPreviewToJSON)),
        'revise_preview': value['revisePreview'] == null ? undefined : ((value['revisePreview'] as Array<any>).map(AffectedPolicyPreviewToJSON)),
    };
}

