/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Policy counts keyed by agent ID, plus a count for unscoped (all-agent) policies.
 * @export
 * @interface AgentPolicyCounts
 */
export interface AgentPolicyCounts {
    /**
     * Map of agent ID to policy count
     */
    agents?: { [key: string]: number; };
    /**
     * Number of policies that apply to all agents (no agent scope)
     */
    unscoped?: number;
}

/**
 * Check if a given object implements the AgentPolicyCounts interface.
 */
export function instanceOfAgentPolicyCounts(value: object): value is AgentPolicyCounts {
    return true;
}

export function AgentPolicyCountsFromJSON(json: any): AgentPolicyCounts {
    return AgentPolicyCountsFromJSONTyped(json, false);
}

export function AgentPolicyCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentPolicyCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'agents': json['agents'] == null ? undefined : json['agents'],
        'unscoped': json['unscoped'] == null ? undefined : json['unscoped'],
    };
}

export function AgentPolicyCountsToJSON(json: any): AgentPolicyCounts {
    return AgentPolicyCountsToJSONTyped(json, false);
}

export function AgentPolicyCountsToJSONTyped(value?: AgentPolicyCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agents': value['agents'],
        'unscoped': value['unscoped'],
    };
}

