/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Which AI agents a policy applies to, ANDed with its principals.
 * @export
 * @interface AgentScopeRequest
 */
export interface AgentScopeRequest {
    /**
     * Registry agent (application) ids: 1 to 200 unique UUIDs when `mode` is `SELECTED`, empty for `ALL`.
     */
    agentIds?: Array<string>;
    /**
     * `ALL` (every agent, including agents created later) or `SELECTED`.
     */
    mode: string;
}

/**
 * Check if a given object implements the AgentScopeRequest interface.
 */
export function instanceOfAgentScopeRequest(value: object): value is AgentScopeRequest {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function AgentScopeRequestFromJSON(json: any): AgentScopeRequest {
    return AgentScopeRequestFromJSONTyped(json, false);
}

export function AgentScopeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentScopeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agentIds': json['agent_ids'] == null ? undefined : json['agent_ids'],
        'mode': json['mode'],
    };
}

export function AgentScopeRequestToJSON(json: any): AgentScopeRequest {
    return AgentScopeRequestToJSONTyped(json, false);
}

export function AgentScopeRequestToJSONTyped(value?: AgentScopeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_ids': value['agentIds'],
        'mode': value['mode'],
    };
}

