/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Agent type classification for applications.
 * @export
 */
export const AgentType = {
    Internal: 'internal',
    External: 'external',
} as const;
export type AgentType = typeof AgentType[keyof typeof AgentType];


export function instanceOfAgentType(value: any): boolean {
    for (const key in AgentType) {
        if (Object.prototype.hasOwnProperty.call(AgentType, key)) {
            if (AgentType[key as keyof typeof AgentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentTypeFromJSON(json: any): AgentType {
    return AgentTypeFromJSONTyped(json, false);
}

export function AgentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentType {
    return json as AgentType;
}

export function AgentTypeToJSON(value?: AgentType | null): any {
    return value as any;
}

export function AgentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentType {
    return value as AgentType;
}

