/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { AgentRuntimeCapabilities } from './AgentRuntimeCapabilities.js';
import {
    AgentRuntimeCapabilitiesFromJSON,
    AgentRuntimeCapabilitiesFromJSONTyped,
    AgentRuntimeCapabilitiesToJSON,
    AgentRuntimeCapabilitiesToJSONTyped,
} from './AgentRuntimeCapabilities.js';

/**
 * A profile joined with the contract of its `current_version`.
 * @export
 * @interface AgentRuntimeProfile
 */
export interface AgentRuntimeProfile {
    /**
     * 
     */
    active: boolean;
    /**
     * 
     */
    capabilities: AgentRuntimeCapabilities;
    /**
     * 
     */
    client: string;
    /**
     * 
     */
    config: { [key: string]: string; };
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    displayName: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    isOrgDefault: boolean;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * The immutable version whose `config` is loaded below.
     */
    version: number;
}

/**
 * Check if a given object implements the AgentRuntimeProfile interface.
 */
export function instanceOfAgentRuntimeProfile(value: object): value is AgentRuntimeProfile {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('client' in value) || value['client'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('isOrgDefault' in (value as Record<string, any>)) && !('is_org_default' in (value as Record<string, any>))) || ((value as Record<string, any>)['isOrgDefault'] === undefined && (value as Record<string, any>)['is_org_default'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function AgentRuntimeProfileFromJSON(json: any): AgentRuntimeProfile {
    return AgentRuntimeProfileFromJSONTyped(json, false);
}

export function AgentRuntimeProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRuntimeProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'capabilities': AgentRuntimeCapabilitiesFromJSON(json['capabilities']),
        'client': json['client'],
        'config': json['config'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'displayName': json['display_name'],
        'id': json['id'],
        'isOrgDefault': json['is_org_default'],
        'orgId': json['org_id'],
        'slug': json['slug'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'version': json['version'],
    };
}

export function AgentRuntimeProfileToJSON(json: any): AgentRuntimeProfile {
    return AgentRuntimeProfileToJSONTyped(json, false);
}

export function AgentRuntimeProfileToJSONTyped(value?: AgentRuntimeProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'capabilities': AgentRuntimeCapabilitiesToJSON(value['capabilities']),
        'client': value['client'],
        'config': value['config'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'display_name': value['displayName'],
        'id': value['id'],
        'is_org_default': value['isOrgDefault'],
        'org_id': value['orgId'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'version': value['version'],
    };
}

