/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A discrete, notification-worthy event. This is what publishers emit and what channels
 * subscribe to — a channel is delivered an alert when its subscription set contains that
 * alert's type. Severity and category are intrinsic to the type (see ``ALERT_TAXONOMY``), so
 * they are never set per subscription.
 * 
 * Treat this enum as open: values are added over time, and the set your organization may
 * actually subscribe to is gated by feature flags. Read
 * ``GET /public/v1/channels/options`` for the live vocabulary rather than hardcoding these
 * names — subscribing to a type your organization is not admitted to is silently inert.
 * @export
 */
export const AlertType = {
    LlmThresholdExceeded: 'llm_threshold_exceeded',
    ConnectionBroken: 'connection_broken',
    McpServerAdded: 'mcp_server_added',
    McpServerDeleted: 'mcp_server_deleted',
    PolicyChanged: 'policy_changed',
    PolicyImpact: 'policy_impact',
    AdminRoleChange: 'admin_role_change',
    BreakGlassUsed: 'break_glass_used',
    LlmBudgetExhausted: 'llm_budget_exhausted',
    LlmProviderUnavailable: 'llm_provider_unavailable',
    LlmProviderKeyRejected: 'llm_provider_key_rejected',
    ApiKeyRevoked: 'api_key_revoked',
    McpServerToolingChanged: 'mcp_server_tooling_changed',
} as const;
export type AlertType = typeof AlertType[keyof typeof AlertType];


export function instanceOfAlertType(value: any): boolean {
    for (const key in AlertType) {
        if (Object.prototype.hasOwnProperty.call(AlertType, key)) {
            if (AlertType[key as keyof typeof AlertType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AlertTypeFromJSON(json: any): AlertType {
    return AlertTypeFromJSONTyped(json, false);
}

export function AlertTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertType {
    return json as AlertType;
}

export function AlertTypeToJSON(value?: AlertType | null): any {
    return value as any;
}

export function AlertTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AlertType {
    return value as AlertType;
}

