/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * One subscribable alert type, plus its intrinsic category and severity.
 * @export
 * @interface AlertTypeOption
 */
export interface AlertTypeOption {
    /**
     * The alert type — what to send as a subscription's `alert_type`.
     */
    value: string;
    /**
     * Human-readable label for display.
     */
    label: string;
    /**
     * The type's category. Intrinsic to the type, not configurable.
     */
    category: string;
    /**
     * The type's severity. Intrinsic to the type, not configurable.
     */
    severity: string;
}

/**
 * Check if a given object implements the AlertTypeOption interface.
 */
export function instanceOfAlertTypeOption(value: object): value is AlertTypeOption {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    return true;
}

export function AlertTypeOptionFromJSON(json: any): AlertTypeOption {
    return AlertTypeOptionFromJSONTyped(json, false);
}

export function AlertTypeOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertTypeOption {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'label': json['label'],
        'category': json['category'],
        'severity': json['severity'],
    };
}

export function AlertTypeOptionToJSON(json: any): AlertTypeOption {
    return AlertTypeOptionToJSONTyped(json, false);
}

export function AlertTypeOptionToJSONTyped(value?: AlertTypeOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'label': value['label'],
        'category': value['category'],
        'severity': value['severity'],
    };
}

