/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What category of credential a row is (BCP-3510) — the first-class answer to
 * "is this an ephemeral governed agent-session key?", which the service used
 * to get by pattern-matching [`AGENT_SESSION_SCOPE`] inside `scopes`.
 * 
 * Distinct from [`ActorKind`], which answers a different question. `kind` is
 * about **lifecycle**: who may list it, who may revoke it, and whether the
 * reaper may delete it. `ActorKind` is about **attribution**: whose name goes
 * on an event. That is why `Machine` here covers both the pure service key and
 * the IdP-group-bound key that `ActorKind` keeps apart — the two are listed,
 * revoked and reaped identically, and only the audit trail cares which is
 * which.
 * @export
 */
export const ApiKeyKind = {
    User: 'user',
    Machine: 'machine',
    AgentSession: 'agent_session',
} as const;
export type ApiKeyKind = typeof ApiKeyKind[keyof typeof ApiKeyKind];


export function instanceOfApiKeyKind(value: any): boolean {
    for (const key in ApiKeyKind) {
        if (Object.prototype.hasOwnProperty.call(ApiKeyKind, key)) {
            if (ApiKeyKind[key as keyof typeof ApiKeyKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiKeyKindFromJSON(json: any): ApiKeyKind {
    return ApiKeyKindFromJSONTyped(json, false);
}

export function ApiKeyKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyKind {
    return json as ApiKeyKind;
}

export function ApiKeyKindToJSON(value?: ApiKeyKind | null): any {
    return value as any;
}

export function ApiKeyKindToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiKeyKind {
    return value as ApiKeyKind;
}

