/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * `PATCH /admin/api-keys/{id}` — echoes the disabled state now in effect.
 * @export
 * @interface ApiKeyDisabledResponse
 */
export interface ApiKeyDisabledResponse {
    /**
     * The key's disabled flag after the update, echoing the request.
     */
    disabled: boolean;
}

/**
 * Check if a given object implements the ApiKeyDisabledResponse interface.
 */
export function instanceOfApiKeyDisabledResponse(value: object): value is ApiKeyDisabledResponse {
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    return true;
}

export function ApiKeyDisabledResponseFromJSON(json: any): ApiKeyDisabledResponse {
    return ApiKeyDisabledResponseFromJSONTyped(json, false);
}

export function ApiKeyDisabledResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyDisabledResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'],
    };
}

export function ApiKeyDisabledResponseToJSON(json: any): ApiKeyDisabledResponse {
    return ApiKeyDisabledResponseToJSONTyped(json, false);
}

export function ApiKeyDisabledResponseToJSONTyped(value?: ApiKeyDisabledResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
    };
}

