/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { AppType } from './AppType.js';
import {
    AppTypeFromJSON,
    AppTypeFromJSONTyped,
    AppTypeToJSON,
    AppTypeToJSONTyped,
} from './AppType.js';
import type { OAuthConfig } from './OAuthConfig.js';
import {
    OAuthConfigFromJSON,
    OAuthConfigFromJSONTyped,
    OAuthConfigToJSON,
    OAuthConfigToJSONTyped,
} from './OAuthConfig.js';

/**
 * 
 * @export
 * @interface ApplicationDirectoryResponse
 */
export interface ApplicationDirectoryResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    description: string | null;
    /**
     * Responsible team or person that manages the agent.
     */
    ownerName: string | null;
    /**
     * Contact information (email, Slack, etc.) for the agent owner.
     */
    ownerContact: string | null;
    /**
     * 
     */
    organizationId: string;
    /**
     * 
     */
    externalId: string | null;
    /**
     * 
     */
    _public: boolean;
    /**
     * OAuth application type. Source of truth for the agent's app type; projected onto provider-specific fields (Auth0 ``app_type``, Keycloak ``serviceAccountsEnabled``).
     */
    appType: AppType | null;
    /**
     * 
     */
    dcr: boolean;
    /**
     * 
     */
    postLoginSuccess: boolean;
    /**
     * OAuth callback URLs stored in alphanumeric ascending order
     */
    callbacks: Array<string> | null;
    /**
     * Canonicalized OAuth Client ID Metadata Document URL for clients registered via the CIMD flow. NULL for non-CIMD clients.
     */
    cimdUrl: string | null;
    /**
     * 
     */
    oauthConfig: OAuthConfig | null;
}



/**
 * Check if a given object implements the ApplicationDirectoryResponse interface.
 */
export function instanceOfApplicationDirectoryResponse(value: object): value is ApplicationDirectoryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('ownerName' in (value as Record<string, any>)) && !('owner_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerName'] === undefined && (value as Record<string, any>)['owner_name'] === undefined)) return false;
    if ((!('ownerContact' in (value as Record<string, any>)) && !('owner_contact' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerContact'] === undefined && (value as Record<string, any>)['owner_contact'] === undefined)) return false;
    if ((!('organizationId' in (value as Record<string, any>)) && !('organization_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['organizationId'] === undefined && (value as Record<string, any>)['organization_id'] === undefined)) return false;
    if ((!('externalId' in (value as Record<string, any>)) && !('external_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['externalId'] === undefined && (value as Record<string, any>)['external_id'] === undefined)) return false;
    if ((!('_public' in (value as Record<string, any>)) && !('public' in (value as Record<string, any>))) || ((value as Record<string, any>)['_public'] === undefined && (value as Record<string, any>)['public'] === undefined)) return false;
    if ((!('appType' in (value as Record<string, any>)) && !('app_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['appType'] === undefined && (value as Record<string, any>)['app_type'] === undefined)) return false;
    if (!('dcr' in value) || value['dcr'] === undefined) return false;
    if ((!('postLoginSuccess' in (value as Record<string, any>)) && !('post_login_success' in (value as Record<string, any>))) || ((value as Record<string, any>)['postLoginSuccess'] === undefined && (value as Record<string, any>)['post_login_success'] === undefined)) return false;
    if (!('callbacks' in value) || value['callbacks'] === undefined) return false;
    if ((!('cimdUrl' in (value as Record<string, any>)) && !('cimd_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['cimdUrl'] === undefined && (value as Record<string, any>)['cimd_url'] === undefined)) return false;
    if ((!('oauthConfig' in (value as Record<string, any>)) && !('oauth_config' in (value as Record<string, any>))) || ((value as Record<string, any>)['oauthConfig'] === undefined && (value as Record<string, any>)['oauth_config'] === undefined)) return false;
    return true;
}

export function ApplicationDirectoryResponseFromJSON(json: any): ApplicationDirectoryResponse {
    return ApplicationDirectoryResponseFromJSONTyped(json, false);
}

export function ApplicationDirectoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDirectoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'name': json['name'],
        'description': json['description'],
        'ownerName': json['owner_name'],
        'ownerContact': json['owner_contact'],
        'organizationId': json['organization_id'],
        'externalId': json['external_id'],
        '_public': json['public'],
        'appType': AppTypeFromJSON(json['app_type']),
        'dcr': json['dcr'],
        'postLoginSuccess': json['post_login_success'],
        'callbacks': json['callbacks'] == null ? null : json['callbacks'],
        'cimdUrl': json['cimd_url'],
        'oauthConfig': OAuthConfigFromJSON(json['oauth_config']),
    };
}

export function ApplicationDirectoryResponseToJSON(json: any): ApplicationDirectoryResponse {
    return ApplicationDirectoryResponseToJSONTyped(json, false);
}

export function ApplicationDirectoryResponseToJSONTyped(value?: ApplicationDirectoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'name': value['name'],
        'description': value['description'],
        'owner_name': value['ownerName'],
        'owner_contact': value['ownerContact'],
        'organization_id': value['organizationId'],
        'external_id': value['externalId'],
        'public': value['_public'],
        'app_type': AppTypeToJSON(value['appType']),
        'dcr': value['dcr'],
        'post_login_success': value['postLoginSuccess'],
        'callbacks': value['callbacks'],
        'cimd_url': value['cimdUrl'],
        'oauth_config': OAuthConfigToJSON(value['oauthConfig']),
    };
}

