/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ApplicationLlmGatewayPayload
 */
export interface ApplicationLlmGatewayPayload {
    /**
     * 
     */
    llmGatewayEnabled: boolean;
}

/**
 * Check if a given object implements the ApplicationLlmGatewayPayload interface.
 */
export function instanceOfApplicationLlmGatewayPayload(value: object): value is ApplicationLlmGatewayPayload {
    if ((!('llmGatewayEnabled' in (value as Record<string, any>)) && !('llm_gateway_enabled' in (value as Record<string, any>))) || ((value as Record<string, any>)['llmGatewayEnabled'] === undefined && (value as Record<string, any>)['llm_gateway_enabled'] === undefined)) return false;
    return true;
}

export function ApplicationLlmGatewayPayloadFromJSON(json: any): ApplicationLlmGatewayPayload {
    return ApplicationLlmGatewayPayloadFromJSONTyped(json, false);
}

export function ApplicationLlmGatewayPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationLlmGatewayPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'llmGatewayEnabled': json['llm_gateway_enabled'],
    };
}

export function ApplicationLlmGatewayPayloadToJSON(json: any): ApplicationLlmGatewayPayload {
    return ApplicationLlmGatewayPayloadToJSONTyped(json, false);
}

export function ApplicationLlmGatewayPayloadToJSONTyped(value?: ApplicationLlmGatewayPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'llm_gateway_enabled': value['llmGatewayEnabled'],
    };
}

