/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ApplicationPayload
 */
export interface ApplicationPayload {
    /**
     * 
     */
    applicationDirectoryId: string;
    /**
     * 
     */
    writeConfirmationsRequired?: boolean;
    /**
     * 
     */
    llmGatewayEnabled?: boolean;
}

/**
 * Check if a given object implements the ApplicationPayload interface.
 */
export function instanceOfApplicationPayload(value: object): value is ApplicationPayload {
    if ((!('applicationDirectoryId' in (value as Record<string, any>)) && !('application_directory_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['applicationDirectoryId'] === undefined && (value as Record<string, any>)['application_directory_id'] === undefined)) return false;
    return true;
}

export function ApplicationPayloadFromJSON(json: any): ApplicationPayload {
    return ApplicationPayloadFromJSONTyped(json, false);
}

export function ApplicationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationDirectoryId': json['application_directory_id'],
        'writeConfirmationsRequired': json['write_confirmations_required'] == null ? undefined : json['write_confirmations_required'],
        'llmGatewayEnabled': json['llm_gateway_enabled'] == null ? undefined : json['llm_gateway_enabled'],
    };
}

export function ApplicationPayloadToJSON(json: any): ApplicationPayload {
    return ApplicationPayloadToJSONTyped(json, false);
}

export function ApplicationPayloadToJSONTyped(value?: ApplicationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application_directory_id': value['applicationDirectoryId'],
        'write_confirmations_required': value['writeConfirmationsRequired'],
        'llm_gateway_enabled': value['llmGatewayEnabled'],
    };
}

