/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Supported OAuth application types.
 * 
 * Values mirror Auth0's ``app_type`` field; the same values are used
 * internally for Keycloak (which has no native ``app_type`` concept).
 * @export
 */
export const AppType = {
    RegularWeb: 'regular_web',
    Spa: 'spa',
    Native: 'native',
    NonInteractive: 'non_interactive',
} as const;
export type AppType = typeof AppType[keyof typeof AppType];


export function instanceOfAppType(value: any): boolean {
    for (const key in AppType) {
        if (Object.prototype.hasOwnProperty.call(AppType, key)) {
            if (AppType[key as keyof typeof AppType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppTypeFromJSON(json: any): AppType {
    return AppTypeFromJSONTyped(json, false);
}

export function AppTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppType {
    return json as AppType;
}

export function AppTypeToJSON(value?: AppType | null): any {
    return value as any;
}

export function AppTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AppType {
    return value as AppType;
}

