/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * BCP-3815 — API vocabulary for the :func:`attention_rank_expr` tiers.
 * 
 * Emitted as ``attention_tier`` on server read payloads so the client badges a
 * server from the same CASE that filters (``availability_filter_expr``), sorts
 * (``order_by=attention``) and counts (``/servers/summary``) it — one
 * classification, declared once, instead of a second hand-written copy in
 * TypeScript that could drift with every suite green.
 * @export
 */
export const AttentionTier = {
    PendingPublish: 'pending_publish',
    ConnectionError: 'connection_error',
    PendingCredentials: 'pending_credentials',
    PendingConnection: 'pending_connection',
    Available: 'available',
} as const;
export type AttentionTier = typeof AttentionTier[keyof typeof AttentionTier];


export function instanceOfAttentionTier(value: any): boolean {
    for (const key in AttentionTier) {
        if (Object.prototype.hasOwnProperty.call(AttentionTier, key)) {
            if (AttentionTier[key as keyof typeof AttentionTier] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttentionTierFromJSON(json: any): AttentionTier {
    return AttentionTierFromJSONTyped(json, false);
}

export function AttentionTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttentionTier {
    return json as AttentionTier;
}

export function AttentionTierToJSON(value?: AttentionTier | null): any {
    return value as any;
}

export function AttentionTierToJSONTyped(value: any, ignoreDiscriminator: boolean): AttentionTier {
    return value as AttentionTier;
}

