/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Why the *gateway* — not an admin — turned a `model_mappings` row off.
 * `None` on the column means a human decided, and the reconciler leaves the
 * row alone in both directions. Persisted as a nullable `VARCHAR(32)` (see
 * migration V63).
 * @export
 */
export const AutoDisabledReason = {
    CatalogRetired: 'catalog_retired',
} as const;
export type AutoDisabledReason = typeof AutoDisabledReason[keyof typeof AutoDisabledReason];


export function instanceOfAutoDisabledReason(value: any): boolean {
    for (const key in AutoDisabledReason) {
        if (Object.prototype.hasOwnProperty.call(AutoDisabledReason, key)) {
            if (AutoDisabledReason[key as keyof typeof AutoDisabledReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AutoDisabledReasonFromJSON(json: any): AutoDisabledReason {
    return AutoDisabledReasonFromJSONTyped(json, false);
}

export function AutoDisabledReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoDisabledReason {
    return json as AutoDisabledReason;
}

export function AutoDisabledReasonToJSON(value?: AutoDisabledReason | null): any {
    return value as any;
}

export function AutoDisabledReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): AutoDisabledReason {
    return value as AutoDisabledReason;
}

