/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AwsBedrockGuardrailsConnectionResponse
 */
export interface AwsBedrockGuardrailsConnectionResponse {
    /**
     * 
     */
    accessKeyId?: string | null;
    /**
     * 
     */
    authType: string;
    /**
     * 
     */
    endpoint?: string | null;
    /**
     * 
     */
    externalId?: string | null;
    /**
     * 
     */
    guardrailIdentifier: string;
    /**
     * 
     */
    guardrailVersion: string;
    /**
     * 
     */
    hasCredentials: boolean;
    /**
     * 
     */
    iamRoleArn?: string | null;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    region: string;
}

/**
 * Check if a given object implements the AwsBedrockGuardrailsConnectionResponse interface.
 */
export function instanceOfAwsBedrockGuardrailsConnectionResponse(value: object): value is AwsBedrockGuardrailsConnectionResponse {
    if ((!('authType' in (value as Record<string, any>)) && !('auth_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['authType'] === undefined && (value as Record<string, any>)['auth_type'] === undefined)) return false;
    if ((!('guardrailIdentifier' in (value as Record<string, any>)) && !('guardrail_identifier' in (value as Record<string, any>))) || ((value as Record<string, any>)['guardrailIdentifier'] === undefined && (value as Record<string, any>)['guardrail_identifier'] === undefined)) return false;
    if ((!('guardrailVersion' in (value as Record<string, any>)) && !('guardrail_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['guardrailVersion'] === undefined && (value as Record<string, any>)['guardrail_version'] === undefined)) return false;
    if ((!('hasCredentials' in (value as Record<string, any>)) && !('has_credentials' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasCredentials'] === undefined && (value as Record<string, any>)['has_credentials'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    return true;
}

export function AwsBedrockGuardrailsConnectionResponseFromJSON(json: any): AwsBedrockGuardrailsConnectionResponse {
    return AwsBedrockGuardrailsConnectionResponseFromJSONTyped(json, false);
}

export function AwsBedrockGuardrailsConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsBedrockGuardrailsConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'] === undefined ? undefined : json['access_key_id'] === null ? null : json['access_key_id'],
        'authType': json['auth_type'],
        'endpoint': json['endpoint'] === undefined ? undefined : json['endpoint'] === null ? null : json['endpoint'],
        'externalId': json['external_id'] === undefined ? undefined : json['external_id'] === null ? null : json['external_id'],
        'guardrailIdentifier': json['guardrail_identifier'],
        'guardrailVersion': json['guardrail_version'],
        'hasCredentials': json['has_credentials'],
        'iamRoleArn': json['iam_role_arn'] === undefined ? undefined : json['iam_role_arn'] === null ? null : json['iam_role_arn'],
        'orgId': json['org_id'],
        'region': json['region'],
    };
}

export function AwsBedrockGuardrailsConnectionResponseToJSON(json: any): AwsBedrockGuardrailsConnectionResponse {
    return AwsBedrockGuardrailsConnectionResponseToJSONTyped(json, false);
}

export function AwsBedrockGuardrailsConnectionResponseToJSONTyped(value?: AwsBedrockGuardrailsConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'auth_type': value['authType'],
        'endpoint': value['endpoint'],
        'external_id': value['externalId'],
        'guardrail_identifier': value['guardrailIdentifier'],
        'guardrail_version': value['guardrailVersion'],
        'has_credentials': value['hasCredentials'],
        'iam_role_arn': value['iamRoleArn'],
        'org_id': value['orgId'],
        'region': value['region'],
    };
}

