/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Whether Barndoor's own AWS principal is configured for `aws_role` trust.
 * @export
 * @interface AwsRoleConfigResponse
 */
export interface AwsRoleConfigResponse {
    /**
     * True when Barndoor has a principal ARN to put in a customer trust policy.
     */
    configured: boolean;
    /**
     * The ARN customers name as the trusted principal; null when unconfigured.
     */
    principalArn?: string | null;
}

/**
 * Check if a given object implements the AwsRoleConfigResponse interface.
 */
export function instanceOfAwsRoleConfigResponse(value: object): value is AwsRoleConfigResponse {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    return true;
}

export function AwsRoleConfigResponseFromJSON(json: any): AwsRoleConfigResponse {
    return AwsRoleConfigResponseFromJSONTyped(json, false);
}

export function AwsRoleConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsRoleConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'principalArn': json['principal_arn'] === undefined ? undefined : json['principal_arn'] === null ? null : json['principal_arn'],
    };
}

export function AwsRoleConfigResponseToJSON(json: any): AwsRoleConfigResponse {
    return AwsRoleConfigResponseToJSONTyped(json, false);
}

export function AwsRoleConfigResponseToJSONTyped(value?: AwsRoleConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'principal_arn': value['principalArn'],
    };
}

