/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AWSTrustInfoResponse
 */
export interface AWSTrustInfoResponse {
    /**
     * 
     */
    externalId: string;
    /**
     * 
     */
    principalArn: string;
}

/**
 * Check if a given object implements the AWSTrustInfoResponse interface.
 */
export function instanceOfAWSTrustInfoResponse(value: object): value is AWSTrustInfoResponse {
    if ((!('externalId' in (value as Record<string, any>)) && !('external_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['externalId'] === undefined && (value as Record<string, any>)['external_id'] === undefined)) return false;
    if ((!('principalArn' in (value as Record<string, any>)) && !('principal_arn' in (value as Record<string, any>))) || ((value as Record<string, any>)['principalArn'] === undefined && (value as Record<string, any>)['principal_arn'] === undefined)) return false;
    return true;
}

export function AWSTrustInfoResponseFromJSON(json: any): AWSTrustInfoResponse {
    return AWSTrustInfoResponseFromJSONTyped(json, false);
}

export function AWSTrustInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AWSTrustInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'principalArn': json['principal_arn'],
    };
}

export function AWSTrustInfoResponseToJSON(json: any): AWSTrustInfoResponse {
    return AWSTrustInfoResponseToJSONTyped(json, false);
}

export function AWSTrustInfoResponseToJSONTyped(value?: AWSTrustInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'principal_arn': value['principalArn'],
    };
}

