/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AzureContentSafetyConnectionResponse
 */
export interface AzureContentSafetyConnectionResponse {
    /**
     * 
     */
    apiVersion: string;
    /**
     * 
     */
    endpoint: string;
    /**
     * 
     */
    hasApiKey: boolean;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    severityThreshold: number;
}

/**
 * Check if a given object implements the AzureContentSafetyConnectionResponse interface.
 */
export function instanceOfAzureContentSafetyConnectionResponse(value: object): value is AzureContentSafetyConnectionResponse {
    if ((!('apiVersion' in (value as Record<string, any>)) && !('api_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['apiVersion'] === undefined && (value as Record<string, any>)['api_version'] === undefined)) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if ((!('hasApiKey' in (value as Record<string, any>)) && !('has_api_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasApiKey'] === undefined && (value as Record<string, any>)['has_api_key'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('severityThreshold' in (value as Record<string, any>)) && !('severity_threshold' in (value as Record<string, any>))) || ((value as Record<string, any>)['severityThreshold'] === undefined && (value as Record<string, any>)['severity_threshold'] === undefined)) return false;
    return true;
}

export function AzureContentSafetyConnectionResponseFromJSON(json: any): AzureContentSafetyConnectionResponse {
    return AzureContentSafetyConnectionResponseFromJSONTyped(json, false);
}

export function AzureContentSafetyConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureContentSafetyConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['api_version'],
        'endpoint': json['endpoint'],
        'hasApiKey': json['has_api_key'],
        'orgId': json['org_id'],
        'severityThreshold': json['severity_threshold'],
    };
}

export function AzureContentSafetyConnectionResponseToJSON(json: any): AzureContentSafetyConnectionResponse {
    return AzureContentSafetyConnectionResponseToJSONTyped(json, false);
}

export function AzureContentSafetyConnectionResponseToJSONTyped(value?: AzureContentSafetyConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_version': value['apiVersion'],
        'endpoint': value['endpoint'],
        'has_api_key': value['hasApiKey'],
        'org_id': value['orgId'],
        'severity_threshold': value['severityThreshold'],
    };
}

