/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How the vendor bills a provider. Persisted as a nullable `VARCHAR(16)`,
 * required when `billing_mode = 'not_metered'` and optional otherwise (V69
 * CHECK-enforced).
 * 
 * **Independent of [`BillingMode`], not paired with it.** A subscription that
 * bills overages beyond the plan is genuinely per-token *and* genuinely a
 * subscription; requiring the two to agree made that unrepresentable. What
 * survives is the half worth keeping: a provider must not stop recording cost
 * without saying why.
 * 
 * **Label only — nothing branches on this.** That is the point of separating
 * it from [`BillingMode`]: adding a reason touches this enum, its label maps
 * and the CHECK constraint, and never the billing path. If a proposed
 * category needs different *behaviour* (prepaid credits drawing down a
 * balance, committed spend needing a floor), it is a feature, not a variant
 * here.
 * @export
 */
export const BillingReason = {
    Subscription: 'subscription',
    Local: 'local',
    External: 'external',
    Other: 'other',
} as const;
export type BillingReason = typeof BillingReason[keyof typeof BillingReason];


export function instanceOfBillingReason(value: any): boolean {
    for (const key in BillingReason) {
        if (Object.prototype.hasOwnProperty.call(BillingReason, key)) {
            if (BillingReason[key as keyof typeof BillingReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BillingReasonFromJSON(json: any): BillingReason {
    return BillingReasonFromJSONTyped(json, false);
}

export function BillingReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingReason {
    return json as BillingReason;
}

export function BillingReasonToJSON(value?: BillingReason | null): any {
    return value as any;
}

export function BillingReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): BillingReason {
    return value as BillingReason;
}

