/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether the gateway computes a per-token cost for a provider. Persisted as
 * a `VARCHAR(16)` constrained to `per_token | not_metered` (see migration
 * V69, BCP-3876).
 * 
 * Deliberately binary, with the *why* held separately in [`BillingReason`].
 * The reason list is open-ended; this question is not, and never will be.
 * Folding both into one enum would make every "is this zero-cost" check grow
 * an OR-list as reasons are added, and would need a [`PricingSource`] variant
 * per reason — an enum whose values reach ClickHouse, the reporting labels, a
 * frontend union type and three UI modules.
 * 
 * [`PricingSource`]: ai_governance::PricingSource
 * @export
 */
export const BillingMode = {
    PerToken: 'per_token',
    NotMetered: 'not_metered',
} as const;
export type BillingMode = typeof BillingMode[keyof typeof BillingMode];


export function instanceOfBillingMode(value: any): boolean {
    for (const key in BillingMode) {
        if (Object.prototype.hasOwnProperty.call(BillingMode, key)) {
            if (BillingMode[key as keyof typeof BillingMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BillingModeFromJSON(json: any): BillingMode {
    return BillingModeFromJSONTyped(json, false);
}

export function BillingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingMode {
    return json as BillingMode;
}

export function BillingModeToJSON(value?: BillingMode | null): any {
    return value as any;
}

export function BillingModeToJSONTyped(value: any, ignoreDiscriminator: boolean): BillingMode {
    return value as BillingMode;
}

