/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which target dimension the exhausted budget is scoped to. Drives the
 * pill label in the admin Model Mappings page and the user-portal Models
 * page.
 * @export
 */
export const BudgetTargetKind = {
    Provider: 'provider',
    UpstreamModel: 'upstream_model',
    ModelAlias: 'model_alias',
} as const;
export type BudgetTargetKind = typeof BudgetTargetKind[keyof typeof BudgetTargetKind];


export function instanceOfBudgetTargetKind(value: any): boolean {
    for (const key in BudgetTargetKind) {
        if (Object.prototype.hasOwnProperty.call(BudgetTargetKind, key)) {
            if (BudgetTargetKind[key as keyof typeof BudgetTargetKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BudgetTargetKindFromJSON(json: any): BudgetTargetKind {
    return BudgetTargetKindFromJSONTyped(json, false);
}

export function BudgetTargetKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetTargetKind {
    return json as BudgetTargetKind;
}

export function BudgetTargetKindToJSON(value?: BudgetTargetKind | null): any {
    return value as any;
}

export function BudgetTargetKindToJSONTyped(value: any, ignoreDiscriminator: boolean): BudgetTargetKind {
    return value as BudgetTargetKind;
}

