/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Result of sending a stock connectivity-test message through a channel's real transport.
 * 
 * Delivery failure is reported here as `ok: false` with a `200` status, not as an HTTP error:
 * the request to test succeeded, the transport is what failed.
 * @export
 * @interface ChannelTestResponse
 */
export interface ChannelTestResponse {
    /**
     * Whether the test message reached the destination transport.
     */
    ok: boolean;
    /**
     * Why delivery failed, when `ok` is false. `null` on success.
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ChannelTestResponse interface.
 */
export function instanceOfChannelTestResponse(value: object): value is ChannelTestResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function ChannelTestResponseFromJSON(json: any): ChannelTestResponse {
    return ChannelTestResponseFromJSONTyped(json, false);
}

export function ChannelTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
    };
}

export function ChannelTestResponseToJSON(json: any): ChannelTestResponse {
    return ChannelTestResponseToJSONTyped(json, false);
}

export function ChannelTestResponseToJSONTyped(value?: ChannelTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'error': value['error'],
    };
}

