/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertTypeOption } from './AlertTypeOption.js';
import {
    AlertTypeOptionFromJSON,
    AlertTypeOptionFromJSONTyped,
    AlertTypeOptionToJSON,
    AlertTypeOptionToJSONTyped,
} from './AlertTypeOption.js';
import type { LabeledOption } from './LabeledOption.js';
import {
    LabeledOptionFromJSON,
    LabeledOptionFromJSONTyped,
    LabeledOptionToJSON,
    LabeledOptionToJSONTyped,
} from './LabeledOption.js';

/**
 * The subscription vocabulary, enumerated server-side so new alert types appear to every
 * client without a code change. `alert_types` is filtered to what the caller's organization is
 * admitted to; `categories` and `severities` are the full closed label vocabularies the types
 * reference. Fetch this before building a subscription set rather than hardcoding enum names.
 * @export
 * @interface ChannelOptionsResponse
 */
export interface ChannelOptionsResponse {
    /**
     * Every alert type your organization may subscribe a channel to. Authoritative: types withheld here are gated off for this organization and subscribing to one is inert. Read this instead of hardcoding the enum — the set grows over time.
     */
    alertTypes: Array<AlertTypeOption>;
    /**
     * The categories your organization may see, in display order. A category whose every alert type is gated off for this organization is withheld entirely, so it needs no client-side handling; a category that is simply reserved and has no alert types yet is still listed and groups nothing.
     */
    categories: Array<LabeledOption>;
    /**
     * The full severity vocabulary, unfiltered.
     */
    severities: Array<LabeledOption>;
}

/**
 * Check if a given object implements the ChannelOptionsResponse interface.
 */
export function instanceOfChannelOptionsResponse(value: object): value is ChannelOptionsResponse {
    if ((!('alertTypes' in (value as Record<string, any>)) && !('alert_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['alertTypes'] === undefined && (value as Record<string, any>)['alert_types'] === undefined)) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('severities' in value) || value['severities'] === undefined) return false;
    return true;
}

export function ChannelOptionsResponseFromJSON(json: any): ChannelOptionsResponse {
    return ChannelOptionsResponseFromJSONTyped(json, false);
}

export function ChannelOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelOptionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alertTypes': ((json['alert_types'] as Array<any>).map(AlertTypeOptionFromJSON)),
        'categories': ((json['categories'] as Array<any>).map(LabeledOptionFromJSON)),
        'severities': ((json['severities'] as Array<any>).map(LabeledOptionFromJSON)),
    };
}

export function ChannelOptionsResponseToJSON(json: any): ChannelOptionsResponse {
    return ChannelOptionsResponseToJSONTyped(json, false);
}

export function ChannelOptionsResponseToJSONTyped(value?: ChannelOptionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_types': ((value['alertTypes'] as Array<any>).map(AlertTypeOptionToJSON)),
        'categories': ((value['categories'] as Array<any>).map(LabeledOptionToJSON)),
        'severities': ((value['severities'] as Array<any>).map(LabeledOptionToJSON)),
    };
}

