/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertType } from './AlertType.js';
import {
    AlertTypeFromJSON,
    AlertTypeFromJSONTyped,
    AlertTypeToJSON,
    AlertTypeToJSONTyped,
} from './AlertType.js';

/**
 * One alert type this channel is subscribed to.
 * @export
 * @interface ChannelSubscription
 */
export interface ChannelSubscription {
    /**
     * The subscribed alert type.
     */
    alertType: AlertType;
}



/**
 * Check if a given object implements the ChannelSubscription interface.
 */
export function instanceOfChannelSubscription(value: object): value is ChannelSubscription {
    if ((!('alertType' in (value as Record<string, any>)) && !('alert_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['alertType'] === undefined && (value as Record<string, any>)['alert_type'] === undefined)) return false;
    return true;
}

export function ChannelSubscriptionFromJSON(json: any): ChannelSubscription {
    return ChannelSubscriptionFromJSONTyped(json, false);
}

export function ChannelSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'alertType': AlertTypeFromJSON(json['alert_type']),
    };
}

export function ChannelSubscriptionToJSON(json: any): ChannelSubscription {
    return ChannelSubscriptionToJSONTyped(json, false);
}

export function ChannelSubscriptionToJSONTyped(value?: ChannelSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_type': AlertTypeToJSON(value['alertType']),
    };
}

