/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ChannelType } from './ChannelType.js';
import {
    ChannelTypeFromJSON,
    ChannelTypeFromJSONTyped,
    ChannelTypeToJSON,
    ChannelTypeToJSONTyped,
} from './ChannelType.js';
import type { ChannelSubscriptionInput } from './ChannelSubscriptionInput.js';
import {
    ChannelSubscriptionInputFromJSON,
    ChannelSubscriptionInputFromJSONTyped,
    ChannelSubscriptionInputToJSON,
    ChannelSubscriptionInputToJSONTyped,
} from './ChannelSubscriptionInput.js';

/**
 * Create or update one notification channel and replace its subscription set.
 * 
 * This is a full upsert, not a patch: ``subscriptions`` is **replaced** by what you send, so
 * omitting it removes every subscription the channel had. Send the complete desired set on
 * every call — which is what makes the endpoint safe to drive from a declarative tool.
 * 
 * Which fields are permitted depends on ``type``; sending one that does not belong to the
 * type is a ``422``, not a silently ignored field. See ``ChannelType`` for the full matrix.
 * 
 * | ``type`` | required | forbidden |
 * |---|---|---|
 * | ``in_app`` / ``user_email`` | — | every destination field |
 * | ``email`` | ``email_address`` | ``url``, ``label``, ``slack_channel_id``, ``teams_workflow_url`` |
 * | ``webhook`` | ``url`` | ``email_address``, ``label``, ``slack_channel_id``, ``teams_workflow_url`` |
 * | ``slack`` | ``slack_channel_id``, ``label`` | ``email_address``, ``url``, ``teams_workflow_url`` |
 * | ``teams`` | ``label`` (+ ``teams_workflow_url`` on create) | ``email_address``, ``url``, ``slack_channel_id`` |
 * 
 * **Identity.** Without ``id`` the channel is keyed on its type's natural identity, so
 * repeating the same call is idempotent rather than creating duplicates: personal types by
 * (organization, type, caller), ``email`` by (organization, ``email_address``), ``webhook`` by
 * (organization, ``url``), ``slack`` by (organization, ``slack_channel_id``). With ``id`` it is
 * an authoritative edit of that row — the only way to change a ``teams`` channel, whose
 * natural identity is a secret URL you never hold back.
 * @export
 * @interface ChannelUpsertRequest
 */
export interface ChannelUpsertRequest {
    /**
     * Existing channel to edit authoritatively. Omit to create-or-dedup on the type's natural identity (see the model description). When supplied and unknown — or owned by another organization — the request is a `404`, never a create.
     */
    id?: string | null;
    /**
     * The kind of destination, and the discriminator for every other field. Immutable in practice: an edit-by-id that changes `type` is rejected, and an upsert without `id` and a different `type` addresses a different natural identity, so it creates a separate channel.
     */
    type: ChannelType;
    /**
     * Whether the channel delivers. `false` suspends delivery while keeping the channel and its subscriptions intact — the reversible alternative to deleting it.
     */
    enabled?: boolean;
    /**
     * Destination address for `type: email`. Any deliverable address — a team alias or a ticketing inbox, not necessarily a platform user. Validated and normalized; also the channel's natural identity, so reusing an address updates that channel. Forbidden on every other type.
     */
    emailAddress?: string | null;
    /**
     * Destination endpoint for `type: webhook`. Must be `https` and must resolve to a public address — private, loopback, link-local, and cloud-metadata targets are rejected with a `422` naming the reason. Also the channel's natural identity. Forbidden on every other type.
     */
    url?: string | null;
    /**
     * Human-readable name, shown wherever the channel is listed. Required for `slack` and `teams` (for `teams` it is the only non-secret identifier you get back). Forbidden on the other types.
     */
    label?: string | null;
    /**
     * Slack channel id (not its name) for `type: slack`; the organization's Slack app must already be installed. Also the channel's natural identity. Forbidden on every other type.
     */
    slackChannelId?: string | null;
    /**
     * Microsoft Teams Workflows incoming-webhook URL for `type: teams`. Write-only: it is stored as a secret and never returned by any endpoint — reads expose only `has_workflow_url`. Required on create, optional on edit-by-id (omit to keep the stored URL). Must be `https`, resolve to a public address, and sit on the Power Automate host allowlist. Forbidden on every other type.
     */
    teamsWorkflowUrl?: string | null;
    /**
     * The complete set of alert types to deliver to this channel. **Replaces** the channel's existing set — an omitted or empty list unsubscribes it from everything. At most one entry per alert type; duplicates are a `422`.
     */
    subscriptions?: Array<ChannelSubscriptionInput>;
}



/**
 * Check if a given object implements the ChannelUpsertRequest interface.
 */
export function instanceOfChannelUpsertRequest(value: object): value is ChannelUpsertRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ChannelUpsertRequestFromJSON(json: any): ChannelUpsertRequest {
    return ChannelUpsertRequestFromJSONTyped(json, false);
}

export function ChannelUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] === undefined ? undefined : json['id'] === null ? null : json['id'],
        'type': ChannelTypeFromJSON(json['type']),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'emailAddress': json['email_address'] === undefined ? undefined : json['email_address'] === null ? null : json['email_address'],
        'url': json['url'] === undefined ? undefined : json['url'] === null ? null : json['url'],
        'label': json['label'] === undefined ? undefined : json['label'] === null ? null : json['label'],
        'slackChannelId': json['slack_channel_id'] === undefined ? undefined : json['slack_channel_id'] === null ? null : json['slack_channel_id'],
        'teamsWorkflowUrl': json['teams_workflow_url'] === undefined ? undefined : json['teams_workflow_url'] === null ? null : json['teams_workflow_url'],
        'subscriptions': json['subscriptions'] == null ? undefined : ((json['subscriptions'] as Array<any>).map(ChannelSubscriptionInputFromJSON)),
    };
}

export function ChannelUpsertRequestToJSON(json: any): ChannelUpsertRequest {
    return ChannelUpsertRequestToJSONTyped(json, false);
}

export function ChannelUpsertRequestToJSONTyped(value?: ChannelUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': ChannelTypeToJSON(value['type']),
        'enabled': value['enabled'],
        'email_address': value['emailAddress'],
        'url': value['url'],
        'label': value['label'],
        'slack_channel_id': value['slackChannelId'],
        'teams_workflow_url': value['teamsWorkflowUrl'],
        'subscriptions': value['subscriptions'] == null ? undefined : ((value['subscriptions'] as Array<any>).map(ChannelSubscriptionInputToJSON)),
    };
}

