/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertType } from './AlertType.js';
import {
    AlertTypeFromJSON,
    AlertTypeFromJSONTyped,
    AlertTypeToJSON,
    AlertTypeToJSONTyped,
} from './AlertType.js';

/**
 * One alert type the channel matches on.
 * 
 * Named ``Channel``-first deliberately: these schemas are merged by name into the unified
 * public OpenAPI document (scripts/generate-public-openapi.py), where a bare
 * ``SubscriptionResponse`` collided with identity-service's *payment* subscription schema and
 * silently lost the tie. Keep the prefix. A channel receives an alert only if its
 * subscription set contains that alert's type — an empty set means the channel exists but
 * delivers nothing.
 * @export
 * @interface ChannelSubscriptionInput
 */
export interface ChannelSubscriptionInput {
    /**
     * The alert type to deliver to this channel. Must be one of the values returned by `GET /public/v1/channels/options`; subscribing to a type your organization is not admitted to is accepted but inert.
     */
    alertType: AlertType;
}



/**
 * Check if a given object implements the ChannelSubscriptionInput interface.
 */
export function instanceOfChannelSubscriptionInput(value: object): value is ChannelSubscriptionInput {
    if ((!('alertType' in (value as Record<string, any>)) && !('alert_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['alertType'] === undefined && (value as Record<string, any>)['alert_type'] === undefined)) return false;
    return true;
}

export function ChannelSubscriptionInputFromJSON(json: any): ChannelSubscriptionInput {
    return ChannelSubscriptionInputFromJSONTyped(json, false);
}

export function ChannelSubscriptionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSubscriptionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'alertType': AlertTypeFromJSON(json['alert_type']),
    };
}

export function ChannelSubscriptionInputToJSON(json: any): ChannelSubscriptionInput {
    return ChannelSubscriptionInputToJSONTyped(json, false);
}

export function ChannelSubscriptionInputToJSONTyped(value?: ChannelSubscriptionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_type': AlertTypeToJSON(value['alertType']),
    };
}

