/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * The attribution carried on an admin-configurable row, as returned to the
 * portal.
 * 
 * Every field is `Option` and nothing is backfilled: a row that predates V75
 * has no truthful actor to attribute it to, and inventing one would be worse
 * than rendering a placeholder. Rows pick up attribution on their first
 * write.
 * @export
 * @interface ChangeAttribution
 */
export interface ChangeAttribution {
    /**
     * 
     */
    createdByEmail?: string | null;
    /**
     * 
     */
    createdByName?: string | null;
    /**
     * 
     */
    createdByUserId?: string | null;
    /**
     * Optional free text explaining *why* the last change was made
     * ("Raised for the Q3 batch job", "Vendor deprecated the old endpoint").
     * 
     * Admin-authored and rendered in the portal, so it is untrusted input:
     * length-capped here, escaped on render.
     */
    lastChangeNote?: string | null;
    /**
     * When the change named by `last_modified_by_*` happened.
     * 
     * Its own column rather than the row's `updated_at`, because `updated_at`
     * is bumped by writes nobody is attributed for -- pairing the two would
     * date a named admin's edit to a background job's clock. See the V75
     * migration for the full reasoning.
     */
    lastModifiedAt?: Date | null;
    /**
     * 
     */
    lastModifiedByEmail?: string | null;
    /**
     * 
     */
    lastModifiedByName?: string | null;
    /**
     * 
     */
    lastModifiedByUserId?: string | null;
}

/**
 * Check if a given object implements the ChangeAttribution interface.
 */
export function instanceOfChangeAttribution(value: object): value is ChangeAttribution {
    return true;
}

export function ChangeAttributionFromJSON(json: any): ChangeAttribution {
    return ChangeAttributionFromJSONTyped(json, false);
}

export function ChangeAttributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeAttribution {
    if (json == null) {
        return json;
    }
    return {
        
        'createdByEmail': json['created_by_email'] === undefined ? undefined : json['created_by_email'] === null ? null : json['created_by_email'],
        'createdByName': json['created_by_name'] === undefined ? undefined : json['created_by_name'] === null ? null : json['created_by_name'],
        'createdByUserId': json['created_by_user_id'] === undefined ? undefined : json['created_by_user_id'] === null ? null : json['created_by_user_id'],
        'lastChangeNote': json['last_change_note'] === undefined ? undefined : json['last_change_note'] === null ? null : json['last_change_note'],
        'lastModifiedAt': json['last_modified_at'] === undefined ? undefined : json['last_modified_at'] === null ? null : (parseDateTime(json['last_modified_at'])),
        'lastModifiedByEmail': json['last_modified_by_email'] === undefined ? undefined : json['last_modified_by_email'] === null ? null : json['last_modified_by_email'],
        'lastModifiedByName': json['last_modified_by_name'] === undefined ? undefined : json['last_modified_by_name'] === null ? null : json['last_modified_by_name'],
        'lastModifiedByUserId': json['last_modified_by_user_id'] === undefined ? undefined : json['last_modified_by_user_id'] === null ? null : json['last_modified_by_user_id'],
    };
}

export function ChangeAttributionToJSON(json: any): ChangeAttribution {
    return ChangeAttributionToJSONTyped(json, false);
}

export function ChangeAttributionToJSONTyped(value?: ChangeAttribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by_email': value['createdByEmail'],
        'created_by_name': value['createdByName'],
        'created_by_user_id': value['createdByUserId'],
        'last_change_note': value['lastChangeNote'],
        'last_modified_at': value['lastModifiedAt'] == null ? value['lastModifiedAt'] : serializeDateTime(value['lastModifiedAt']),
        'last_modified_by_email': value['lastModifiedByEmail'],
        'last_modified_by_name': value['lastModifiedByName'],
        'last_modified_by_user_id': value['lastModifiedByUserId'],
    };
}

