/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OfInner } from './OfInner.js';
import {
    OfInnerFromJSON,
    OfInnerFromJSONTyped,
    OfInnerToJSON,
    OfInnerToJSONTyped,
} from './OfInner.js';

/**
 * 
 * @export
 * @interface ConditionOfInput
 */
export interface ConditionOfInput {
    /**
     * Operand list for the enclosing `all`/`any`/`none` combinator. Each operand is itself a matcher — either `{"expr": "..."}` or a further nested combinator.
     */
    of: Array<OfInner>;
}

/**
 * Check if a given object implements the ConditionOfInput interface.
 */
export function instanceOfConditionOfInput(value: object): value is ConditionOfInput {
    if (!('of' in value) || value['of'] === undefined) return false;
    return true;
}

export function ConditionOfInputFromJSON(json: any): ConditionOfInput {
    return ConditionOfInputFromJSONTyped(json, false);
}

export function ConditionOfInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConditionOfInput {
    if (json == null) {
        return json;
    }
    return {
        
        'of': ((json['of'] as Array<any>).map(OfInnerFromJSON)),
    };
}

export function ConditionOfInputToJSON(json: any): ConditionOfInput {
    return ConditionOfInputToJSONTyped(json, false);
}

export function ConditionOfInputToJSONTyped(value?: ConditionOfInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'of': ((value['of'] as Array<any>).map(OfInnerToJSON)),
    };
}

