/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConfigureDestinationRequest
 */
export interface ConfigureDestinationRequest {
    /**
     * 
     */
    accessKeyId?: string;
    /**
     * 
     */
    accountKey?: string;
    /**
     * 
     */
    authMethod?: string;
    /**
     * 
     */
    bucket?: string;
    /**
     * 
     */
    endpoint?: string;
    /**
     * 
     */
    iamRoleArn?: string;
    /**
     * 
     */
    pathPrefix?: string;
    /**
     * 
     */
    provider?: string;
    /**
     * 
     */
    region?: string;
    /**
     * 
     */
    sasToken?: string;
    /**
     * 
     */
    secretAccessKey?: string;
    /**
     * 
     */
    usePathStyle?: boolean;
    /**
     * 
     */
    useSsl?: boolean;
}

/**
 * Check if a given object implements the ConfigureDestinationRequest interface.
 */
export function instanceOfConfigureDestinationRequest(value: object): value is ConfigureDestinationRequest {
    return true;
}

export function ConfigureDestinationRequestFromJSON(json: any): ConfigureDestinationRequest {
    return ConfigureDestinationRequestFromJSONTyped(json, false);
}

export function ConfigureDestinationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigureDestinationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'] == null ? undefined : json['access_key_id'],
        'accountKey': json['account_key'] == null ? undefined : json['account_key'],
        'authMethod': json['auth_method'] == null ? undefined : json['auth_method'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'iamRoleArn': json['iam_role_arn'] == null ? undefined : json['iam_role_arn'],
        'pathPrefix': json['path_prefix'] == null ? undefined : json['path_prefix'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'region': json['region'] == null ? undefined : json['region'],
        'sasToken': json['sas_token'] == null ? undefined : json['sas_token'],
        'secretAccessKey': json['secret_access_key'] == null ? undefined : json['secret_access_key'],
        'usePathStyle': json['use_path_style'] == null ? undefined : json['use_path_style'],
        'useSsl': json['use_ssl'] == null ? undefined : json['use_ssl'],
    };
}

export function ConfigureDestinationRequestToJSON(json: any): ConfigureDestinationRequest {
    return ConfigureDestinationRequestToJSONTyped(json, false);
}

export function ConfigureDestinationRequestToJSONTyped(value?: ConfigureDestinationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'account_key': value['accountKey'],
        'auth_method': value['authMethod'],
        'bucket': value['bucket'],
        'endpoint': value['endpoint'],
        'iam_role_arn': value['iamRoleArn'],
        'path_prefix': value['pathPrefix'],
        'provider': value['provider'],
        'region': value['region'],
        'sas_token': value['sasToken'],
        'secret_access_key': value['secretAccessKey'],
        'use_path_style': value['usePathStyle'],
        'use_ssl': value['useSsl'],
    };
}

