/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Response model after initiating a connection.
 * @export
 * @interface ConnectionInitiateResponse
 */
export interface ConnectionInitiateResponse {
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    authUrl?: string | null;
    /**
     * 
     */
    state: string;
    /**
     * 
     */
    message: string;
}

/**
 * Check if a given object implements the ConnectionInitiateResponse interface.
 */
export function instanceOfConnectionInitiateResponse(value: object): value is ConnectionInitiateResponse {
    if ((!('connectionId' in (value as Record<string, any>)) && !('connection_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['connectionId'] === undefined && (value as Record<string, any>)['connection_id'] === undefined)) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ConnectionInitiateResponseFromJSON(json: any): ConnectionInitiateResponse {
    return ConnectionInitiateResponseFromJSONTyped(json, false);
}

export function ConnectionInitiateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionInitiateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'],
        'authUrl': json['auth_url'] === undefined ? undefined : json['auth_url'] === null ? null : json['auth_url'],
        'state': json['state'],
        'message': json['message'],
    };
}

export function ConnectionInitiateResponseToJSON(json: any): ConnectionInitiateResponse {
    return ConnectionInitiateResponseToJSONTyped(json, false);
}

export function ConnectionInitiateResponseToJSONTyped(value?: ConnectionInitiateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'auth_url': value['authUrl'],
        'state': value['state'],
        'message': value['message'],
    };
}

