/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A route's cooldown policy, one field per column.
 * 
 * Route-health *state* is keyed by `(provider_id, upstream_model)`, so an
 * enablement row and an alias row that target the same upstream share one
 * failure window and ejection deadline; each request judges that shared
 * state by the policy of the row it resolved.
 * @export
 * @interface CooldownPolicy
 */
export interface CooldownPolicy {
    /**
     * Cooldown on a 429 with no usable `Retry-After`, seconds.
     */
    cooldown429DefaultSecs: number;
    /**
     * First cooldown window, doubled on each failed recovery probe up to
     * `cooldown_max_secs`.
     */
    cooldownBaseSecs: number;
    /**
     * Gateway failures within `cooldown_window_secs` that cool the route.
     * `0` disables every cooldown of the shared route.
     */
    cooldownFailureThreshold: number;
    /**
     * Cap on every cooldown window.
     */
    cooldownMaxSecs: number;
    /**
     * Flat cooldown on a 529 "overloaded" with no usable `Retry-After`,
     * seconds. `0` counts a 529 as an ordinary gateway failure instead.
     */
    cooldownOverloadedSecs: number;
    /**
     * Width of the rolling failure window, seconds.
     */
    cooldownWindowSecs: number;
}

/**
 * Check if a given object implements the CooldownPolicy interface.
 */
export function instanceOfCooldownPolicy(value: object): value is CooldownPolicy {
    if ((!('cooldown429DefaultSecs' in (value as Record<string, any>)) && !('cooldown_429_default_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldown429DefaultSecs'] === undefined && (value as Record<string, any>)['cooldown_429_default_secs'] === undefined)) return false;
    if ((!('cooldownBaseSecs' in (value as Record<string, any>)) && !('cooldown_base_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldownBaseSecs'] === undefined && (value as Record<string, any>)['cooldown_base_secs'] === undefined)) return false;
    if ((!('cooldownFailureThreshold' in (value as Record<string, any>)) && !('cooldown_failure_threshold' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldownFailureThreshold'] === undefined && (value as Record<string, any>)['cooldown_failure_threshold'] === undefined)) return false;
    if ((!('cooldownMaxSecs' in (value as Record<string, any>)) && !('cooldown_max_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldownMaxSecs'] === undefined && (value as Record<string, any>)['cooldown_max_secs'] === undefined)) return false;
    if ((!('cooldownOverloadedSecs' in (value as Record<string, any>)) && !('cooldown_overloaded_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldownOverloadedSecs'] === undefined && (value as Record<string, any>)['cooldown_overloaded_secs'] === undefined)) return false;
    if ((!('cooldownWindowSecs' in (value as Record<string, any>)) && !('cooldown_window_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['cooldownWindowSecs'] === undefined && (value as Record<string, any>)['cooldown_window_secs'] === undefined)) return false;
    return true;
}

export function CooldownPolicyFromJSON(json: any): CooldownPolicy {
    return CooldownPolicyFromJSONTyped(json, false);
}

export function CooldownPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CooldownPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'cooldown429DefaultSecs': json['cooldown_429_default_secs'],
        'cooldownBaseSecs': json['cooldown_base_secs'],
        'cooldownFailureThreshold': json['cooldown_failure_threshold'],
        'cooldownMaxSecs': json['cooldown_max_secs'],
        'cooldownOverloadedSecs': json['cooldown_overloaded_secs'],
        'cooldownWindowSecs': json['cooldown_window_secs'],
    };
}

export function CooldownPolicyToJSON(json: any): CooldownPolicy {
    return CooldownPolicyToJSONTyped(json, false);
}

export function CooldownPolicyToJSONTyped(value?: CooldownPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cooldown_429_default_secs': value['cooldown429DefaultSecs'],
        'cooldown_base_secs': value['cooldownBaseSecs'],
        'cooldown_failure_threshold': value['cooldownFailureThreshold'],
        'cooldown_max_secs': value['cooldownMaxSecs'],
        'cooldown_overloaded_secs': value['cooldownOverloadedSecs'],
        'cooldown_window_secs': value['cooldownWindowSecs'],
    };
}

