/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ModelSource } from './ModelSource.js';
import {
    ModelSourceFromJSON,
    ModelSourceFromJSONTyped,
    ModelSourceToJSON,
    ModelSourceToJSONTyped,
} from './ModelSource.js';

/**
 * 
 * @export
 * @interface CreateModelMappingRequest
 */
export interface CreateModelMappingRequest {
    /**
     * Whether this row should participate in bare-name resolution. The
     * admin handler treats `None` as "infer from alias shape" — custom
     * aliases imply `true`, 1:1 enablement rows imply `false`. Pass
     * `Some(true)` explicitly from the Model Routes tab to opt a 1:1
     * row into bare resolution.
     */
    bareAlias?: boolean | null;
    /**
     * Optional free-text note explaining why this route was added
     * (BCP-3998). Surfaced on the row and mirrored into the audit event.
     */
    changeNote?: string | null;
    /**
     * Cooldown on an upstream 429 that carries no usable `Retry-After`
     * (a `Retry-After` sets the window instead). Range 1-3600, and at most
     * `cooldown_max_secs`; default 30.
     */
    cooldown429DefaultSecs?: number | null;
    /**
     * First cooldown window once the threshold trips, doubled on each failed
     * recovery probe up to `cooldown_max_secs`. Range 1-3600, and at most
     * `cooldown_max_secs`; default 30.
     */
    cooldownBaseSecs?: number | null;
    /**
     * Gateway failures (5xx, timeouts, connection errors, managed-key 401/403)
     * within `cooldown_window_secs` that cool the route. `0` disables every
     * cooldown of the shared route (rolling failures, 429 and 529); per-user
     * credential cooldowns on passthrough routes still apply. Range 0-100;
     * default 10.
     */
    cooldownFailureThreshold?: number | null;
    /**
     * Cap on every cooldown window: doubling, 429 and 529. Range 1-86400;
     * default 300.
     */
    cooldownMaxSecs?: number | null;
    /**
     * Flat cooldown on an upstream 529 "overloaded" with no usable
     * `Retry-After`; it does not spend the failure budget. `0` counts a 529 as
     * an ordinary gateway failure instead. Range 0-3600, and at most
     * `cooldown_max_secs` unless 0; default 10.
     */
    cooldownOverloadedSecs?: number | null;
    /**
     * Width of the rolling failure window, seconds. Range 1-3600; default 60.
     */
    cooldownWindowSecs?: number | null;
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    modelAlias: string;
    /**
     * 
     */
    priority?: number;
    /**
     * 
     */
    providerId: string;
    /**
     * Per-mapping total-request timeout for non-streaming responses
     * (streaming responses have no total timeout). On a custom-alias row
     * this sets the *route* tier; on a 1:1 enablement (anchor) row it sets
     * the *model* tier consulted for every alias of that model. `None` (the
     * default) lets `model_mappings.create` write the platform default
     * (`TOTAL_REQUEST_TIMEOUT_DEFAULT_SECS`) at the route tier. The range is
     * fixed platform policy
     * (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`);
     * see [`crate::proxy::timeouts`].
     */
    requestTimeoutSecs?: number | null;
    /**
     * Same-route retries on upstream 429. 0 means immediate failover.
     */
    retryOn429Count?: number;
    /**
     * Cap on honoring upstream `Retry-After`. 0 means use a small default.
     */
    retryOn429MaxWaitSecs?: number;
    /**
     * Where this model came from. The Add Models dialog sends `Custom` from
     * its free-text branch and `Catalog` from the picker; those two paths
     * already differ client-side, and this is what carries the difference
     * through to storage.
     * 
     * `None` means "infer": the handler inherits the anchor's provenance
     * when one exists (so a route created on Model Routes agrees with the
     * enablement it points at), and otherwise falls back to `Catalog`. SDK
     * and curl callers therefore land on `Catalog` by default — accepted,
     * since the pill exists to catch a typo in the UI and an API caller is
     * not its audience.
     */
    source?: ModelSource | null;
    /**
     * Per-mapping stream-idle (per-chunk) timeout for streaming responses.
     * `None` (the default) lets `model_mappings.create` write the platform
     * default (`STREAM_IDLE_TIMEOUT_DEFAULT_SECS`) at the route tier. The
     * range is fixed platform policy
     * (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`); see
     * [`crate::proxy::timeouts`].
     */
    streamIdleTimeoutSecs?: number | null;
    /**
     * 
     */
    upstreamModel: string;
}



/**
 * Check if a given object implements the CreateModelMappingRequest interface.
 */
export function instanceOfCreateModelMappingRequest(value: object): value is CreateModelMappingRequest {
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if ((!('providerId' in (value as Record<string, any>)) && !('provider_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerId'] === undefined && (value as Record<string, any>)['provider_id'] === undefined)) return false;
    if ((!('upstreamModel' in (value as Record<string, any>)) && !('upstream_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['upstreamModel'] === undefined && (value as Record<string, any>)['upstream_model'] === undefined)) return false;
    return true;
}

export function CreateModelMappingRequestFromJSON(json: any): CreateModelMappingRequest {
    return CreateModelMappingRequestFromJSONTyped(json, false);
}

export function CreateModelMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModelMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bareAlias': json['bare_alias'] === undefined ? undefined : json['bare_alias'] === null ? null : json['bare_alias'],
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'cooldown429DefaultSecs': json['cooldown_429_default_secs'] === undefined ? undefined : json['cooldown_429_default_secs'] === null ? null : json['cooldown_429_default_secs'],
        'cooldownBaseSecs': json['cooldown_base_secs'] === undefined ? undefined : json['cooldown_base_secs'] === null ? null : json['cooldown_base_secs'],
        'cooldownFailureThreshold': json['cooldown_failure_threshold'] === undefined ? undefined : json['cooldown_failure_threshold'] === null ? null : json['cooldown_failure_threshold'],
        'cooldownMaxSecs': json['cooldown_max_secs'] === undefined ? undefined : json['cooldown_max_secs'] === null ? null : json['cooldown_max_secs'],
        'cooldownOverloadedSecs': json['cooldown_overloaded_secs'] === undefined ? undefined : json['cooldown_overloaded_secs'] === null ? null : json['cooldown_overloaded_secs'],
        'cooldownWindowSecs': json['cooldown_window_secs'] === undefined ? undefined : json['cooldown_window_secs'] === null ? null : json['cooldown_window_secs'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'modelAlias': json['model_alias'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'providerId': json['provider_id'],
        'requestTimeoutSecs': json['request_timeout_secs'] === undefined ? undefined : json['request_timeout_secs'] === null ? null : json['request_timeout_secs'],
        'retryOn429Count': json['retry_on_429_count'] == null ? undefined : json['retry_on_429_count'],
        'retryOn429MaxWaitSecs': json['retry_on_429_max_wait_secs'] == null ? undefined : json['retry_on_429_max_wait_secs'],
        'source': json['source'] === undefined ? undefined : json['source'] === null ? null : ModelSourceFromJSON(json['source']),
        'streamIdleTimeoutSecs': json['stream_idle_timeout_secs'] === undefined ? undefined : json['stream_idle_timeout_secs'] === null ? null : json['stream_idle_timeout_secs'],
        'upstreamModel': json['upstream_model'],
    };
}

export function CreateModelMappingRequestToJSON(json: any): CreateModelMappingRequest {
    return CreateModelMappingRequestToJSONTyped(json, false);
}

export function CreateModelMappingRequestToJSONTyped(value?: CreateModelMappingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bare_alias': value['bareAlias'],
        'change_note': value['changeNote'],
        'cooldown_429_default_secs': value['cooldown429DefaultSecs'],
        'cooldown_base_secs': value['cooldownBaseSecs'],
        'cooldown_failure_threshold': value['cooldownFailureThreshold'],
        'cooldown_max_secs': value['cooldownMaxSecs'],
        'cooldown_overloaded_secs': value['cooldownOverloadedSecs'],
        'cooldown_window_secs': value['cooldownWindowSecs'],
        'enabled': value['enabled'],
        'model_alias': value['modelAlias'],
        'priority': value['priority'],
        'provider_id': value['providerId'],
        'request_timeout_secs': value['requestTimeoutSecs'],
        'retry_on_429_count': value['retryOn429Count'],
        'retry_on_429_max_wait_secs': value['retryOn429MaxWaitSecs'],
        'source': ModelSourceToJSON(value['source']),
        'stream_idle_timeout_secs': value['streamIdleTimeoutSecs'],
        'upstream_model': value['upstreamModel'],
    };
}

