/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateApiKeyResponse
 */
export interface CreateApiKeyResponse {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    expiresAt?: Date | null;
    /**
     * 
     */
    groupName?: string | null;
    /**
     * 
     */
    id: string;
    /**
     * The full API key — only returned at creation time, never stored.
     */
    key: string;
    /**
     * 
     */
    keyPrefix: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    scopes: Array<string>;
}

/**
 * Check if a given object implements the CreateApiKeyResponse interface.
 */
export function instanceOfCreateApiKeyResponse(value: object): value is CreateApiKeyResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if ((!('keyPrefix' in (value as Record<string, any>)) && !('key_prefix' in (value as Record<string, any>))) || ((value as Record<string, any>)['keyPrefix'] === undefined && (value as Record<string, any>)['key_prefix'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    return true;
}

export function CreateApiKeyResponseFromJSON(json: any): CreateApiKeyResponse {
    return CreateApiKeyResponseFromJSONTyped(json, false);
}

export function CreateApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'expiresAt': json['expires_at'] === undefined ? undefined : json['expires_at'] === null ? null : (parseDateTime(json['expires_at'])),
        'groupName': json['group_name'] === undefined ? undefined : json['group_name'] === null ? null : json['group_name'],
        'id': json['id'],
        'key': json['key'],
        'keyPrefix': json['key_prefix'],
        'name': json['name'],
        'scopes': json['scopes'],
    };
}

export function CreateApiKeyResponseToJSON(json: any): CreateApiKeyResponse {
    return CreateApiKeyResponseToJSONTyped(json, false);
}

export function CreateApiKeyResponseToJSONTyped(value?: CreateApiKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'group_name': value['groupName'],
        'id': value['id'],
        'key': value['key'],
        'key_prefix': value['keyPrefix'],
        'name': value['name'],
        'scopes': value['scopes'],
    };
}

