/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAllowListEntryRequest
 */
export interface CreateAllowListEntryRequest {
    /**
     * 
     */
    detectionTypes?: Array<string> | null;
    /**
     * 
     */
    pattern: string;
    /**
     * 
     */
    patternType: string;
    /**
     * 
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the CreateAllowListEntryRequest interface.
 */
export function instanceOfCreateAllowListEntryRequest(value: object): value is CreateAllowListEntryRequest {
    if (!('pattern' in value) || value['pattern'] === undefined) return false;
    if ((!('patternType' in (value as Record<string, any>)) && !('pattern_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['patternType'] === undefined && (value as Record<string, any>)['pattern_type'] === undefined)) return false;
    return true;
}

export function CreateAllowListEntryRequestFromJSON(json: any): CreateAllowListEntryRequest {
    return CreateAllowListEntryRequestFromJSONTyped(json, false);
}

export function CreateAllowListEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAllowListEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'detectionTypes': json['detection_types'] === undefined ? undefined : json['detection_types'] === null ? null : json['detection_types'],
        'pattern': json['pattern'],
        'patternType': json['pattern_type'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function CreateAllowListEntryRequestToJSON(json: any): CreateAllowListEntryRequest {
    return CreateAllowListEntryRequestToJSONTyped(json, false);
}

export function CreateAllowListEntryRequestToJSONTyped(value?: CreateAllowListEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detection_types': value['detectionTypes'],
        'pattern': value['pattern'],
        'pattern_type': value['patternType'],
        'reason': value['reason'],
    };
}

