/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ModelAccessTarget } from './ModelAccessTarget.js';
import {
    ModelAccessTargetFromJSON,
    ModelAccessTargetFromJSONTyped,
    ModelAccessTargetToJSON,
    ModelAccessTargetToJSONTyped,
} from './ModelAccessTarget.js';

/**
 * 
 * @export
 * @interface CreateModelAccessRequest
 */
export interface CreateModelAccessRequest {
    /**
     * Optional free-text note explaining why this policy was created
     * (BCP-3998). Surfaced on the row and mirrored into the audit event.
     */
    changeNote?: string | null;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    policyType: string;
    /**
     * Single-entity form of `scope_ids`, kept for existing clients. Send one
     * or the other; when both are sent `scope_id` must be the first element
     * of `scope_ids`.
     */
    scopeId?: string | null;
    /**
     * Every user / project / API key / agent the policy applies to
     * (BCP-5001). The policy applies when any one of them matches the caller.
     * Empty or omitted means not bound to a specific entity.
     */
    scopeIds?: Array<string> | null;
    /**
     * 
     */
    scopeType: string;
    /**
     * Single-entity form of `scope_values`; same rules as `scope_id`.
     */
    scopeValue?: string | null;
    /**
     * Every role / group name the policy applies to (BCP-5001). Same
     * any-of semantics as `scope_ids`.
     */
    scopeValues?: Array<string> | null;
    /**
     * 
     */
    targets: Array<ModelAccessTarget>;
    /**
     * 
     */
    trafficType?: string;
}

/**
 * Check if a given object implements the CreateModelAccessRequest interface.
 */
export function instanceOfCreateModelAccessRequest(value: object): value is CreateModelAccessRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('policyType' in (value as Record<string, any>)) && !('policy_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyType'] === undefined && (value as Record<string, any>)['policy_type'] === undefined)) return false;
    if ((!('scopeType' in (value as Record<string, any>)) && !('scope_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['scopeType'] === undefined && (value as Record<string, any>)['scope_type'] === undefined)) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    return true;
}

export function CreateModelAccessRequestFromJSON(json: any): CreateModelAccessRequest {
    return CreateModelAccessRequestFromJSONTyped(json, false);
}

export function CreateModelAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModelAccessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'name': json['name'],
        'policyType': json['policy_type'],
        'scopeId': json['scope_id'] === undefined ? undefined : json['scope_id'] === null ? null : json['scope_id'],
        'scopeIds': json['scope_ids'] === undefined ? undefined : json['scope_ids'] === null ? null : json['scope_ids'],
        'scopeType': json['scope_type'],
        'scopeValue': json['scope_value'] === undefined ? undefined : json['scope_value'] === null ? null : json['scope_value'],
        'scopeValues': json['scope_values'] === undefined ? undefined : json['scope_values'] === null ? null : json['scope_values'],
        'targets': ((json['targets'] as Array<any>).map(ModelAccessTargetFromJSON)),
        'trafficType': json['traffic_type'] == null ? undefined : json['traffic_type'],
    };
}

export function CreateModelAccessRequestToJSON(json: any): CreateModelAccessRequest {
    return CreateModelAccessRequestToJSONTyped(json, false);
}

export function CreateModelAccessRequestToJSONTyped(value?: CreateModelAccessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'name': value['name'],
        'policy_type': value['policyType'],
        'scope_id': value['scopeId'],
        'scope_ids': value['scopeIds'],
        'scope_type': value['scopeType'],
        'scope_value': value['scopeValue'],
        'scope_values': value['scopeValues'],
        'targets': ((value['targets'] as Array<any>).map(ModelAccessTargetToJSON)),
        'traffic_type': value['trafficType'],
    };
}

