/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BillingReason } from './BillingReason.js';
import {
    BillingReasonFromJSON,
    BillingReasonFromJSONTyped,
    BillingReasonToJSON,
    BillingReasonToJSONTyped,
} from './BillingReason.js';
import type { BillingMode } from './BillingMode.js';
import {
    BillingModeFromJSON,
    BillingModeFromJSONTyped,
    BillingModeToJSON,
    BillingModeToJSONTyped,
} from './BillingMode.js';
import type { ModelSyncMode } from './ModelSyncMode.js';
import {
    ModelSyncModeFromJSON,
    ModelSyncModeFromJSONTyped,
    ModelSyncModeToJSON,
    ModelSyncModeToJSONTyped,
} from './ModelSyncMode.js';

/**
 * 
 * @export
 * @interface CreateProviderRequest
 */
export interface CreateProviderRequest {
    /**
     * The provider's upstream API key. Required when `connection_id` is not supplied.
     */
    apiKey?: string | null;
    /**
     * 
     */
    authType?: string | null;
    /**
     * 
     */
    baseUrl: string;
    /**
     * Whether the gateway records a per-token cost (BCP-3876). Omitted means
     * `per_token` — a provider never stops recording cost by default, and
     * nothing is inferred server-side. The create form *suggests* from the
     * catalog entry and the auth type; `openrouter` is why inference would be
     * wrong (it ships `pricing: []` and is API-billed).
     */
    billingMode?: BillingMode | null;
    /**
     * Optional free-text context for the arrangement, max
     * [`BILLING_NOTE_MAX_LEN`] chars.
     */
    billingNote?: string | null;
    /**
     * How the vendor bills. Required when `billing_mode` is `not_metered`,
     * optional otherwise — see `validate_billing_fields`.
     */
    billingReason?: BillingReason | null;
    /**
     * Optional reference to a provider_catalog entry.
     */
    catalogId?: string | null;
    /**
     * Optional free-text note explaining why this provider was added
     * (BCP-3998). Distinct from `billing_note`, which describes the *billing
     * arrangement* and persists; this describes one change and is replaced by
     * the next edit's note.
     */
    changeNote?: string | null;
    /**
     * Optional reference to a connection for shared credentials.
     */
    connectionId?: string | null;
    /**
     * Structured provider credentials. Preferred over `api_key` for
     * provider-specific auth schemas; never returned by any API.
     */
    credentials?: any | null;
    /**
     * Whether routing should gate on the connectivity health check.
     * `None`/omitted defaults to `true` (enforce). Set `false` to override
     * the gate and serve the provider even when its probe fails.
     */
    enforceHealthCheck?: boolean | null;
    /**
     * 
     */
    modelProvider: string;
    /**
     * Whether this provider tracks Barndoor's model catalog (BCP-3811).
     * Omitted means `off` — a provider is never enrolled by default.
     */
    modelSyncMode?: ModelSyncMode | null;
    /**
     * Upstream models to auto-create as 1:1 model mappings (alias = upstream name).
     */
    models?: Array<string>;
    /**
     * 
     */
    name: string;
    /**
     * Provider-tier total-request timeout override (non-streaming).
     * Operator-only and `None` by default: the effective value is written at
     * the route tier (`model_mappings`), so this applies only if a route row
     * leaves it unset, and then to every such route served by this provider.
     * The range is fixed platform policy
     * (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`); see
     * [`crate::proxy::timeouts`].
     */
    requestTimeoutSecs?: number | null;
    /**
     * 
     */
    settings?: any | null;
    /**
     * Provider-tier stream-idle timeout override (streaming). Operator-only
     * and `None` by default; the effective value is written at the route
     * tier (`model_mappings`). The range is fixed platform policy
     * (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`); see
     * [`crate::proxy::timeouts`].
     */
    streamIdleTimeoutSecs?: number | null;
}



/**
 * Check if a given object implements the CreateProviderRequest interface.
 */
export function instanceOfCreateProviderRequest(value: object): value is CreateProviderRequest {
    if ((!('baseUrl' in (value as Record<string, any>)) && !('base_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseUrl'] === undefined && (value as Record<string, any>)['base_url'] === undefined)) return false;
    if ((!('modelProvider' in (value as Record<string, any>)) && !('model_provider' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelProvider'] === undefined && (value as Record<string, any>)['model_provider'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProviderRequestFromJSON(json: any): CreateProviderRequest {
    return CreateProviderRequestFromJSONTyped(json, false);
}

export function CreateProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] === undefined ? undefined : json['api_key'] === null ? null : json['api_key'],
        'authType': json['auth_type'] === undefined ? undefined : json['auth_type'] === null ? null : json['auth_type'],
        'baseUrl': json['base_url'],
        'billingMode': json['billing_mode'] === undefined ? undefined : json['billing_mode'] === null ? null : BillingModeFromJSON(json['billing_mode']),
        'billingNote': json['billing_note'] === undefined ? undefined : json['billing_note'] === null ? null : json['billing_note'],
        'billingReason': json['billing_reason'] === undefined ? undefined : json['billing_reason'] === null ? null : BillingReasonFromJSON(json['billing_reason']),
        'catalogId': json['catalog_id'] === undefined ? undefined : json['catalog_id'] === null ? null : json['catalog_id'],
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'connectionId': json['connection_id'] === undefined ? undefined : json['connection_id'] === null ? null : json['connection_id'],
        'credentials': json['credentials'] === undefined ? undefined : json['credentials'] === null ? null : json['credentials'],
        'enforceHealthCheck': json['enforce_health_check'] === undefined ? undefined : json['enforce_health_check'] === null ? null : json['enforce_health_check'],
        'modelProvider': json['model_provider'],
        'modelSyncMode': json['model_sync_mode'] === undefined ? undefined : json['model_sync_mode'] === null ? null : ModelSyncModeFromJSON(json['model_sync_mode']),
        'models': json['models'] == null ? undefined : json['models'],
        'name': json['name'],
        'requestTimeoutSecs': json['request_timeout_secs'] === undefined ? undefined : json['request_timeout_secs'] === null ? null : json['request_timeout_secs'],
        'settings': json['settings'] === undefined ? undefined : json['settings'] === null ? null : json['settings'],
        'streamIdleTimeoutSecs': json['stream_idle_timeout_secs'] === undefined ? undefined : json['stream_idle_timeout_secs'] === null ? null : json['stream_idle_timeout_secs'],
    };
}

export function CreateProviderRequestToJSON(json: any): CreateProviderRequest {
    return CreateProviderRequestToJSONTyped(json, false);
}

export function CreateProviderRequestToJSONTyped(value?: CreateProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'auth_type': value['authType'],
        'base_url': value['baseUrl'],
        'billing_mode': BillingModeToJSON(value['billingMode']),
        'billing_note': value['billingNote'],
        'billing_reason': BillingReasonToJSON(value['billingReason']),
        'catalog_id': value['catalogId'],
        'change_note': value['changeNote'],
        'connection_id': value['connectionId'],
        'credentials': value['credentials'],
        'enforce_health_check': value['enforceHealthCheck'],
        'model_provider': value['modelProvider'],
        'model_sync_mode': ModelSyncModeToJSON(value['modelSyncMode']),
        'models': value['models'],
        'name': value['name'],
        'request_timeout_secs': value['requestTimeoutSecs'],
        'settings': value['settings'],
        'stream_idle_timeout_secs': value['streamIdleTimeoutSecs'],
    };
}

