/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { LongContextTierRequest } from './LongContextTierRequest.js';
import {
    LongContextTierRequestFromJSON,
    LongContextTierRequestFromJSONTyped,
    LongContextTierRequestToJSON,
    LongContextTierRequestToJSONTyped,
} from './LongContextTierRequest.js';
import type { PricingSyncMode } from './PricingSyncMode.js';
import {
    PricingSyncModeFromJSON,
    PricingSyncModeFromJSONTyped,
    PricingSyncModeToJSON,
    PricingSyncModeToJSONTyped,
} from './PricingSyncMode.js';

/**
 * 
 * @export
 * @interface CreatePricingRequest
 */
export interface CreatePricingRequest {
    /**
     * Per-million-tokens rate billed for prompt-cache reads. Omit to
     * inherit the Barndoor default (or leave NULL if the default has
     * none, in which case the cost calculator falls back to the full
     * input rate). Storing NULL preserves the "no override" semantics
     * so a future seeder update can repopulate the default rate without
     * the org row blocking it.
     */
    cacheReadCostPerMillionTokens?: number | null;
    /**
     * Per-million-tokens rate billed for the cache-creation premium
     * that Anthropic-family models charge on the request that populates
     * the prompt cache. Same NULL semantics as `cache_read_cost`.
     */
    cacheWriteCostPerMillionTokens?: number | null;
    /**
     * 
     */
    catalogSlug?: string | null;
    /**
     * Optional free-text note ("Q1 pricing review", "Negotiated discount")
     * surfaced on the History dialog timeline.
     */
    changeReason?: string | null;
    /**
     * When the price should take effect. Omit (or pass `null`) for
     * "right now". A timestamp in the future schedules the change and
     * records the row with `change_source = 'admin_schedule'` so the
     * History dialog can distinguish it from an immediate edit.
     */
    effectiveFrom?: Date | null;
    /**
     * 
     */
    inputCostPerMillionTokens: number;
    /**
     * Optional context-tiered surcharge (BCP-3904). Omit for the normal
     * case of one rate set at every prompt size.
     */
    longContext?: LongContextTierRequest | null;
    /**
     * 
     */
    modelPattern: string;
    /**
     * 
     */
    modelProvider?: string | null;
    /**
     * 
     */
    outputCostPerMillionTokens: number;
    /**
     * 
     */
    providerId?: string | null;
    /**
     * 
     */
    syncMode?: PricingSyncMode;
}



/**
 * Check if a given object implements the CreatePricingRequest interface.
 */
export function instanceOfCreatePricingRequest(value: object): value is CreatePricingRequest {
    if ((!('inputCostPerMillionTokens' in (value as Record<string, any>)) && !('input_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['inputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['input_cost_per_million_tokens'] === undefined)) return false;
    if ((!('modelPattern' in (value as Record<string, any>)) && !('model_pattern' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelPattern'] === undefined && (value as Record<string, any>)['model_pattern'] === undefined)) return false;
    if ((!('outputCostPerMillionTokens' in (value as Record<string, any>)) && !('output_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['outputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['output_cost_per_million_tokens'] === undefined)) return false;
    return true;
}

export function CreatePricingRequestFromJSON(json: any): CreatePricingRequest {
    return CreatePricingRequestFromJSONTyped(json, false);
}

export function CreatePricingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePricingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheReadCostPerMillionTokens': json['cache_read_cost_per_million_tokens'] === undefined ? undefined : json['cache_read_cost_per_million_tokens'] === null ? null : json['cache_read_cost_per_million_tokens'],
        'cacheWriteCostPerMillionTokens': json['cache_write_cost_per_million_tokens'] === undefined ? undefined : json['cache_write_cost_per_million_tokens'] === null ? null : json['cache_write_cost_per_million_tokens'],
        'catalogSlug': json['catalog_slug'] === undefined ? undefined : json['catalog_slug'] === null ? null : json['catalog_slug'],
        'changeReason': json['change_reason'] === undefined ? undefined : json['change_reason'] === null ? null : json['change_reason'],
        'effectiveFrom': json['effective_from'] === undefined ? undefined : json['effective_from'] === null ? null : (parseDateTime(json['effective_from'])),
        'inputCostPerMillionTokens': json['input_cost_per_million_tokens'],
        'longContext': json['long_context'] === undefined ? undefined : json['long_context'] === null ? null : LongContextTierRequestFromJSON(json['long_context']),
        'modelPattern': json['model_pattern'],
        'modelProvider': json['model_provider'] === undefined ? undefined : json['model_provider'] === null ? null : json['model_provider'],
        'outputCostPerMillionTokens': json['output_cost_per_million_tokens'],
        'providerId': json['provider_id'] === undefined ? undefined : json['provider_id'] === null ? null : json['provider_id'],
        'syncMode': json['sync_mode'] == null ? undefined : PricingSyncModeFromJSON(json['sync_mode']),
    };
}

export function CreatePricingRequestToJSON(json: any): CreatePricingRequest {
    return CreatePricingRequestToJSONTyped(json, false);
}

export function CreatePricingRequestToJSONTyped(value?: CreatePricingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read_cost_per_million_tokens': value['cacheReadCostPerMillionTokens'],
        'cache_write_cost_per_million_tokens': value['cacheWriteCostPerMillionTokens'],
        'catalog_slug': value['catalogSlug'],
        'change_reason': value['changeReason'],
        'effective_from': value['effectiveFrom'] == null ? value['effectiveFrom'] : serializeDateTime(value['effectiveFrom']),
        'input_cost_per_million_tokens': value['inputCostPerMillionTokens'],
        'long_context': LongContextTierRequestToJSON(value['longContext']),
        'model_pattern': value['modelPattern'],
        'model_provider': value['modelProvider'],
        'output_cost_per_million_tokens': value['outputCostPerMillionTokens'],
        'provider_id': value['providerId'],
        'sync_mode': PricingSyncModeToJSON(value['syncMode']),
    };
}

