/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CustomDetectionTypeResponse } from './CustomDetectionTypeResponse.js';
import {
    CustomDetectionTypeResponseFromJSON,
    CustomDetectionTypeResponseFromJSONTyped,
    CustomDetectionTypeResponseToJSON,
    CustomDetectionTypeResponseToJSONTyped,
} from './CustomDetectionTypeResponse.js';

/**
 * 
 * @export
 * @interface CustomDetectionTypesResponse
 */
export interface CustomDetectionTypesResponse {
    /**
     * 
     */
    items: Array<CustomDetectionTypeResponse>;
}

/**
 * Check if a given object implements the CustomDetectionTypesResponse interface.
 */
export function instanceOfCustomDetectionTypesResponse(value: object): value is CustomDetectionTypesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CustomDetectionTypesResponseFromJSON(json: any): CustomDetectionTypesResponse {
    return CustomDetectionTypesResponseFromJSONTyped(json, false);
}

export function CustomDetectionTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDetectionTypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CustomDetectionTypeResponseFromJSON)),
    };
}

export function CustomDetectionTypesResponseToJSON(json: any): CustomDetectionTypesResponse {
    return CustomDetectionTypesResponseToJSONTyped(json, false);
}

export function CustomDetectionTypesResponseToJSONTyped(value?: CustomDetectionTypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CustomDetectionTypeResponseToJSON)),
    };
}

