/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExportDestination } from './ExportDestination.js';
import {
    ExportDestinationFromJSON,
    ExportDestinationFromJSONTyped,
    ExportDestinationToJSON,
    ExportDestinationToJSONTyped,
} from './ExportDestination.js';
import type { ExportRuntimeStatus } from './ExportRuntimeStatus.js';
import {
    ExportRuntimeStatusFromJSON,
    ExportRuntimeStatusFromJSONTyped,
    ExportRuntimeStatusToJSON,
    ExportRuntimeStatusToJSONTyped,
} from './ExportRuntimeStatus.js';

/**
 * 
 * @export
 * @interface DestinationResponse
 */
export interface DestinationResponse {
    /**
     * 
     */
    destination: ExportDestination;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    exportType: string;
    /**
     * 
     */
    organizationId: string;
    /**
     * 
     */
    runtimeStatus: ExportRuntimeStatus;
}

/**
 * Check if a given object implements the DestinationResponse interface.
 */
export function instanceOfDestinationResponse(value: object): value is DestinationResponse {
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if ((!('exportType' in (value as Record<string, any>)) && !('export_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['exportType'] === undefined && (value as Record<string, any>)['export_type'] === undefined)) return false;
    if ((!('organizationId' in (value as Record<string, any>)) && !('organization_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['organizationId'] === undefined && (value as Record<string, any>)['organization_id'] === undefined)) return false;
    if ((!('runtimeStatus' in (value as Record<string, any>)) && !('runtime_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['runtimeStatus'] === undefined && (value as Record<string, any>)['runtime_status'] === undefined)) return false;
    return true;
}

export function DestinationResponseFromJSON(json: any): DestinationResponse {
    return DestinationResponseFromJSONTyped(json, false);
}

export function DestinationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'destination': ExportDestinationFromJSON(json['destination']),
        'enabled': json['enabled'],
        'exportType': json['export_type'],
        'organizationId': json['organization_id'],
        'runtimeStatus': ExportRuntimeStatusFromJSON(json['runtime_status']),
    };
}

export function DestinationResponseToJSON(json: any): DestinationResponse {
    return DestinationResponseToJSONTyped(json, false);
}

export function DestinationResponseToJSONTyped(value?: DestinationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination': ExportDestinationToJSON(value['destination']),
        'enabled': value['enabled'],
        'export_type': value['exportType'],
        'organization_id': value['organizationId'],
        'runtime_status': ExportRuntimeStatusToJSON(value['runtimeStatus']),
    };
}

