/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { DetectionEngineCapabilitiesResponse } from './DetectionEngineCapabilitiesResponse.js';
import {
    DetectionEngineCapabilitiesResponseFromJSON,
    DetectionEngineCapabilitiesResponseFromJSONTyped,
    DetectionEngineCapabilitiesResponseToJSON,
    DetectionEngineCapabilitiesResponseToJSONTyped,
} from './DetectionEngineCapabilitiesResponse.js';

/**
 * 
 * @export
 * @interface DetectionEngineResponse
 */
export interface DetectionEngineResponse {
    /**
     * 
     */
    capabilities: DetectionEngineCapabilitiesResponse;
    /**
     * 
     */
    config: any | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    createdBy?: string | null;
    /**
     * 
     */
    enabledDetectionTypes: Array<string>;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    providerClass: string;
    /**
     * 
     */
    providerConnectionName?: string | null;
    /**
     * 
     */
    providerType: string;
    /**
     * 
     */
    runtimeStages: Array<string>;
    /**
     * 
     */
    supportedActions: Array<string>;
    /**
     * Every `DETECTION_TYPE_*` this engine's provider can produce, code-derived
     * from the backend capability tables (coverage compiler). The frontend
     * reads this instead of re-encoding per-engine type Sets by hand.
     */
    supportedDetectionTypes: Array<string>;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    updatedBy?: string | null;
}

/**
 * Check if a given object implements the DetectionEngineResponse interface.
 */
export function instanceOfDetectionEngineResponse(value: object): value is DetectionEngineResponse {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('enabledDetectionTypes' in (value as Record<string, any>)) && !('enabled_detection_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['enabledDetectionTypes'] === undefined && (value as Record<string, any>)['enabled_detection_types'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('providerClass' in (value as Record<string, any>)) && !('provider_class' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerClass'] === undefined && (value as Record<string, any>)['provider_class'] === undefined)) return false;
    if ((!('providerType' in (value as Record<string, any>)) && !('provider_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerType'] === undefined && (value as Record<string, any>)['provider_type'] === undefined)) return false;
    if ((!('runtimeStages' in (value as Record<string, any>)) && !('runtime_stages' in (value as Record<string, any>))) || ((value as Record<string, any>)['runtimeStages'] === undefined && (value as Record<string, any>)['runtime_stages'] === undefined)) return false;
    if ((!('supportedActions' in (value as Record<string, any>)) && !('supported_actions' in (value as Record<string, any>))) || ((value as Record<string, any>)['supportedActions'] === undefined && (value as Record<string, any>)['supported_actions'] === undefined)) return false;
    if ((!('supportedDetectionTypes' in (value as Record<string, any>)) && !('supported_detection_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['supportedDetectionTypes'] === undefined && (value as Record<string, any>)['supported_detection_types'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function DetectionEngineResponseFromJSON(json: any): DetectionEngineResponse {
    return DetectionEngineResponseFromJSONTyped(json, false);
}

export function DetectionEngineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectionEngineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilities': DetectionEngineCapabilitiesResponseFromJSON(json['capabilities']),
        'config': json['config'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'createdBy': json['created_by'] === undefined ? undefined : json['created_by'] === null ? null : json['created_by'],
        'enabledDetectionTypes': json['enabled_detection_types'],
        'id': json['id'],
        'name': json['name'],
        'orgId': json['org_id'],
        'providerClass': json['provider_class'],
        'providerConnectionName': json['provider_connection_name'] === undefined ? undefined : json['provider_connection_name'] === null ? null : json['provider_connection_name'],
        'providerType': json['provider_type'],
        'runtimeStages': json['runtime_stages'],
        'supportedActions': json['supported_actions'],
        'supportedDetectionTypes': json['supported_detection_types'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'updatedBy': json['updated_by'] === undefined ? undefined : json['updated_by'] === null ? null : json['updated_by'],
    };
}

export function DetectionEngineResponseToJSON(json: any): DetectionEngineResponse {
    return DetectionEngineResponseToJSONTyped(json, false);
}

export function DetectionEngineResponseToJSONTyped(value?: DetectionEngineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capabilities': DetectionEngineCapabilitiesResponseToJSON(value['capabilities']),
        'config': value['config'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'created_by': value['createdBy'],
        'enabled_detection_types': value['enabledDetectionTypes'],
        'id': value['id'],
        'name': value['name'],
        'org_id': value['orgId'],
        'provider_class': value['providerClass'],
        'provider_connection_name': value['providerConnectionName'],
        'provider_type': value['providerType'],
        'runtime_stages': value['runtimeStages'],
        'supported_actions': value['supportedActions'],
        'supported_detection_types': value['supportedDetectionTypes'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'updated_by': value['updatedBy'],
    };
}

