/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EnforcementPolicyPrincipalResponse
 */
export interface EnforcementPolicyPrincipalResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    principalId: string;
    /**
     * 
     */
    principalType: string;
}

/**
 * Check if a given object implements the EnforcementPolicyPrincipalResponse interface.
 */
export function instanceOfEnforcementPolicyPrincipalResponse(value: object): value is EnforcementPolicyPrincipalResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('principalId' in (value as Record<string, any>)) && !('principal_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['principalId'] === undefined && (value as Record<string, any>)['principal_id'] === undefined)) return false;
    if ((!('principalType' in (value as Record<string, any>)) && !('principal_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['principalType'] === undefined && (value as Record<string, any>)['principal_type'] === undefined)) return false;
    return true;
}

export function EnforcementPolicyPrincipalResponseFromJSON(json: any): EnforcementPolicyPrincipalResponse {
    return EnforcementPolicyPrincipalResponseFromJSONTyped(json, false);
}

export function EnforcementPolicyPrincipalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnforcementPolicyPrincipalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'principalId': json['principal_id'],
        'principalType': json['principal_type'],
    };
}

export function EnforcementPolicyPrincipalResponseToJSON(json: any): EnforcementPolicyPrincipalResponse {
    return EnforcementPolicyPrincipalResponseToJSONTyped(json, false);
}

export function EnforcementPolicyPrincipalResponseToJSONTyped(value?: EnforcementPolicyPrincipalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'principal_id': value['principalId'],
        'principal_type': value['principalType'],
    };
}

