/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExportDestination
 */
export interface ExportDestination {
    /**
     * 
     */
    authMethod?: string;
    /**
     * 
     */
    bucket?: string;
    /**
     * 
     */
    credentialsRotatedAt?: string;
    /**
     * 
     */
    endpoint?: string;
    /**
     * 
     */
    externalId?: string;
    /**
     * 
     */
    hasCredentials?: boolean;
    /**
     * 
     */
    iamRoleArn?: string;
    /**
     * 
     */
    pathPrefix?: string;
    /**
     * 
     */
    provider?: string;
    /**
     * 
     */
    region?: string;
    /**
     * 
     */
    usePathStyle?: boolean;
    /**
     * 
     */
    useSsl?: boolean;
}

/**
 * Check if a given object implements the ExportDestination interface.
 */
export function instanceOfExportDestination(value: object): value is ExportDestination {
    return true;
}

export function ExportDestinationFromJSON(json: any): ExportDestination {
    return ExportDestinationFromJSONTyped(json, false);
}

export function ExportDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'authMethod': json['auth_method'] == null ? undefined : json['auth_method'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'credentialsRotatedAt': json['credentials_rotated_at'] == null ? undefined : json['credentials_rotated_at'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'hasCredentials': json['has_credentials'] == null ? undefined : json['has_credentials'],
        'iamRoleArn': json['iam_role_arn'] == null ? undefined : json['iam_role_arn'],
        'pathPrefix': json['path_prefix'] == null ? undefined : json['path_prefix'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'region': json['region'] == null ? undefined : json['region'],
        'usePathStyle': json['use_path_style'] == null ? undefined : json['use_path_style'],
        'useSsl': json['use_ssl'] == null ? undefined : json['use_ssl'],
    };
}

export function ExportDestinationToJSON(json: any): ExportDestination {
    return ExportDestinationToJSONTyped(json, false);
}

export function ExportDestinationToJSONTyped(value?: ExportDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_method': value['authMethod'],
        'bucket': value['bucket'],
        'credentials_rotated_at': value['credentialsRotatedAt'],
        'endpoint': value['endpoint'],
        'external_id': value['externalId'],
        'has_credentials': value['hasCredentials'],
        'iam_role_arn': value['iamRoleArn'],
        'path_prefix': value['pathPrefix'],
        'provider': value['provider'],
        'region': value['region'],
        'use_path_style': value['usePathStyle'],
        'use_ssl': value['useSsl'],
    };
}

