/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExportResponse } from './ExportResponse.js';
import {
    ExportResponseFromJSON,
    ExportResponseFromJSONTyped,
    ExportResponseToJSON,
    ExportResponseToJSONTyped,
} from './ExportResponse.js';

/**
 * 
 * @export
 * @interface ExportsResponse
 */
export interface ExportsResponse {
    /**
     * 
     */
    exports: Array<ExportResponse> | null;
}

/**
 * Check if a given object implements the ExportsResponse interface.
 */
export function instanceOfExportsResponse(value: object): value is ExportsResponse {
    if (!('exports' in value) || value['exports'] === undefined) return false;
    return true;
}

export function ExportsResponseFromJSON(json: any): ExportsResponse {
    return ExportsResponseFromJSONTyped(json, false);
}

export function ExportsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'exports': (json['exports'] == null ? null : (json['exports'] as Array<any>).map(ExportResponseFromJSON)),
    };
}

export function ExportsResponseToJSON(json: any): ExportsResponse {
    return ExportsResponseToJSONTyped(json, false);
}

export function ExportsResponseToJSONTyped(value?: ExportsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exports': (value['exports'] == null ? null : (value['exports'] as Array<any>).map(ExportResponseToJSON)),
    };
}

