/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExportSettings
 */
export interface ExportSettings {
    /**
     * 
     */
    batchSize: number;
    /**
     * 
     */
    bufferSize: number;
    /**
     * 
     */
    flushIntervalSeconds: number;
    /**
     * 
     */
    includedEventTypes?: Array<string> | null;
    /**
     * 
     */
    maxRetries: number;
    /**
     * 
     */
    retryBackoffSeconds: number;
}

/**
 * Check if a given object implements the ExportSettings interface.
 */
export function instanceOfExportSettings(value: object): value is ExportSettings {
    if ((!('batchSize' in (value as Record<string, any>)) && !('batch_size' in (value as Record<string, any>))) || ((value as Record<string, any>)['batchSize'] === undefined && (value as Record<string, any>)['batch_size'] === undefined)) return false;
    if ((!('bufferSize' in (value as Record<string, any>)) && !('buffer_size' in (value as Record<string, any>))) || ((value as Record<string, any>)['bufferSize'] === undefined && (value as Record<string, any>)['buffer_size'] === undefined)) return false;
    if ((!('flushIntervalSeconds' in (value as Record<string, any>)) && !('flush_interval_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['flushIntervalSeconds'] === undefined && (value as Record<string, any>)['flush_interval_seconds'] === undefined)) return false;
    if ((!('maxRetries' in (value as Record<string, any>)) && !('max_retries' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxRetries'] === undefined && (value as Record<string, any>)['max_retries'] === undefined)) return false;
    if ((!('retryBackoffSeconds' in (value as Record<string, any>)) && !('retry_backoff_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryBackoffSeconds'] === undefined && (value as Record<string, any>)['retry_backoff_seconds'] === undefined)) return false;
    return true;
}

export function ExportSettingsFromJSON(json: any): ExportSettings {
    return ExportSettingsFromJSONTyped(json, false);
}

export function ExportSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'batchSize': json['batch_size'],
        'bufferSize': json['buffer_size'],
        'flushIntervalSeconds': json['flush_interval_seconds'],
        'includedEventTypes': json['included_event_types'] === undefined ? undefined : json['included_event_types'] === null ? null : json['included_event_types'],
        'maxRetries': json['max_retries'],
        'retryBackoffSeconds': json['retry_backoff_seconds'],
    };
}

export function ExportSettingsToJSON(json: any): ExportSettings {
    return ExportSettingsToJSONTyped(json, false);
}

export function ExportSettingsToJSONTyped(value?: ExportSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batch_size': value['batchSize'],
        'buffer_size': value['bufferSize'],
        'flush_interval_seconds': value['flushIntervalSeconds'],
        'included_event_types': value['includedEventTypes'],
        'max_retries': value['maxRetries'],
        'retry_backoff_seconds': value['retryBackoffSeconds'],
    };
}

