/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FilterOption } from './FilterOption.js';
import {
    FilterOptionFromJSON,
    FilterOptionFromJSONTyped,
    FilterOptionToJSON,
    FilterOptionToJSONTyped,
} from './FilterOption.js';

/**
 * Category of filter options for the advanced filter UI.
 * @export
 * @interface FilterCategory
 */
export interface FilterCategory {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    label: string;
    /**
     * 
     */
    options?: Array<FilterOption>;
}

/**
 * Check if a given object implements the FilterCategory interface.
 */
export function instanceOfFilterCategory(value: object): value is FilterCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function FilterCategoryFromJSON(json: any): FilterCategory {
    return FilterCategoryFromJSONTyped(json, false);
}

export function FilterCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(FilterOptionFromJSON)),
    };
}

export function FilterCategoryToJSON(json: any): FilterCategory {
    return FilterCategoryToJSONTyped(json, false);
}

export function FilterCategoryToJSONTyped(value?: FilterCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(FilterOptionToJSON)),
    };
}

