/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GoogleDlpConnectionResponse
 */
export interface GoogleDlpConnectionResponse {
    /**
     * 
     */
    endpoint: string;
    /**
     * Whether a bearer token is configured. The token value is never returned.
     */
    hasBearerToken: boolean;
    /**
     * 
     */
    location: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    projectId: string;
}

/**
 * Check if a given object implements the GoogleDlpConnectionResponse interface.
 */
export function instanceOfGoogleDlpConnectionResponse(value: object): value is GoogleDlpConnectionResponse {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if ((!('hasBearerToken' in (value as Record<string, any>)) && !('has_bearer_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasBearerToken'] === undefined && (value as Record<string, any>)['has_bearer_token'] === undefined)) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    return true;
}

export function GoogleDlpConnectionResponseFromJSON(json: any): GoogleDlpConnectionResponse {
    return GoogleDlpConnectionResponseFromJSONTyped(json, false);
}

export function GoogleDlpConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleDlpConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
        'hasBearerToken': json['has_bearer_token'],
        'location': json['location'],
        'orgId': json['org_id'],
        'projectId': json['project_id'],
    };
}

export function GoogleDlpConnectionResponseToJSON(json: any): GoogleDlpConnectionResponse {
    return GoogleDlpConnectionResponseToJSONTyped(json, false);
}

export function GoogleDlpConnectionResponseToJSONTyped(value?: GoogleDlpConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'has_bearer_token': value['hasBearerToken'],
        'location': value['location'],
        'org_id': value['orgId'],
        'project_id': value['projectId'],
    };
}

