/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DefaultModelAccess } from './DefaultModelAccess.js';
import {
    DefaultModelAccessFromJSON,
    DefaultModelAccessFromJSONTyped,
    DefaultModelAccessToJSON,
    DefaultModelAccessToJSONTyped,
} from './DefaultModelAccess.js';

/**
 * 
 * @export
 * @interface GovernanceConfig
 */
export interface GovernanceConfig {
    /**
     * 
     */
    defaultModelAccess?: DefaultModelAccess;
    /**
     * 
     */
    requirePricingForMappings: boolean;
    /**
     * Whether callers must address a routing policy rather than naming a
     * model directly (BCP-4037).
     * 
     * `false` — the historical behaviour — is the `Default`, and must agree
     * with the column default in `V78__require_routing_policy.sql` for the
     * same reason [`DefaultModelAccess`] must agree with V70's:
     * `governance_config` holds a row only for orgs that have changed some
     * governance setting, so whether an org gets this default or the column's
     * depends on whether a row happens to exist.
     * `default_matches_column_default` pins both.
     * 
     * `#[serde(default)]` so config bodies written before this field existed
     * — every current Terraform config and API client — keep deserialising,
     * and keep meaning "off".
     */
    requireRoutingPolicy?: boolean;
}



/**
 * Check if a given object implements the GovernanceConfig interface.
 */
export function instanceOfGovernanceConfig(value: object): value is GovernanceConfig {
    if ((!('requirePricingForMappings' in (value as Record<string, any>)) && !('require_pricing_for_mappings' in (value as Record<string, any>))) || ((value as Record<string, any>)['requirePricingForMappings'] === undefined && (value as Record<string, any>)['require_pricing_for_mappings'] === undefined)) return false;
    return true;
}

export function GovernanceConfigFromJSON(json: any): GovernanceConfig {
    return GovernanceConfigFromJSONTyped(json, false);
}

export function GovernanceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernanceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModelAccess': json['default_model_access'] == null ? undefined : DefaultModelAccessFromJSON(json['default_model_access']),
        'requirePricingForMappings': json['require_pricing_for_mappings'],
        'requireRoutingPolicy': json['require_routing_policy'] == null ? undefined : json['require_routing_policy'],
    };
}

export function GovernanceConfigToJSON(json: any): GovernanceConfig {
    return GovernanceConfigToJSONTyped(json, false);
}

export function GovernanceConfigToJSONTyped(value?: GovernanceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model_access': DefaultModelAccessToJSON(value['defaultModelAccess']),
        'require_pricing_for_mappings': value['requirePricingForMappings'],
        'require_routing_policy': value['requireRoutingPolicy'],
    };
}

