/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Response containing current IdP connection configuration.
 * @export
 * @interface IdpConnectionResponse
 */
export interface IdpConnectionResponse {
    /**
     * 
     */
    configured?: boolean;
    /**
     * 
     */
    alias?: string | null;
    /**
     * 
     */
    expectedAlias?: string | null;
    /**
     * 
     */
    displayName?: string | null;
    /**
     * 
     */
    issuer?: string | null;
    /**
     * 
     */
    authorizationUrl?: string | null;
    /**
     * 
     */
    tokenUrl?: string | null;
    /**
     * 
     */
    userinfoUrl?: string | null;
    /**
     * 
     */
    jwksUrl?: string | null;
    /**
     * 
     */
    logoutUrl?: string | null;
    /**
     * 
     */
    scopes?: string | null;
    /**
     * 
     */
    prompt?: string;
    /**
     * 
     */
    clientIdConfigured?: boolean;
    /**
     * 
     */
    clientSecretConfigured?: boolean;
    /**
     * 
     */
    domain?: string | null;
}

/**
 * Check if a given object implements the IdpConnectionResponse interface.
 */
export function instanceOfIdpConnectionResponse(value: object): value is IdpConnectionResponse {
    return true;
}

export function IdpConnectionResponseFromJSON(json: any): IdpConnectionResponse {
    return IdpConnectionResponseFromJSONTyped(json, false);
}

export function IdpConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdpConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'alias': json['alias'] === undefined ? undefined : json['alias'] === null ? null : json['alias'],
        'expectedAlias': json['expected_alias'] === undefined ? undefined : json['expected_alias'] === null ? null : json['expected_alias'],
        'displayName': json['display_name'] === undefined ? undefined : json['display_name'] === null ? null : json['display_name'],
        'issuer': json['issuer'] === undefined ? undefined : json['issuer'] === null ? null : json['issuer'],
        'authorizationUrl': json['authorization_url'] === undefined ? undefined : json['authorization_url'] === null ? null : json['authorization_url'],
        'tokenUrl': json['token_url'] === undefined ? undefined : json['token_url'] === null ? null : json['token_url'],
        'userinfoUrl': json['userinfo_url'] === undefined ? undefined : json['userinfo_url'] === null ? null : json['userinfo_url'],
        'jwksUrl': json['jwks_url'] === undefined ? undefined : json['jwks_url'] === null ? null : json['jwks_url'],
        'logoutUrl': json['logout_url'] === undefined ? undefined : json['logout_url'] === null ? null : json['logout_url'],
        'scopes': json['scopes'] === undefined ? undefined : json['scopes'] === null ? null : json['scopes'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'clientIdConfigured': json['client_id_configured'] == null ? undefined : json['client_id_configured'],
        'clientSecretConfigured': json['client_secret_configured'] == null ? undefined : json['client_secret_configured'],
        'domain': json['domain'] === undefined ? undefined : json['domain'] === null ? null : json['domain'],
    };
}

export function IdpConnectionResponseToJSON(json: any): IdpConnectionResponse {
    return IdpConnectionResponseToJSONTyped(json, false);
}

export function IdpConnectionResponseToJSONTyped(value?: IdpConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'alias': value['alias'],
        'expected_alias': value['expectedAlias'],
        'display_name': value['displayName'],
        'issuer': value['issuer'],
        'authorization_url': value['authorizationUrl'],
        'token_url': value['tokenUrl'],
        'userinfo_url': value['userinfoUrl'],
        'jwks_url': value['jwksUrl'],
        'logout_url': value['logoutUrl'],
        'scopes': value['scopes'],
        'prompt': value['prompt'],
        'client_id_configured': value['clientIdConfigured'],
        'client_secret_configured': value['clientSecretConfigured'],
        'domain': value['domain'],
    };
}

