/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Configuration for IdP group to Barndoor role mapping.
 * @export
 * @interface IdpRoleMappingConfig
 */
export interface IdpRoleMappingConfig {
    /**
     * 
     */
    adminGroup?: string | null;
}

/**
 * Check if a given object implements the IdpRoleMappingConfig interface.
 */
export function instanceOfIdpRoleMappingConfig(value: object): value is IdpRoleMappingConfig {
    return true;
}

export function IdpRoleMappingConfigFromJSON(json: any): IdpRoleMappingConfig {
    return IdpRoleMappingConfigFromJSONTyped(json, false);
}

export function IdpRoleMappingConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdpRoleMappingConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'adminGroup': json['admin_group'] === undefined ? undefined : json['admin_group'] === null ? null : json['admin_group'],
    };
}

export function IdpRoleMappingConfigToJSON(json: any): IdpRoleMappingConfig {
    return IdpRoleMappingConfigToJSONTyped(json, false);
}

export function IdpRoleMappingConfigToJSONTyped(value?: IdpRoleMappingConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admin_group': value['adminGroup'],
    };
}

