/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Response containing current IdP settings for an organization.
 * @export
 * @interface IdpSettingsResponse
 */
export interface IdpSettingsResponse {
    /**
     * 
     */
    enforceSso?: boolean;
    /**
     * 
     */
    breakGlassEmail?: string | null;
    /**
     * 
     */
    breakGlassUserId?: string | null;
}

/**
 * Check if a given object implements the IdpSettingsResponse interface.
 */
export function instanceOfIdpSettingsResponse(value: object): value is IdpSettingsResponse {
    return true;
}

export function IdpSettingsResponseFromJSON(json: any): IdpSettingsResponse {
    return IdpSettingsResponseFromJSONTyped(json, false);
}

export function IdpSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdpSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enforceSso': json['enforce_sso'] == null ? undefined : json['enforce_sso'],
        'breakGlassEmail': json['break_glass_email'] === undefined ? undefined : json['break_glass_email'] === null ? null : json['break_glass_email'],
        'breakGlassUserId': json['break_glass_user_id'] === undefined ? undefined : json['break_glass_user_id'] === null ? null : json['break_glass_user_id'],
    };
}

export function IdpSettingsResponseToJSON(json: any): IdpSettingsResponse {
    return IdpSettingsResponseToJSONTyped(json, false);
}

export function IdpSettingsResponseToJSONTyped(value?: IdpSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enforce_sso': value['enforceSso'],
        'break_glass_email': value['breakGlassEmail'],
        'break_glass_user_id': value['breakGlassUserId'],
    };
}

