/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * An enum value paired with its display label.
 * @export
 * @interface LabeledOption
 */
export interface LabeledOption {
    /**
     * The value to send in a request.
     */
    value: string;
    /**
     * Human-readable label for display.
     */
    label: string;
}

/**
 * Check if a given object implements the LabeledOption interface.
 */
export function instanceOfLabeledOption(value: object): value is LabeledOption {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function LabeledOptionFromJSON(json: any): LabeledOption {
    return LabeledOptionFromJSONTyped(json, false);
}

export function LabeledOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabeledOption {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'label': json['label'],
    };
}

export function LabeledOptionToJSON(json: any): LabeledOption {
    return LabeledOptionToJSONTyped(json, false);
}

export function LabeledOptionToJSONTyped(value?: LabeledOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'label': value['label'],
    };
}

