/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentRuntimeProfile } from './AgentRuntimeProfile.js';
import {
    AgentRuntimeProfileFromJSON,
    AgentRuntimeProfileFromJSONTyped,
    AgentRuntimeProfileToJSON,
    AgentRuntimeProfileToJSONTyped,
} from './AgentRuntimeProfile.js';

/**
 * 
 * @export
 * @interface ListProfilesResponse
 */
export interface ListProfilesResponse {
    /**
     * 
     */
    profiles: Array<AgentRuntimeProfile>;
}

/**
 * Check if a given object implements the ListProfilesResponse interface.
 */
export function instanceOfListProfilesResponse(value: object): value is ListProfilesResponse {
    if (!('profiles' in value) || value['profiles'] === undefined) return false;
    return true;
}

export function ListProfilesResponseFromJSON(json: any): ListProfilesResponse {
    return ListProfilesResponseFromJSONTyped(json, false);
}

export function ListProfilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProfilesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'profiles': ((json['profiles'] as Array<any>).map(AgentRuntimeProfileFromJSON)),
    };
}

export function ListProfilesResponseToJSON(json: any): ListProfilesResponse {
    return ListProfilesResponseToJSONTyped(json, false);
}

export function ListProfilesResponseToJSONTyped(value?: ListProfilesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profiles': ((value['profiles'] as Array<any>).map(AgentRuntimeProfileToJSON)),
    };
}

