/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * The long-context surcharge on a create/update request.
 * 
 * One nested object rather than five sibling fields so a partial tier is
 * awkward to express in the first place, and so the wire shape matches both
 * the provider YAML's `long_context:` block and the `long_context` object the
 * defaults listing returns.
 * @export
 * @interface LongContextTierRequest
 */
export interface LongContextTierRequest {
    /**
     * Omit to bill long-context cache reads at this tier's input rate.
     */
    cacheReadCostPerMillionTokens?: number | null;
    /**
     * 
     */
    cacheWriteCostPerMillionTokens?: number | null;
    /**
     * 
     */
    inputCostPerMillionTokens: number;
    /**
     * 
     */
    outputCostPerMillionTokens: number;
    /**
     * Total prompt tokens (non-cached input + cache-read + cache-creation)
     * at or above which the tier's rates replace the base rates for the
     * whole request.
     */
    thresholdPromptTokens: number;
}

/**
 * Check if a given object implements the LongContextTierRequest interface.
 */
export function instanceOfLongContextTierRequest(value: object): value is LongContextTierRequest {
    if ((!('inputCostPerMillionTokens' in (value as Record<string, any>)) && !('input_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['inputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['input_cost_per_million_tokens'] === undefined)) return false;
    if ((!('outputCostPerMillionTokens' in (value as Record<string, any>)) && !('output_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['outputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['output_cost_per_million_tokens'] === undefined)) return false;
    if ((!('thresholdPromptTokens' in (value as Record<string, any>)) && !('threshold_prompt_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['thresholdPromptTokens'] === undefined && (value as Record<string, any>)['threshold_prompt_tokens'] === undefined)) return false;
    return true;
}

export function LongContextTierRequestFromJSON(json: any): LongContextTierRequest {
    return LongContextTierRequestFromJSONTyped(json, false);
}

export function LongContextTierRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LongContextTierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheReadCostPerMillionTokens': json['cache_read_cost_per_million_tokens'] === undefined ? undefined : json['cache_read_cost_per_million_tokens'] === null ? null : json['cache_read_cost_per_million_tokens'],
        'cacheWriteCostPerMillionTokens': json['cache_write_cost_per_million_tokens'] === undefined ? undefined : json['cache_write_cost_per_million_tokens'] === null ? null : json['cache_write_cost_per_million_tokens'],
        'inputCostPerMillionTokens': json['input_cost_per_million_tokens'],
        'outputCostPerMillionTokens': json['output_cost_per_million_tokens'],
        'thresholdPromptTokens': json['threshold_prompt_tokens'],
    };
}

export function LongContextTierRequestToJSON(json: any): LongContextTierRequest {
    return LongContextTierRequestToJSONTyped(json, false);
}

export function LongContextTierRequestToJSONTyped(value?: LongContextTierRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read_cost_per_million_tokens': value['cacheReadCostPerMillionTokens'],
        'cache_write_cost_per_million_tokens': value['cacheWriteCostPerMillionTokens'],
        'input_cost_per_million_tokens': value['inputCostPerMillionTokens'],
        'output_cost_per_million_tokens': value['outputCostPerMillionTokens'],
        'threshold_prompt_tokens': value['thresholdPromptTokens'],
    };
}

