/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface MCPServerCategory
 */
export interface MCPServerCategory {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    description: string | null;
}

/**
 * Check if a given object implements the MCPServerCategory interface.
 */
export function instanceOfMCPServerCategory(value: object): value is MCPServerCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MCPServerCategoryFromJSON(json: any): MCPServerCategory {
    return MCPServerCategoryFromJSONTyped(json, false);
}

export function MCPServerCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MCPServerCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
    };
}

export function MCPServerCategoryToJSON(json: any): MCPServerCategory {
    return MCPServerCategoryToJSONTyped(json, false);
}

export function MCPServerCategoryToJSONTyped(value?: MCPServerCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
    };
}

