/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Match by user-facing model alias (with optional trailing `*`
 * wildcard) — i.e. whatever the caller put in the `model` field.
 * 
 * Use this for aliases that may map to multiple providers (e.g. a
 * `goto` alias fanned out across OpenAI and Anthropic): the policy
 * fires whenever a request uses that alias, regardless of routing.
 * @export
 * @interface ModelAccessTargetOneOf
 */
export interface ModelAccessTargetOneOf {
    /**
     * 
     */
    alias: string;
    /**
     * 
     */
    kind: ModelAccessTargetOneOfKindEnum;
}


/**
 * @export
 */
export const ModelAccessTargetOneOfKindEnum = {
    ModelAlias: 'model_alias',
} as const;
export type ModelAccessTargetOneOfKindEnum = typeof ModelAccessTargetOneOfKindEnum[keyof typeof ModelAccessTargetOneOfKindEnum];


/**
 * Check if a given object implements the ModelAccessTargetOneOf interface.
 */
export function instanceOfModelAccessTargetOneOf(value: object): value is ModelAccessTargetOneOf {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (value['kind'] !== 'model_alias') return false;
    
    return true;
}

export function ModelAccessTargetOneOfFromJSON(json: any): ModelAccessTargetOneOf {
    return ModelAccessTargetOneOfFromJSONTyped(json, false);
}

export function ModelAccessTargetOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccessTargetOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'kind': json['kind'],
    };
}

export function ModelAccessTargetOneOfToJSON(json: any): ModelAccessTargetOneOf {
    return ModelAccessTargetOneOfToJSONTyped(json, false);
}

export function ModelAccessTargetOneOfToJSONTyped(value?: ModelAccessTargetOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'kind': value['kind'],
    };
}

