/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ModelAccessTargetOneOf } from './ModelAccessTargetOneOf.js';
import {
    instanceOfModelAccessTargetOneOf,
    ModelAccessTargetOneOfFromJSON,
    ModelAccessTargetOneOfFromJSONTyped,
    ModelAccessTargetOneOfToJSON,
} from './ModelAccessTargetOneOf.js';
import type { ModelAccessTargetOneOf1 } from './ModelAccessTargetOneOf1.js';
import {
    instanceOfModelAccessTargetOneOf1,
    ModelAccessTargetOneOf1FromJSON,
    ModelAccessTargetOneOf1FromJSONTyped,
    ModelAccessTargetOneOf1ToJSON,
} from './ModelAccessTargetOneOf1.js';
import type { ModelAccessTargetOneOf2 } from './ModelAccessTargetOneOf2.js';
import {
    instanceOfModelAccessTargetOneOf2,
    ModelAccessTargetOneOf2FromJSON,
    ModelAccessTargetOneOf2FromJSONTyped,
    ModelAccessTargetOneOf2ToJSON,
} from './ModelAccessTargetOneOf2.js';
import type { ModelAccessTargetOneOf3 } from './ModelAccessTargetOneOf3.js';
import {
    instanceOfModelAccessTargetOneOf3,
    ModelAccessTargetOneOf3FromJSON,
    ModelAccessTargetOneOf3FromJSONTyped,
    ModelAccessTargetOneOf3ToJSON,
} from './ModelAccessTargetOneOf3.js';
import type { ModelAccessTargetOneOf4 } from './ModelAccessTargetOneOf4.js';
import {
    instanceOfModelAccessTargetOneOf4,
    ModelAccessTargetOneOf4FromJSON,
    ModelAccessTargetOneOf4FromJSONTyped,
    ModelAccessTargetOneOf4ToJSON,
} from './ModelAccessTargetOneOf4.js';

/**
 * @type ModelAccessTarget
 * A single restriction target inside a [`ModelAccessPolicy`].
 * 
 * Targets answer the question "*what* is being allowed/denied?" — distinct
 * from `scope_type`, which answers "*who* is the policy applied to?". A
 * policy's `targets` list is OR-ed when matching: a request matches the
 * policy if any one of its targets matches the (provider, model) pair.
 * 
 * Serialised to JSONB with a `kind` discriminator so it round-trips cleanly
 * through the admin REST API.
 * 
 * `ModelAlias` matches against the literal `model` field in the request.
 * `Model` matches against the *resolved upstream model* — i.e. the underlying
 * model the routed mapping points at. The two are distinct because the
 * admin UI lets admins pick along either dimension: a `goto` alias fanned
 * out across providers is best expressed with `ModelAlias`, while "block any
 * request that ends up at gpt-4o-mini regardless of the alias used" is best
 * expressed with `Model` (so it fires even when `goto` resolves to
 * `gpt-4o-mini`).
 * @export
 */
export type ModelAccessTarget = ModelAccessTargetOneOf | ModelAccessTargetOneOf1 | ModelAccessTargetOneOf2 | ModelAccessTargetOneOf3 | ModelAccessTargetOneOf4;

export function ModelAccessTargetFromJSON(json: any): ModelAccessTarget {
    return ModelAccessTargetFromJSONTyped(json, false);
}

export function ModelAccessTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccessTarget {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfModelAccessTargetOneOf(json)) {
        return ModelAccessTargetOneOfFromJSONTyped(json, true);
    }
    if (instanceOfModelAccessTargetOneOf1(json)) {
        return ModelAccessTargetOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfModelAccessTargetOneOf2(json)) {
        return ModelAccessTargetOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfModelAccessTargetOneOf3(json)) {
        return ModelAccessTargetOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfModelAccessTargetOneOf4(json)) {
        return ModelAccessTargetOneOf4FromJSONTyped(json, true);
    }
    return {} as any;
}

export function ModelAccessTargetToJSON(json: any): any {
    return ModelAccessTargetToJSONTyped(json, false);
}

export function ModelAccessTargetToJSONTyped(value?: ModelAccessTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfModelAccessTargetOneOf(value)) {
        return ModelAccessTargetOneOfToJSON(value as ModelAccessTargetOneOf);
    }
    if (instanceOfModelAccessTargetOneOf1(value)) {
        return ModelAccessTargetOneOf1ToJSON(value as ModelAccessTargetOneOf1);
    }
    if (instanceOfModelAccessTargetOneOf2(value)) {
        return ModelAccessTargetOneOf2ToJSON(value as ModelAccessTargetOneOf2);
    }
    if (instanceOfModelAccessTargetOneOf3(value)) {
        return ModelAccessTargetOneOf3ToJSON(value as ModelAccessTargetOneOf3);
    }
    if (instanceOfModelAccessTargetOneOf4(value)) {
        return ModelAccessTargetOneOf4ToJSON(value as ModelAccessTargetOneOf4);
    }
    return {};
}

