/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { LongContextTier } from './LongContextTier.js';
import {
    LongContextTierFromJSON,
    LongContextTierFromJSONTyped,
    LongContextTierToJSON,
    LongContextTierToJSONTyped,
} from './LongContextTier.js';

/**
 * 
 * @export
 * @interface ModelPricing
 */
export interface ModelPricing {
    /**
     * Per-million-token cost for input tokens served from the prompt
     * cache. `None` ⇒ the calculator bills cached input at
     * `input_cost_per_million_tokens`.
     */
    cacheReadCostPerMillionTokens?: number | null;
    /**
     * Per-million-token cost for input tokens added to the prompt cache.
     * `None` ⇒ same fallback as `cache_read_cost_per_million_tokens`.
     */
    cacheWriteCostPerMillionTokens?: number | null;
    /**
     * Catalog slug for provider-level pricing (e.g. "openai", "aws_bedrock").
     */
    catalogSlug?: string | null;
    /**
     * 
     */
    effectiveFrom: Date;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    inputCostPerMillionTokens: number;
    /**
     * Optional context-tiered surcharge (BCP-3904). `None` ⇒ one rate set
     * at every prompt size, i.e. exactly the pre-BCP-3904 behaviour.
     * 
     * Serialized as `long_context`, not as the Rust field name. This struct
     * reaches the admin API through `AdminModelPricing`'s
     * `#[serde(flatten)]`, so the field name here *is* the wire key — and
     * every sibling surface (`DefaultPricingEntry`, `EffectivePricing`, the
     * create/update request bodies) already spells it `long_context`. Left
     * unrenamed, the pricing tab would write a tier successfully and then
     * read back nothing, which is precisely how it behaved before this
     * attribute existed: the surcharge saved, the dialog reopened unchecked,
     * and the edit looked silently discarded. Pinned by
     * `admin_model_pricing_serializes_the_tier_as_long_context`.
     */
    longContext?: LongContextTier | null;
    /**
     * 
     */
    modelPattern: string;
    /**
     * 
     */
    modelProvider?: string | null;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    outputCostPerMillionTokens: number;
    /**
     * Optional reference to a specific LLM Gateway provider instance.
     */
    providerId?: string | null;
    /**
     * 
     */
    providerName?: string | null;
}

/**
 * Check if a given object implements the ModelPricing interface.
 */
export function instanceOfModelPricing(value: object): value is ModelPricing {
    if ((!('effectiveFrom' in (value as Record<string, any>)) && !('effective_from' in (value as Record<string, any>))) || ((value as Record<string, any>)['effectiveFrom'] === undefined && (value as Record<string, any>)['effective_from'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('inputCostPerMillionTokens' in (value as Record<string, any>)) && !('input_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['inputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['input_cost_per_million_tokens'] === undefined)) return false;
    if ((!('modelPattern' in (value as Record<string, any>)) && !('model_pattern' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelPattern'] === undefined && (value as Record<string, any>)['model_pattern'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('outputCostPerMillionTokens' in (value as Record<string, any>)) && !('output_cost_per_million_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['outputCostPerMillionTokens'] === undefined && (value as Record<string, any>)['output_cost_per_million_tokens'] === undefined)) return false;
    return true;
}

export function ModelPricingFromJSON(json: any): ModelPricing {
    return ModelPricingFromJSONTyped(json, false);
}

export function ModelPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPricing {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheReadCostPerMillionTokens': json['cache_read_cost_per_million_tokens'] === undefined ? undefined : json['cache_read_cost_per_million_tokens'] === null ? null : json['cache_read_cost_per_million_tokens'],
        'cacheWriteCostPerMillionTokens': json['cache_write_cost_per_million_tokens'] === undefined ? undefined : json['cache_write_cost_per_million_tokens'] === null ? null : json['cache_write_cost_per_million_tokens'],
        'catalogSlug': json['catalog_slug'] === undefined ? undefined : json['catalog_slug'] === null ? null : json['catalog_slug'],
        'effectiveFrom': (json['effective_from'] == null ? json['effective_from'] : parseDateTime(json['effective_from'])),
        'id': json['id'],
        'inputCostPerMillionTokens': json['input_cost_per_million_tokens'],
        'longContext': json['long_context'] === undefined ? undefined : json['long_context'] === null ? null : LongContextTierFromJSON(json['long_context']),
        'modelPattern': json['model_pattern'],
        'modelProvider': json['model_provider'] === undefined ? undefined : json['model_provider'] === null ? null : json['model_provider'],
        'orgId': json['org_id'],
        'outputCostPerMillionTokens': json['output_cost_per_million_tokens'],
        'providerId': json['provider_id'] === undefined ? undefined : json['provider_id'] === null ? null : json['provider_id'],
        'providerName': json['provider_name'] === undefined ? undefined : json['provider_name'] === null ? null : json['provider_name'],
    };
}

export function ModelPricingToJSON(json: any): ModelPricing {
    return ModelPricingToJSONTyped(json, false);
}

export function ModelPricingToJSONTyped(value?: ModelPricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read_cost_per_million_tokens': value['cacheReadCostPerMillionTokens'],
        'cache_write_cost_per_million_tokens': value['cacheWriteCostPerMillionTokens'],
        'catalog_slug': value['catalogSlug'],
        'effective_from': value['effectiveFrom'] == null ? value['effectiveFrom'] : serializeDateTime(value['effectiveFrom']),
        'id': value['id'],
        'input_cost_per_million_tokens': value['inputCostPerMillionTokens'],
        'long_context': LongContextTierToJSON(value['longContext']),
        'model_pattern': value['modelPattern'],
        'model_provider': value['modelProvider'],
        'org_id': value['orgId'],
        'output_cost_per_million_tokens': value['outputCostPerMillionTokens'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
    };
}

