/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { RouteHealthStatus } from './RouteHealthStatus.js';
import {
    RouteHealthStatusFromJSON,
    RouteHealthStatusFromJSONTyped,
    RouteHealthStatusToJSON,
    RouteHealthStatusToJSONTyped,
} from './RouteHealthStatus.js';
import type { BudgetTargetStatus } from './BudgetTargetStatus.js';
import {
    BudgetTargetStatusFromJSON,
    BudgetTargetStatusFromJSONTyped,
    BudgetTargetStatusToJSON,
    BudgetTargetStatusToJSONTyped,
} from './BudgetTargetStatus.js';
import type { ModelStaleStatus } from './ModelStaleStatus.js';
import {
    ModelStaleStatusFromJSON,
    ModelStaleStatusFromJSONTyped,
    ModelStaleStatusToJSON,
    ModelStaleStatusToJSONTyped,
} from './ModelStaleStatus.js';
import type { EffectivePricing } from './EffectivePricing.js';
import {
    EffectivePricingFromJSON,
    EffectivePricingFromJSONTyped,
    EffectivePricingToJSON,
    EffectivePricingToJSONTyped,
} from './EffectivePricing.js';
import type { AutoDisabledReason } from './AutoDisabledReason.js';
import {
    AutoDisabledReasonFromJSON,
    AutoDisabledReasonFromJSONTyped,
    AutoDisabledReasonToJSON,
    AutoDisabledReasonToJSONTyped,
} from './AutoDisabledReason.js';
import type { ModelSource } from './ModelSource.js';
import {
    ModelSourceFromJSON,
    ModelSourceFromJSONTyped,
    ModelSourceToJSON,
    ModelSourceToJSONTyped,
} from './ModelSource.js';

/**
 * Same wrapper but for the cross-provider listing endpoint that returns
 * `ModelMappingWithProvider` (extra `provider_name` field).
 * @export
 * @interface ModelMappingWithProviderAndBudgetStatus
 */
export interface ModelMappingWithProviderAndBudgetStatus {
    /**
     * 
     */
    createdByEmail?: string;
    /**
     * 
     */
    createdByName?: string;
    /**
     * 
     */
    createdByUserId?: string;
    /**
     * Optional free text explaining *why* the last change was made
     * ("Raised for the Q3 batch job", "Vendor deprecated the old endpoint").
     * 
     * Admin-authored and rendered in the portal, so it is untrusted input:
     * length-capped here, escaped on render.
     */
    lastChangeNote?: string;
    /**
     * When the change named by `last_modified_by_*` happened.
     * 
     * Its own column rather than the row's `updated_at`, because `updated_at`
     * is bumped by writes nobody is attributed for -- pairing the two would
     * date a named admin's edit to a background job's clock. See the V75
     * migration for the full reasoning.
     */
    lastModifiedAt?: Date;
    /**
     * 
     */
    lastModifiedByEmail?: string;
    /**
     * 
     */
    lastModifiedByName?: string;
    /**
     * 
     */
    lastModifiedByUserId?: string;
    /**
     * See [`ModelMapping::auto_disabled_reason`].
     */
    autoDisabledReason?: AutoDisabledReason;
    /**
     * 
     */
    bareAlias: boolean;
    /**
     * When this mapping was created. Rows predating the column are
     * backfilled from the owning provider — see migration V58.
     */
    createdAt: Date;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    modelAlias: string;
    /**
     * 
     */
    priority: number;
    /**
     * 
     */
    providerAuthType: string;
    /**
     * 
     */
    providerId: string;
    /**
     * 
     */
    providerName: string;
    /**
     * 
     */
    requestTimeoutSecs?: number;
    /**
     * 
     */
    retryOn429Count: number;
    /**
     * 
     */
    retryOn429MaxWaitSecs: number;
    /**
     * See [`ModelMapping::source`].
     */
    source: ModelSource;
    /**
     * 
     */
    streamIdleTimeoutSecs?: number;
    /**
     * 
     */
    upstreamModel: string;
    /**
     * 
     */
    budgetStatus?: BudgetTargetStatus | null;
    /**
     * 
     */
    effectivePricing: EffectivePricing;
    /**
     * 
     */
    routeHealthStatus?: RouteHealthStatus | null;
    /**
     * See [`ModelMappingWithBudgetStatus::stale_status`].
     */
    staleStatus?: ModelStaleStatus | null;
}



/**
 * Check if a given object implements the ModelMappingWithProviderAndBudgetStatus interface.
 */
export function instanceOfModelMappingWithProviderAndBudgetStatus(value: object): value is ModelMappingWithProviderAndBudgetStatus {
    if ((!('bareAlias' in (value as Record<string, any>)) && !('bare_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['bareAlias'] === undefined && (value as Record<string, any>)['bare_alias'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if ((!('providerAuthType' in (value as Record<string, any>)) && !('provider_auth_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerAuthType'] === undefined && (value as Record<string, any>)['provider_auth_type'] === undefined)) return false;
    if ((!('providerId' in (value as Record<string, any>)) && !('provider_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerId'] === undefined && (value as Record<string, any>)['provider_id'] === undefined)) return false;
    if ((!('providerName' in (value as Record<string, any>)) && !('provider_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerName'] === undefined && (value as Record<string, any>)['provider_name'] === undefined)) return false;
    if ((!('retryOn429Count' in (value as Record<string, any>)) && !('retry_on_429_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryOn429Count'] === undefined && (value as Record<string, any>)['retry_on_429_count'] === undefined)) return false;
    if ((!('retryOn429MaxWaitSecs' in (value as Record<string, any>)) && !('retry_on_429_max_wait_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryOn429MaxWaitSecs'] === undefined && (value as Record<string, any>)['retry_on_429_max_wait_secs'] === undefined)) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if ((!('upstreamModel' in (value as Record<string, any>)) && !('upstream_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['upstreamModel'] === undefined && (value as Record<string, any>)['upstream_model'] === undefined)) return false;
    if ((!('effectivePricing' in (value as Record<string, any>)) && !('effective_pricing' in (value as Record<string, any>))) || ((value as Record<string, any>)['effectivePricing'] === undefined && (value as Record<string, any>)['effective_pricing'] === undefined)) return false;
    return true;
}

export function ModelMappingWithProviderAndBudgetStatusFromJSON(json: any): ModelMappingWithProviderAndBudgetStatus {
    return ModelMappingWithProviderAndBudgetStatusFromJSONTyped(json, false);
}

export function ModelMappingWithProviderAndBudgetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelMappingWithProviderAndBudgetStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'createdByEmail': json['created_by_email'] == null ? undefined : json['created_by_email'],
        'createdByName': json['created_by_name'] == null ? undefined : json['created_by_name'],
        'createdByUserId': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'lastChangeNote': json['last_change_note'] == null ? undefined : json['last_change_note'],
        'lastModifiedAt': json['last_modified_at'] == null ? undefined : (parseDateTime(json['last_modified_at'])),
        'lastModifiedByEmail': json['last_modified_by_email'] == null ? undefined : json['last_modified_by_email'],
        'lastModifiedByName': json['last_modified_by_name'] == null ? undefined : json['last_modified_by_name'],
        'lastModifiedByUserId': json['last_modified_by_user_id'] == null ? undefined : json['last_modified_by_user_id'],
        'autoDisabledReason': json['auto_disabled_reason'] == null ? undefined : AutoDisabledReasonFromJSON(json['auto_disabled_reason']),
        'bareAlias': json['bare_alias'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'enabled': json['enabled'],
        'id': json['id'],
        'modelAlias': json['model_alias'],
        'priority': json['priority'],
        'providerAuthType': json['provider_auth_type'],
        'providerId': json['provider_id'],
        'providerName': json['provider_name'],
        'requestTimeoutSecs': json['request_timeout_secs'] == null ? undefined : json['request_timeout_secs'],
        'retryOn429Count': json['retry_on_429_count'],
        'retryOn429MaxWaitSecs': json['retry_on_429_max_wait_secs'],
        'source': ModelSourceFromJSON(json['source']),
        'streamIdleTimeoutSecs': json['stream_idle_timeout_secs'] == null ? undefined : json['stream_idle_timeout_secs'],
        'upstreamModel': json['upstream_model'],
        'budgetStatus': json['budget_status'] === undefined ? undefined : json['budget_status'] === null ? null : BudgetTargetStatusFromJSON(json['budget_status']),
        'effectivePricing': EffectivePricingFromJSON(json['effective_pricing']),
        'routeHealthStatus': json['route_health_status'] === undefined ? undefined : json['route_health_status'] === null ? null : RouteHealthStatusFromJSON(json['route_health_status']),
        'staleStatus': json['stale_status'] === undefined ? undefined : json['stale_status'] === null ? null : ModelStaleStatusFromJSON(json['stale_status']),
    };
}

export function ModelMappingWithProviderAndBudgetStatusToJSON(json: any): ModelMappingWithProviderAndBudgetStatus {
    return ModelMappingWithProviderAndBudgetStatusToJSONTyped(json, false);
}

export function ModelMappingWithProviderAndBudgetStatusToJSONTyped(value?: ModelMappingWithProviderAndBudgetStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by_email': value['createdByEmail'],
        'created_by_name': value['createdByName'],
        'created_by_user_id': value['createdByUserId'],
        'last_change_note': value['lastChangeNote'],
        'last_modified_at': value['lastModifiedAt'] == null ? value['lastModifiedAt'] : serializeDateTime(value['lastModifiedAt']),
        'last_modified_by_email': value['lastModifiedByEmail'],
        'last_modified_by_name': value['lastModifiedByName'],
        'last_modified_by_user_id': value['lastModifiedByUserId'],
        'auto_disabled_reason': AutoDisabledReasonToJSON(value['autoDisabledReason']),
        'bare_alias': value['bareAlias'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'enabled': value['enabled'],
        'id': value['id'],
        'model_alias': value['modelAlias'],
        'priority': value['priority'],
        'provider_auth_type': value['providerAuthType'],
        'provider_id': value['providerId'],
        'provider_name': value['providerName'],
        'request_timeout_secs': value['requestTimeoutSecs'],
        'retry_on_429_count': value['retryOn429Count'],
        'retry_on_429_max_wait_secs': value['retryOn429MaxWaitSecs'],
        'source': ModelSourceToJSON(value['source']),
        'stream_idle_timeout_secs': value['streamIdleTimeoutSecs'],
        'upstream_model': value['upstreamModel'],
        'budget_status': BudgetTargetStatusToJSON(value['budgetStatus']),
        'effective_pricing': EffectivePricingToJSON(value['effectivePricing']),
        'route_health_status': RouteHealthStatusToJSON(value['routeHealthStatus']),
        'stale_status': ModelStaleStatusToJSON(value['staleStatus']),
    };
}

