/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { RouteHealthStatus } from './RouteHealthStatus.js';
import {
    RouteHealthStatusFromJSON,
    RouteHealthStatusFromJSONTyped,
    RouteHealthStatusToJSON,
    RouteHealthStatusToJSONTyped,
} from './RouteHealthStatus.js';
import type { BudgetTargetStatus } from './BudgetTargetStatus.js';
import {
    BudgetTargetStatusFromJSON,
    BudgetTargetStatusFromJSONTyped,
    BudgetTargetStatusToJSON,
    BudgetTargetStatusToJSONTyped,
} from './BudgetTargetStatus.js';
import type { ModelStaleStatus } from './ModelStaleStatus.js';
import {
    ModelStaleStatusFromJSON,
    ModelStaleStatusFromJSONTyped,
    ModelStaleStatusToJSON,
    ModelStaleStatusToJSONTyped,
} from './ModelStaleStatus.js';
import type { EffectivePricing } from './EffectivePricing.js';
import {
    EffectivePricingFromJSON,
    EffectivePricingFromJSONTyped,
    EffectivePricingToJSON,
    EffectivePricingToJSONTyped,
} from './EffectivePricing.js';
import type { AutoDisabledReason } from './AutoDisabledReason.js';
import {
    AutoDisabledReasonFromJSON,
    AutoDisabledReasonFromJSONTyped,
    AutoDisabledReasonToJSON,
    AutoDisabledReasonToJSONTyped,
} from './AutoDisabledReason.js';
import type { ModelSource } from './ModelSource.js';
import {
    ModelSourceFromJSON,
    ModelSourceFromJSONTyped,
    ModelSourceToJSON,
    ModelSourceToJSONTyped,
} from './ModelSource.js';

/**
 * Wraps a [`ModelMapping`] with the BCP-2813 `budget_status` annotation so
 * the admin Model Mappings page can render a "disabled by budget" pill.
 * The inner `ModelMapping` fields are flattened so the response is a
 * drop-in superset of the legacy `Vec<ModelMapping>` shape — older clients
 * that ignore `budget_status` keep working unchanged.
 * @export
 * @interface ModelMappingWithBudgetStatus
 */
export interface ModelMappingWithBudgetStatus {
    /**
     * 
     */
    createdByEmail?: string;
    /**
     * 
     */
    createdByName?: string;
    /**
     * 
     */
    createdByUserId?: string;
    /**
     * Optional free text explaining *why* the last change was made
     * ("Raised for the Q3 batch job", "Vendor deprecated the old endpoint").
     * 
     * Admin-authored and rendered in the portal, so it is untrusted input:
     * length-capped here, escaped on render.
     */
    lastChangeNote?: string;
    /**
     * When the change named by `last_modified_by_*` happened.
     * 
     * Its own column rather than the row's `updated_at`, because `updated_at`
     * is bumped by writes nobody is attributed for -- pairing the two would
     * date a named admin's edit to a background job's clock. See the V75
     * migration for the full reasoning.
     */
    lastModifiedAt?: Date;
    /**
     * 
     */
    lastModifiedByEmail?: string;
    /**
     * 
     */
    lastModifiedByName?: string;
    /**
     * 
     */
    lastModifiedByUserId?: string;
    /**
     * Set when the *gateway* turned this row off (BCP-3811's `full` sync
     * retiring a model the catalog dropped). `None` means a human decided
     * the `enabled` flag, and the reconciler will not touch it in either
     * direction — see migration V63. Any admin write to `enabled` clears this.
     * 
     * Clearing it is *not* a durable claim on the row, and it is easy to read
     * it that way. It protects a human's **disable** — the re-enable branch
     * requires the marker to be present, so a row a human turned off is never
     * turned back on. It cannot protect a human's **re-enable**: a cleared
     * marker is exactly what makes the row eligible for retirement again, so
     * under `full` a model the catalog still does not list is re-disabled on
     * the next tick. That is `full`'s contract ("enabled set tracks the
     * catalog"), not a bug — see
     * `model_sync::tests::re_enabling_a_dropped_model_is_retired_again_on_the_next_tick`.
     */
    autoDisabledReason?: AutoDisabledReason;
    /**
     * When `true` the row participates in bare-name resolution
     * (`POST /v1/chat/completions {"model": "<alias>"}`). When `false` the
     * row is enablement-only — addressable solely via the explicit
     * `<provider>/<upstream>` form. Custom-alias rows
     * (`model_alias != upstream_model`) are always `true`; 1:1 rows
     * default to `false` and admins opt in by creating an explicit Route
     * on the Model Routes tab.
     */
    bareAlias: boolean;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    modelAlias: string;
    /**
     * 
     */
    priority: number;
    /**
     * 
     */
    providerId: string;
    /**
     * Per-mapping (route-tier / model-tier) total-request timeout for
     * non-streaming requests (streaming responses have no total timeout).
     * Defaults to `TOTAL_REQUEST_TIMEOUT_DEFAULT_SECS` at insert. On a
     * custom-alias row this is the *route* tier; on the 1:1 enablement
     * (anchor) row it is the *model* tier consulted by the resolver for
     * every alias of that model. The range is fixed platform policy
     * (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`),
     * enforced by the column CHECK.
     */
    requestTimeoutSecs?: number;
    /**
     * Same-route retries on upstream 429. 0 means immediate failover.
     */
    retryOn429Count: number;
    /**
     * Cap on honoring upstream `Retry-After` header. 0 means use a small
     * built-in default and ignore the header value.
     */
    retryOn429MaxWaitSecs: number;
    /**
     * Whether the model was picked from the provider catalog or typed in by
     * an admin. Stamped once at create time and never recomputed — see
     * [`ModelSource`] and migration V61.
     */
    source: ModelSource;
    /**
     * Per-mapping stream-idle (per-chunk) timeout for streaming responses.
     * Defaults to `STREAM_IDLE_TIMEOUT_DEFAULT_SECS` at insert; enforced via
     * `tokio::time::timeout` around each upstream SSE/eventstream chunk
     * read. The range is fixed platform policy
     * (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`),
     * enforced by the column CHECK.
     */
    streamIdleTimeoutSecs?: number;
    /**
     * 
     */
    upstreamModel: string;
    /**
     * Populated when a `LlmProvider` / `Model` / `ModelAlias` budget with
     * `action_on_exhaust = block` is currently exhausted for the
     * mapping's `(provider_id, upstream_model, model_alias)` triple.
     * Runtime would drop this route from the resolved plan; the pill
     * surfaces the same state without filtering the row out of the
     * listing.
     */
    budgetStatus?: BudgetTargetStatus | null;
    /**
     * The rate a request against this mapping would be billed at, resolved
     * through the same tier chain the cost calculator uses (BCP-3564).
     * Always present; `source == "none"` means unpriced. See
     * [`crate::effective_pricing`].
     */
    effectivePricing: EffectivePricing;
    /**
     * Populated when the mapping's `(provider_id, upstream_model)` route is
     * in a passive-health cooldown. The page renders a "temporarily
     * unavailable" pill; the row stays in the listing.
     */
    routeHealthStatus?: RouteHealthStatus | null;
    /**
     * Populated when the model is enabled from a provider catalog that no
     * longer lists it (BCP-3812). Advisory: nothing is disabled on the
     * strength of it — retirement is BCP-3811's `full` mode, which the org
     * opts into. See [`crate::catalog_status`].
     */
    staleStatus?: ModelStaleStatus | null;
}



/**
 * Check if a given object implements the ModelMappingWithBudgetStatus interface.
 */
export function instanceOfModelMappingWithBudgetStatus(value: object): value is ModelMappingWithBudgetStatus {
    if ((!('bareAlias' in (value as Record<string, any>)) && !('bare_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['bareAlias'] === undefined && (value as Record<string, any>)['bare_alias'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if ((!('providerId' in (value as Record<string, any>)) && !('provider_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerId'] === undefined && (value as Record<string, any>)['provider_id'] === undefined)) return false;
    if ((!('retryOn429Count' in (value as Record<string, any>)) && !('retry_on_429_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryOn429Count'] === undefined && (value as Record<string, any>)['retry_on_429_count'] === undefined)) return false;
    if ((!('retryOn429MaxWaitSecs' in (value as Record<string, any>)) && !('retry_on_429_max_wait_secs' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryOn429MaxWaitSecs'] === undefined && (value as Record<string, any>)['retry_on_429_max_wait_secs'] === undefined)) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if ((!('upstreamModel' in (value as Record<string, any>)) && !('upstream_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['upstreamModel'] === undefined && (value as Record<string, any>)['upstream_model'] === undefined)) return false;
    if ((!('effectivePricing' in (value as Record<string, any>)) && !('effective_pricing' in (value as Record<string, any>))) || ((value as Record<string, any>)['effectivePricing'] === undefined && (value as Record<string, any>)['effective_pricing'] === undefined)) return false;
    return true;
}

export function ModelMappingWithBudgetStatusFromJSON(json: any): ModelMappingWithBudgetStatus {
    return ModelMappingWithBudgetStatusFromJSONTyped(json, false);
}

export function ModelMappingWithBudgetStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelMappingWithBudgetStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'createdByEmail': json['created_by_email'] == null ? undefined : json['created_by_email'],
        'createdByName': json['created_by_name'] == null ? undefined : json['created_by_name'],
        'createdByUserId': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'lastChangeNote': json['last_change_note'] == null ? undefined : json['last_change_note'],
        'lastModifiedAt': json['last_modified_at'] == null ? undefined : (parseDateTime(json['last_modified_at'])),
        'lastModifiedByEmail': json['last_modified_by_email'] == null ? undefined : json['last_modified_by_email'],
        'lastModifiedByName': json['last_modified_by_name'] == null ? undefined : json['last_modified_by_name'],
        'lastModifiedByUserId': json['last_modified_by_user_id'] == null ? undefined : json['last_modified_by_user_id'],
        'autoDisabledReason': json['auto_disabled_reason'] == null ? undefined : AutoDisabledReasonFromJSON(json['auto_disabled_reason']),
        'bareAlias': json['bare_alias'],
        'enabled': json['enabled'],
        'id': json['id'],
        'modelAlias': json['model_alias'],
        'priority': json['priority'],
        'providerId': json['provider_id'],
        'requestTimeoutSecs': json['request_timeout_secs'] == null ? undefined : json['request_timeout_secs'],
        'retryOn429Count': json['retry_on_429_count'],
        'retryOn429MaxWaitSecs': json['retry_on_429_max_wait_secs'],
        'source': ModelSourceFromJSON(json['source']),
        'streamIdleTimeoutSecs': json['stream_idle_timeout_secs'] == null ? undefined : json['stream_idle_timeout_secs'],
        'upstreamModel': json['upstream_model'],
        'budgetStatus': json['budget_status'] === undefined ? undefined : json['budget_status'] === null ? null : BudgetTargetStatusFromJSON(json['budget_status']),
        'effectivePricing': EffectivePricingFromJSON(json['effective_pricing']),
        'routeHealthStatus': json['route_health_status'] === undefined ? undefined : json['route_health_status'] === null ? null : RouteHealthStatusFromJSON(json['route_health_status']),
        'staleStatus': json['stale_status'] === undefined ? undefined : json['stale_status'] === null ? null : ModelStaleStatusFromJSON(json['stale_status']),
    };
}

export function ModelMappingWithBudgetStatusToJSON(json: any): ModelMappingWithBudgetStatus {
    return ModelMappingWithBudgetStatusToJSONTyped(json, false);
}

export function ModelMappingWithBudgetStatusToJSONTyped(value?: ModelMappingWithBudgetStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by_email': value['createdByEmail'],
        'created_by_name': value['createdByName'],
        'created_by_user_id': value['createdByUserId'],
        'last_change_note': value['lastChangeNote'],
        'last_modified_at': value['lastModifiedAt'] == null ? value['lastModifiedAt'] : serializeDateTime(value['lastModifiedAt']),
        'last_modified_by_email': value['lastModifiedByEmail'],
        'last_modified_by_name': value['lastModifiedByName'],
        'last_modified_by_user_id': value['lastModifiedByUserId'],
        'auto_disabled_reason': AutoDisabledReasonToJSON(value['autoDisabledReason']),
        'bare_alias': value['bareAlias'],
        'enabled': value['enabled'],
        'id': value['id'],
        'model_alias': value['modelAlias'],
        'priority': value['priority'],
        'provider_id': value['providerId'],
        'request_timeout_secs': value['requestTimeoutSecs'],
        'retry_on_429_count': value['retryOn429Count'],
        'retry_on_429_max_wait_secs': value['retryOn429MaxWaitSecs'],
        'source': ModelSourceToJSON(value['source']),
        'stream_idle_timeout_secs': value['streamIdleTimeoutSecs'],
        'upstream_model': value['upstreamModel'],
        'budget_status': BudgetTargetStatusToJSON(value['budgetStatus']),
        'effective_pricing': EffectivePricingToJSON(value['effectivePricing']),
        'route_health_status': RouteHealthStatusToJSON(value['routeHealthStatus']),
        'stale_status': ModelStaleStatusToJSON(value['staleStatus']),
    };
}

