/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Match any model served by the given provider connection.
 * 
 * Asymmetric between the two policy directions — see
 * [`ModelAccessTarget::grants`]. As a *denial* this covers everything
 * routed to the provider, custom aliases included. As a *grant* it
 * covers the provider's own models only.
 * @export
 * @interface ModelAccessTargetOneOf2
 */
export interface ModelAccessTargetOneOf2 {
    /**
     * 
     */
    kind: ModelAccessTargetOneOf2KindEnum;
    /**
     * 
     */
    providerId: string;
}


/**
 * @export
 */
export const ModelAccessTargetOneOf2KindEnum = {
    Provider: 'provider',
} as const;
export type ModelAccessTargetOneOf2KindEnum = typeof ModelAccessTargetOneOf2KindEnum[keyof typeof ModelAccessTargetOneOf2KindEnum];


/**
 * Check if a given object implements the ModelAccessTargetOneOf2 interface.
 */
export function instanceOfModelAccessTargetOneOf2(value: object): value is ModelAccessTargetOneOf2 {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (value['kind'] !== 'provider') return false;
    
    if ((!('providerId' in (value as Record<string, any>)) && !('provider_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['providerId'] === undefined && (value as Record<string, any>)['provider_id'] === undefined)) return false;
    return true;
}

export function ModelAccessTargetOneOf2FromJSON(json: any): ModelAccessTargetOneOf2 {
    return ModelAccessTargetOneOf2FromJSONTyped(json, false);
}

export function ModelAccessTargetOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccessTargetOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'providerId': json['provider_id'],
    };
}

export function ModelAccessTargetOneOf2ToJSON(json: any): ModelAccessTargetOneOf2 {
    return ModelAccessTargetOneOf2ToJSONTyped(json, false);
}

export function ModelAccessTargetOneOf2ToJSONTyped(value?: ModelAccessTargetOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'provider_id': value['providerId'],
    };
}

