/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether a provider tracks Barndoor's model catalog, and how far. Persisted
 * as a `VARCHAR(16)` constrained to `off | additive | full` (see migration
 * V63).
 * 
 * The three-way split is the whole point: an org that wants new models
 * without the gateway ever removing anything, and an org that also wants
 * retired models cleaned up, are asking for different things and both are
 * legitimate. Retirement stays a separate step up rather than riding along
 * with additions, because it is the only one of the two that can take a route
 * out of service.
 * @export
 */
export const ModelSyncMode = {
    Off: 'off',
    Additive: 'additive',
    Full: 'full',
} as const;
export type ModelSyncMode = typeof ModelSyncMode[keyof typeof ModelSyncMode];


export function instanceOfModelSyncMode(value: any): boolean {
    for (const key in ModelSyncMode) {
        if (Object.prototype.hasOwnProperty.call(ModelSyncMode, key)) {
            if (ModelSyncMode[key as keyof typeof ModelSyncMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelSyncModeFromJSON(json: any): ModelSyncMode {
    return ModelSyncModeFromJSONTyped(json, false);
}

export function ModelSyncModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSyncMode {
    return json as ModelSyncMode;
}

export function ModelSyncModeToJSON(value?: ModelSyncMode | null): any {
    return value as any;
}

export function ModelSyncModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ModelSyncMode {
    return value as ModelSyncMode;
}

