/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AppType } from './AppType.js';
import {
    AppTypeFromJSON,
    AppTypeFromJSONTyped,
    AppTypeToJSON,
    AppTypeToJSONTyped,
} from './AppType.js';

/**
 * 
 * @export
 * @interface OAuthConfig
 */
export interface OAuthConfig {
    /**
     * 
     */
    callbacks?: Array<string>;
    /**
     * 
     */
    allowedLogoutUrls?: Array<string>;
    /**
     * 
     */
    appType?: AppType | null;
}



/**
 * Check if a given object implements the OAuthConfig interface.
 */
export function instanceOfOAuthConfig(value: object): value is OAuthConfig {
    return true;
}

export function OAuthConfigFromJSON(json: any): OAuthConfig {
    return OAuthConfigFromJSONTyped(json, false);
}

export function OAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'callbacks': json['callbacks'] == null ? undefined : json['callbacks'],
        'allowedLogoutUrls': json['allowed_logout_urls'] == null ? undefined : json['allowed_logout_urls'],
        'appType': json['app_type'] === undefined ? undefined : json['app_type'] === null ? null : AppTypeFromJSON(json['app_type']),
    };
}

export function OAuthConfigToJSON(json: any): OAuthConfig {
    return OAuthConfigToJSONTyped(json, false);
}

export function OAuthConfigToJSONTyped(value?: OAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'callbacks': value['callbacks'],
        'allowed_logout_urls': value['allowedLogoutUrls'],
        'app_type': AppTypeToJSON(value['appType']),
    };
}

