/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionOfOutput } from './ConditionOfOutput.js';
import {
    ConditionOfOutputFromJSON,
    ConditionOfOutputFromJSONTyped,
    ConditionOfOutputToJSON,
    ConditionOfOutputToJSONTyped,
} from './ConditionOfOutput.js';

/**
 * 
 * @export
 * @interface OperatorNoneOutput
 */
export interface OperatorNoneOutput {
    /**
     * Logical NOR — the rule applies only if NO matcher in `of` evaluates true.
     */
    none: ConditionOfOutput;
}

/**
 * Check if a given object implements the OperatorNoneOutput interface.
 */
export function instanceOfOperatorNoneOutput(value: object): value is OperatorNoneOutput {
    if (!('none' in value) || value['none'] === undefined) return false;
    return true;
}

export function OperatorNoneOutputFromJSON(json: any): OperatorNoneOutput {
    return OperatorNoneOutputFromJSONTyped(json, false);
}

export function OperatorNoneOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorNoneOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'none': ConditionOfOutputFromJSON(json['none']),
    };
}

export function OperatorNoneOutputToJSON(json: any): OperatorNoneOutput {
    return OperatorNoneOutputToJSONTyped(json, false);
}

export function OperatorNoneOutputToJSONTyped(value?: OperatorNoneOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'none': ConditionOfOutputToJSON(value['none']),
    };
}

