/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionOfInput } from './ConditionOfInput.js';
import {
    ConditionOfInputFromJSON,
    ConditionOfInputFromJSONTyped,
    ConditionOfInputToJSON,
    ConditionOfInputToJSONTyped,
} from './ConditionOfInput.js';

/**
 * 
 * @export
 * @interface OperatorAnyInput
 */
export interface OperatorAnyInput {
    /**
     * Logical OR — at least one matcher in `of` must evaluate true.
     */
    any: ConditionOfInput;
}

/**
 * Check if a given object implements the OperatorAnyInput interface.
 */
export function instanceOfOperatorAnyInput(value: object): value is OperatorAnyInput {
    if (!('any' in value) || value['any'] === undefined) return false;
    return true;
}

export function OperatorAnyInputFromJSON(json: any): OperatorAnyInput {
    return OperatorAnyInputFromJSONTyped(json, false);
}

export function OperatorAnyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorAnyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'any': ConditionOfInputFromJSON(json['any']),
    };
}

export function OperatorAnyInputToJSON(json: any): OperatorAnyInput {
    return OperatorAnyInputToJSONTyped(json, false);
}

export function OperatorAnyInputToJSONTyped(value?: OperatorAnyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'any': ConditionOfInputToJSON(value['any']),
    };
}

