/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionOfOutput } from './ConditionOfOutput.js';
import {
    ConditionOfOutputFromJSON,
    ConditionOfOutputFromJSONTyped,
    ConditionOfOutputToJSON,
    ConditionOfOutputToJSONTyped,
} from './ConditionOfOutput.js';

/**
 * 
 * @export
 * @interface OperatorAnyOutput
 */
export interface OperatorAnyOutput {
    /**
     * Logical OR — at least one matcher in `of` must evaluate true.
     */
    any: ConditionOfOutput;
}

/**
 * Check if a given object implements the OperatorAnyOutput interface.
 */
export function instanceOfOperatorAnyOutput(value: object): value is OperatorAnyOutput {
    if (!('any' in value) || value['any'] === undefined) return false;
    return true;
}

export function OperatorAnyOutputFromJSON(json: any): OperatorAnyOutput {
    return OperatorAnyOutputFromJSONTyped(json, false);
}

export function OperatorAnyOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorAnyOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'any': ConditionOfOutputFromJSON(json['any']),
    };
}

export function OperatorAnyOutputToJSON(json: any): OperatorAnyOutput {
    return OperatorAnyOutputToJSONTyped(json, false);
}

export function OperatorAnyOutputToJSONTyped(value?: OperatorAnyOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'any': ConditionOfOutputToJSON(value['any']),
    };
}

