/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Aggregated roles and groups for all users in an organization.
 * 
 * These are the names a policy rule addresses through ``roles_groups``. The
 * values here are UNPREFIXED; a policy rule requires the ``role:``/``group:``
 * prefix (see ``PolicyRule.roles_groups`` in policy-service), so a value
 * ``Engineering`` from ``groups`` is written as ``group:Engineering``.
 * @export
 * @interface OrganizationRolesGroupsResponse
 */
export interface OrganizationRolesGroupsResponse {
    /**
     * Distinct role names assigned to at least one user in the organization. Unprefixed — use as `role:<name>` in a policy rule's `roles_groups`.
     */
    roles: Array<string>;
    /**
     * Distinct group names assigned to at least one user in the organization. Unprefixed — use as `group:<name>` in a policy rule's `roles_groups`.
     */
    groups: Array<string>;
}

/**
 * Check if a given object implements the OrganizationRolesGroupsResponse interface.
 */
export function instanceOfOrganizationRolesGroupsResponse(value: object): value is OrganizationRolesGroupsResponse {
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function OrganizationRolesGroupsResponseFromJSON(json: any): OrganizationRolesGroupsResponse {
    return OrganizationRolesGroupsResponseFromJSONTyped(json, false);
}

export function OrganizationRolesGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRolesGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': json['roles'],
        'groups': json['groups'],
    };
}

export function OrganizationRolesGroupsResponseToJSON(json: any): OrganizationRolesGroupsResponse {
    return OrganizationRolesGroupsResponseToJSONTyped(json, false);
}

export function OrganizationRolesGroupsResponseToJSONTyped(value?: OrganizationRolesGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': value['roles'],
        'groups': value['groups'],
    };
}

