/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PolicySummary } from './PolicySummary.js';
import {
    PolicySummaryFromJSON,
    PolicySummaryFromJSONTyped,
    PolicySummaryToJSON,
    PolicySummaryToJSONTyped,
} from './PolicySummary.js';
import type { PaginationMeta } from './PaginationMeta.js';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta.js';

/**
 * 
 * @export
 * @interface PaginationResponsePolicySummary
 */
export interface PaginationResponsePolicySummary {
    /**
     * Array of items for current page
     */
    data: Array<PolicySummary>;
    /**
     * Pagination metadata
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginationResponsePolicySummary interface.
 */
export function instanceOfPaginationResponsePolicySummary(value: object): value is PaginationResponsePolicySummary {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginationResponsePolicySummaryFromJSON(json: any): PaginationResponsePolicySummary {
    return PaginationResponsePolicySummaryFromJSONTyped(json, false);
}

export function PaginationResponsePolicySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponsePolicySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PolicySummaryFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginationResponsePolicySummaryToJSON(json: any): PaginationResponsePolicySummary {
    return PaginationResponsePolicySummaryToJSONTyped(json, false);
}

export function PaginationResponsePolicySummaryToJSONTyped(value?: PaginationResponsePolicySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PolicySummaryToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

