/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginatedResponseAllowListEntryResponseItemsInner } from './PaginatedResponseAllowListEntryResponseItemsInner.js';
import {
    PaginatedResponseAllowListEntryResponseItemsInnerFromJSON,
    PaginatedResponseAllowListEntryResponseItemsInnerFromJSONTyped,
    PaginatedResponseAllowListEntryResponseItemsInnerToJSON,
    PaginatedResponseAllowListEntryResponseItemsInnerToJSONTyped,
} from './PaginatedResponseAllowListEntryResponseItemsInner.js';

/**
 * 
 * @export
 * @interface PaginatedResponseAllowListEntryResponse
 */
export interface PaginatedResponseAllowListEntryResponse {
    /**
     * 
     */
    items: Array<PaginatedResponseAllowListEntryResponseItemsInner>;
    /**
     * 
     */
    nextPageToken: string;
    /**
     * 
     */
    totalCount: number;
}

/**
 * Check if a given object implements the PaginatedResponseAllowListEntryResponse interface.
 */
export function instanceOfPaginatedResponseAllowListEntryResponse(value: object): value is PaginatedResponseAllowListEntryResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextPageToken' in (value as Record<string, any>)) && !('next_page_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextPageToken'] === undefined && (value as Record<string, any>)['next_page_token'] === undefined)) return false;
    if ((!('totalCount' in (value as Record<string, any>)) && !('total_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCount'] === undefined && (value as Record<string, any>)['total_count'] === undefined)) return false;
    return true;
}

export function PaginatedResponseAllowListEntryResponseFromJSON(json: any): PaginatedResponseAllowListEntryResponse {
    return PaginatedResponseAllowListEntryResponseFromJSONTyped(json, false);
}

export function PaginatedResponseAllowListEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseAllowListEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PaginatedResponseAllowListEntryResponseItemsInnerFromJSON)),
        'nextPageToken': json['next_page_token'],
        'totalCount': json['total_count'],
    };
}

export function PaginatedResponseAllowListEntryResponseToJSON(json: any): PaginatedResponseAllowListEntryResponse {
    return PaginatedResponseAllowListEntryResponseToJSONTyped(json, false);
}

export function PaginatedResponseAllowListEntryResponseToJSONTyped(value?: PaginatedResponseAllowListEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PaginatedResponseAllowListEntryResponseItemsInnerToJSON)),
        'next_page_token': value['nextPageToken'],
        'total_count': value['totalCount'],
    };
}

