/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Live-impact counts for one policy, by severity.
 * 
 * Every known key is zero-filled — a caller rendering a badge should not
 * have to distinguish "no breaking impacts" from "the key is missing".
 * 
 * ``extra="allow"``: ``PolicyImpactService.summary_by_policy`` deliberately
 * surfaces a severity it doesn't recognize as its own key (see that
 * docstring — "silently dropping an unrecognised severity would make a
 * future fourth tier vanish from every badge count with no signal at all").
 * A strict three-field model would undo that the moment the dict crosses
 * this schema, since Pydantic v2's default ``extra="ignore"`` drops
 * unmodeled kwargs silently. Allowing extras keeps the passthrough honest
 * without this schema having to know the full severity vocabulary.
 * @export
 * @interface PolicyImpactSeverityCounts
 */
export interface PolicyImpactSeverityCounts {
    [key: string]: any | any;
    /**
     * 
     */
    breaking?: number;
    /**
     * 
     */
    review?: number;
    /**
     * 
     */
    info?: number;
}

/**
 * Check if a given object implements the PolicyImpactSeverityCounts interface.
 */
export function instanceOfPolicyImpactSeverityCounts(value: object): value is PolicyImpactSeverityCounts {
    return true;
}

export function PolicyImpactSeverityCountsFromJSON(json: any): PolicyImpactSeverityCounts {
    return PolicyImpactSeverityCountsFromJSONTyped(json, false);
}

export function PolicyImpactSeverityCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyImpactSeverityCounts {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'breaking': json['breaking'] == null ? undefined : json['breaking'],
        'review': json['review'] == null ? undefined : json['review'],
        'info': json['info'] == null ? undefined : json['info'],
    };
}

export function PolicyImpactSeverityCountsToJSON(json: any): PolicyImpactSeverityCounts {
    return PolicyImpactSeverityCountsToJSONTyped(json, false);
}

export function PolicyImpactSeverityCountsToJSONTyped(value?: PolicyImpactSeverityCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'breaking': value['breaking'],
        'review': value['review'],
        'info': value['info'],
    };
}

