/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface PolicyRevisionCompareSide
 */
export interface PolicyRevisionCompareSide {
    /**
     * 
     */
    revisionId: string;
    /**
     * 
     */
    revisedAt: Date;
    /**
     * 
     */
    revisedBy: string;
    /**
     * 
     */
    revisedByName?: string | null;
    /**
     * 
     */
    triggeredBy?: string | null;
    /**
     * 
     */
    triggeredByName?: string | null;
    /**
     * 
     */
    versionNumber: number;
}

/**
 * Check if a given object implements the PolicyRevisionCompareSide interface.
 */
export function instanceOfPolicyRevisionCompareSide(value: object): value is PolicyRevisionCompareSide {
    if ((!('revisionId' in (value as Record<string, any>)) && !('revision_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['revisionId'] === undefined && (value as Record<string, any>)['revision_id'] === undefined)) return false;
    if ((!('revisedAt' in (value as Record<string, any>)) && !('revised_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['revisedAt'] === undefined && (value as Record<string, any>)['revised_at'] === undefined)) return false;
    if ((!('revisedBy' in (value as Record<string, any>)) && !('revised_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['revisedBy'] === undefined && (value as Record<string, any>)['revised_by'] === undefined)) return false;
    if ((!('versionNumber' in (value as Record<string, any>)) && !('version_number' in (value as Record<string, any>))) || ((value as Record<string, any>)['versionNumber'] === undefined && (value as Record<string, any>)['version_number'] === undefined)) return false;
    return true;
}

export function PolicyRevisionCompareSideFromJSON(json: any): PolicyRevisionCompareSide {
    return PolicyRevisionCompareSideFromJSONTyped(json, false);
}

export function PolicyRevisionCompareSideFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRevisionCompareSide {
    if (json == null) {
        return json;
    }
    return {
        
        'revisionId': json['revision_id'],
        'revisedAt': (json['revised_at'] == null ? json['revised_at'] : parseDateTime(json['revised_at'])),
        'revisedBy': json['revised_by'],
        'revisedByName': json['revised_by_name'] === undefined ? undefined : json['revised_by_name'] === null ? null : json['revised_by_name'],
        'triggeredBy': json['triggered_by'] === undefined ? undefined : json['triggered_by'] === null ? null : json['triggered_by'],
        'triggeredByName': json['triggered_by_name'] === undefined ? undefined : json['triggered_by_name'] === null ? null : json['triggered_by_name'],
        'versionNumber': json['version_number'],
    };
}

export function PolicyRevisionCompareSideToJSON(json: any): PolicyRevisionCompareSide {
    return PolicyRevisionCompareSideToJSONTyped(json, false);
}

export function PolicyRevisionCompareSideToJSONTyped(value?: PolicyRevisionCompareSide | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revision_id': value['revisionId'],
        'revised_at': value['revisedAt'] == null ? value['revisedAt'] : serializeDateTime(value['revisedAt']),
        'revised_by': value['revisedBy'],
        'revised_by_name': value['revisedByName'],
        'triggered_by': value['triggeredBy'],
        'triggered_by_name': value['triggeredByName'],
        'version_number': value['versionNumber'],
    };
}

