/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PolicyDetail } from './PolicyDetail.js';
import {
    PolicyDetailFromJSON,
    PolicyDetailFromJSONTyped,
    PolicyDetailToJSON,
    PolicyDetailToJSONTyped,
} from './PolicyDetail.js';

/**
 * Envelope for detail responses.
 * @export
 * @interface PolicyDetailResponse
 */
export interface PolicyDetailResponse {
    /**
     * 
     */
    policy: PolicyDetail;
}

/**
 * Check if a given object implements the PolicyDetailResponse interface.
 */
export function instanceOfPolicyDetailResponse(value: object): value is PolicyDetailResponse {
    if (!('policy' in value) || value['policy'] === undefined) return false;
    return true;
}

export function PolicyDetailResponseFromJSON(json: any): PolicyDetailResponse {
    return PolicyDetailResponseFromJSONTyped(json, false);
}

export function PolicyDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'policy': PolicyDetailFromJSON(json['policy']),
    };
}

export function PolicyDetailResponseToJSON(json: any): PolicyDetailResponse {
    return PolicyDetailResponseToJSONTyped(json, false);
}

export function PolicyDetailResponseToJSONTyped(value?: PolicyDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy': PolicyDetailToJSON(value['policy']),
    };
}

