/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Match1 } from './Match1.js';
import {
    Match1FromJSON,
    Match1FromJSONTyped,
    Match1ToJSON,
    Match1ToJSONTyped,
} from './Match1.js';

/**
 * 
 * @export
 * @interface PolicyRuleConditionOutput
 */
export interface PolicyRuleConditionOutput {
    /**
     * 
     */
    match: Match1;
}

/**
 * Check if a given object implements the PolicyRuleConditionOutput interface.
 */
export function instanceOfPolicyRuleConditionOutput(value: object): value is PolicyRuleConditionOutput {
    if (!('match' in value) || value['match'] === undefined) return false;
    return true;
}

export function PolicyRuleConditionOutputFromJSON(json: any): PolicyRuleConditionOutput {
    return PolicyRuleConditionOutputFromJSONTyped(json, false);
}

export function PolicyRuleConditionOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRuleConditionOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'match': Match1FromJSON(json['match']),
    };
}

export function PolicyRuleConditionOutputToJSON(json: any): PolicyRuleConditionOutput {
    return PolicyRuleConditionOutputToJSONTyped(json, false);
}

export function PolicyRuleConditionOutputToJSONTyped(value?: PolicyRuleConditionOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match': Match1ToJSON(value['match']),
    };
}

