/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PolicyRuleConditionOutput } from './PolicyRuleConditionOutput.js';
import {
    PolicyRuleConditionOutputFromJSON,
    PolicyRuleConditionOutputFromJSONTyped,
    PolicyRuleConditionOutputToJSON,
    PolicyRuleConditionOutputToJSONTyped,
} from './PolicyRuleConditionOutput.js';

/**
 * A single rule: which principals may take which tool actions, optionally conditioned.
 * @export
 * @interface PolicyRuleOutput
 */
export interface PolicyRuleOutput {
    /**
     * Optional display name for the rule. Letters, digits, spaces, hyphens and underscores only — a colon or other punctuation is rejected with a 422, which is easy to hit because rule names tend to read like `Security: view agents`. Names must also be unique within the policy once punctuation is normalized, so `My Rule` and `My-Rule` collide.
     */
    name?: string | null;
    /**
     * Optional human-readable description for the rule; has no effect on enforcement
     */
    description?: string | null;
    /**
     * Effect of the rule: True grants the listed `actions`, False denies them. Access is denied by default, so a tool that no rule grants is already blocked — an explicit False rule is only needed to carve an exception out of a broader allow. The effective model is tri-state rather than binary: Always Allow is True on the plain action, Needs Approval is True on the `:approve` twin (see `actions`), and Blocked is simply the absence of a grant.
     */
    authorized?: boolean | null;
    /**
     * Whether this rule is enforced. False keeps the rule on the policy but omits it from enforcement — use it to disable a rule without deleting it.
     */
    active?: boolean;
    /**
     * Tool actions this rule matches, in the wire format `tools/call:<tool_name>` — for example `tools/call:create_issue`. Use `*` to match every action on the server. Tool names are specific to the target MCP server: enumerate the server's real tools rather than guessing names. A trailing `:approve` selects the Needs-Approval variant of a tool (`tools/call:create_issue:approve`), which requires per-call human confirmation; the plain action is Always Allow. Do not grant both twins of the same tool in one rule.
     */
    actions: Array<string>;
    /**
     * Principals this rule applies to, as PREFIXED entries: `role:<role_name>` for an IdP/Keycloak role, `group:<group_name>` for a user group, or the literal `*` for all users (the default). A bare name with no `role:`/`group:` prefix matches NOTHING. Retrieve the organization's real role and group names from `GET /api/identity/public/v1/users/roles-groups`. A principal set should appear on at most ONE rule in a policy — collect all of its actions there instead of spreading them over several rules.
     */
    rolesGroups?: Array<string>;
    /**
     * Optional CEL condition; the rule applies only when it evaluates true. Shape is `{"match": <matcher>}`. Omit entirely for an unconditional rule.
     */
    condition?: PolicyRuleConditionOutput | null;
}

/**
 * Check if a given object implements the PolicyRuleOutput interface.
 */
export function instanceOfPolicyRuleOutput(value: object): value is PolicyRuleOutput {
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function PolicyRuleOutputFromJSON(json: any): PolicyRuleOutput {
    return PolicyRuleOutputFromJSONTyped(json, false);
}

export function PolicyRuleOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRuleOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'authorized': json['authorized'] === undefined ? undefined : json['authorized'] === null ? null : json['authorized'],
        'active': json['active'] == null ? undefined : json['active'],
        'actions': json['actions'],
        'rolesGroups': json['roles_groups'] == null ? undefined : json['roles_groups'],
        'condition': json['condition'] === undefined ? undefined : json['condition'] === null ? null : PolicyRuleConditionOutputFromJSON(json['condition']),
    };
}

export function PolicyRuleOutputToJSON(json: any): PolicyRuleOutput {
    return PolicyRuleOutputToJSONTyped(json, false);
}

export function PolicyRuleOutputToJSONTyped(value?: PolicyRuleOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'authorized': value['authorized'],
        'active': value['active'],
        'actions': value['actions'],
        'roles_groups': value['rolesGroups'],
        'condition': PolicyRuleConditionOutputToJSON(value['condition']),
    };
}

