/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * One ``policy.policy_impact`` row, as returned by the impact list/detail routes.
 * 
 * Built with ``model_validate(row, from_attributes=True)`` directly off the ORM
 * row — the field set below is a straight projection of
 * ``policy_service.db.policy_impact.PolicyImpact``, so there is no hand-mapping
 * to drift out of sync.
 * @export
 * @interface PolicyImpactSummary
 */
export interface PolicyImpactSummary {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    policyId: string;
    /**
     * 
     */
    mcpServerId: string;
    /**
     * 
     */
    changeKind: string;
    /**
     * 
     */
    toolName: string;
    /**
     * 
     */
    severity: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    fromVersion?: number | null;
    /**
     * 
     */
    toVersion: number;
    /**
     * 
     */
    snapshotId: string;
    /**
     * 
     */
    policyStatusAtEval: string;
    /**
     * 
     */
    detail?: { [key: string]: any; };
    /**
     * 
     */
    acknowledgedAt?: Date | null;
    /**
     * 
     */
    acknowledgedBy?: string | null;
    /**
     * 
     */
    resolvedAt?: Date | null;
    /**
     * 
     */
    resolvedBy?: string | null;
    /**
     * 
     */
    resolution?: string | null;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PolicyImpactSummary interface.
 */
export function instanceOfPolicyImpactSummary(value: object): value is PolicyImpactSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('policyId' in (value as Record<string, any>)) && !('policy_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyId'] === undefined && (value as Record<string, any>)['policy_id'] === undefined)) return false;
    if ((!('mcpServerId' in (value as Record<string, any>)) && !('mcp_server_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerId'] === undefined && (value as Record<string, any>)['mcp_server_id'] === undefined)) return false;
    if ((!('changeKind' in (value as Record<string, any>)) && !('change_kind' in (value as Record<string, any>))) || ((value as Record<string, any>)['changeKind'] === undefined && (value as Record<string, any>)['change_kind'] === undefined)) return false;
    if ((!('toolName' in (value as Record<string, any>)) && !('tool_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolName'] === undefined && (value as Record<string, any>)['tool_name'] === undefined)) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('toVersion' in (value as Record<string, any>)) && !('to_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['toVersion'] === undefined && (value as Record<string, any>)['to_version'] === undefined)) return false;
    if ((!('snapshotId' in (value as Record<string, any>)) && !('snapshot_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['snapshotId'] === undefined && (value as Record<string, any>)['snapshot_id'] === undefined)) return false;
    if ((!('policyStatusAtEval' in (value as Record<string, any>)) && !('policy_status_at_eval' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyStatusAtEval'] === undefined && (value as Record<string, any>)['policy_status_at_eval'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function PolicyImpactSummaryFromJSON(json: any): PolicyImpactSummary {
    return PolicyImpactSummaryFromJSONTyped(json, false);
}

export function PolicyImpactSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyImpactSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'policyId': json['policy_id'],
        'mcpServerId': json['mcp_server_id'],
        'changeKind': json['change_kind'],
        'toolName': json['tool_name'],
        'severity': json['severity'],
        'status': json['status'],
        'fromVersion': json['from_version'] === undefined ? undefined : json['from_version'] === null ? null : json['from_version'],
        'toVersion': json['to_version'],
        'snapshotId': json['snapshot_id'],
        'policyStatusAtEval': json['policy_status_at_eval'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'acknowledgedAt': json['acknowledged_at'] === undefined ? undefined : json['acknowledged_at'] === null ? null : (parseDateTime(json['acknowledged_at'])),
        'acknowledgedBy': json['acknowledged_by'] === undefined ? undefined : json['acknowledged_by'] === null ? null : json['acknowledged_by'],
        'resolvedAt': json['resolved_at'] === undefined ? undefined : json['resolved_at'] === null ? null : (parseDateTime(json['resolved_at'])),
        'resolvedBy': json['resolved_by'] === undefined ? undefined : json['resolved_by'] === null ? null : json['resolved_by'],
        'resolution': json['resolution'] === undefined ? undefined : json['resolution'] === null ? null : json['resolution'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
    };
}

export function PolicyImpactSummaryToJSON(json: any): PolicyImpactSummary {
    return PolicyImpactSummaryToJSONTyped(json, false);
}

export function PolicyImpactSummaryToJSONTyped(value?: PolicyImpactSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'policy_id': value['policyId'],
        'mcp_server_id': value['mcpServerId'],
        'change_kind': value['changeKind'],
        'tool_name': value['toolName'],
        'severity': value['severity'],
        'status': value['status'],
        'from_version': value['fromVersion'],
        'to_version': value['toVersion'],
        'snapshot_id': value['snapshotId'],
        'policy_status_at_eval': value['policyStatusAtEval'],
        'detail': value['detail'],
        'acknowledged_at': value['acknowledgedAt'] == null ? value['acknowledgedAt'] : serializeDateTime(value['acknowledgedAt']),
        'acknowledged_by': value['acknowledgedBy'],
        'resolved_at': value['resolvedAt'] == null ? value['resolvedAt'] : serializeDateTime(value['resolvedAt']),
        'resolved_by': value['resolvedBy'],
        'resolution': value['resolution'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

