/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Match } from './Match.js';
import {
    MatchFromJSON,
    MatchFromJSONTyped,
    MatchToJSON,
    MatchToJSONTyped,
} from './Match.js';

/**
 * 
 * @export
 * @interface PolicyRuleConditionInput
 */
export interface PolicyRuleConditionInput {
    /**
     * 
     */
    match: Match;
}

/**
 * Check if a given object implements the PolicyRuleConditionInput interface.
 */
export function instanceOfPolicyRuleConditionInput(value: object): value is PolicyRuleConditionInput {
    if (!('match' in value) || value['match'] === undefined) return false;
    return true;
}

export function PolicyRuleConditionInputFromJSON(json: any): PolicyRuleConditionInput {
    return PolicyRuleConditionInputFromJSONTyped(json, false);
}

export function PolicyRuleConditionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRuleConditionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'match': MatchFromJSON(json['match']),
    };
}

export function PolicyRuleConditionInputToJSON(json: any): PolicyRuleConditionInput {
    return PolicyRuleConditionInputToJSONTyped(json, false);
}

export function PolicyRuleConditionInputToJSONTyped(value?: PolicyRuleConditionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match': MatchToJSON(value['match']),
    };
}

