/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PolicyNeedingUpdate
 */
export interface PolicyNeedingUpdate {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
}

/**
 * Check if a given object implements the PolicyNeedingUpdate interface.
 */
export function instanceOfPolicyNeedingUpdate(value: object): value is PolicyNeedingUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PolicyNeedingUpdateFromJSON(json: any): PolicyNeedingUpdate {
    return PolicyNeedingUpdateFromJSONTyped(json, false);
}

export function PolicyNeedingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyNeedingUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PolicyNeedingUpdateToJSON(json: any): PolicyNeedingUpdate {
    return PolicyNeedingUpdateToJSONTyped(json, false);
}

export function PolicyNeedingUpdateToJSONTyped(value?: PolicyNeedingUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

