/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which way a policy leans when the router is genuinely unsure.
 * 
 * Passed to the router as an instruction, not as a separate code path — there
 * is one picker, and posture only shifts how it resolves uncertainty. It never
 * overrides a rule floor, a rule ban, or the caller's model access; those are
 * applied in code afterwards.
 * @export
 */
export const Posture = {
    Savings: 'savings',
    Balanced: 'balanced',
    Quality: 'quality',
} as const;
export type Posture = typeof Posture[keyof typeof Posture];


export function instanceOfPosture(value: any): boolean {
    for (const key in Posture) {
        if (Object.prototype.hasOwnProperty.call(Posture, key)) {
            if (Posture[key as keyof typeof Posture] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PostureFromJSON(json: any): Posture {
    return PostureFromJSONTyped(json, false);
}

export function PostureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Posture {
    return json as Posture;
}

export function PostureToJSON(value?: Posture | null): any {
    return value as any;
}

export function PostureToJSONTyped(value: any, ignoreDiscriminator: boolean): Posture {
    return value as Posture;
}

