/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Per-row sync behavior. Stored as a `VARCHAR(16)` constrained to
 * `tracking | pinned | auto` (see migration V33).
 * @export
 */
export const PricingSyncMode = {
    Tracking: 'tracking',
    Pinned: 'pinned',
    Auto: 'auto',
} as const;
export type PricingSyncMode = typeof PricingSyncMode[keyof typeof PricingSyncMode];


export function instanceOfPricingSyncMode(value: any): boolean {
    for (const key in PricingSyncMode) {
        if (Object.prototype.hasOwnProperty.call(PricingSyncMode, key)) {
            if (PricingSyncMode[key as keyof typeof PricingSyncMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PricingSyncModeFromJSON(json: any): PricingSyncMode {
    return PricingSyncModeFromJSONTyped(json, false);
}

export function PricingSyncModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingSyncMode {
    return json as PricingSyncMode;
}

export function PricingSyncModeToJSON(value?: PricingSyncMode | null): any {
    return value as any;
}

export function PricingSyncModeToJSONTyped(value: any, ignoreDiscriminator: boolean): PricingSyncMode {
    return value as PricingSyncMode;
}

