/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProviderConnectionResponseOneOf2
 */
export interface ProviderConnectionResponseOneOf2 {
    /**
     * 
     */
    accessKeyId?: string;
    /**
     * 
     */
    authType: string;
    /**
     * 
     */
    endpoint?: string;
    /**
     * 
     */
    externalId?: string;
    /**
     * 
     */
    hasCredentials: boolean;
    /**
     * 
     */
    iamRoleArn?: string;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    region: string;
    /**
     * 
     */
    provider: ProviderConnectionResponseOneOf2ProviderEnum;
}


/**
 * @export
 */
export const ProviderConnectionResponseOneOf2ProviderEnum = {
    AwsComprehendPii: 'aws_comprehend_pii',
} as const;
export type ProviderConnectionResponseOneOf2ProviderEnum = typeof ProviderConnectionResponseOneOf2ProviderEnum[keyof typeof ProviderConnectionResponseOneOf2ProviderEnum];


/**
 * Check if a given object implements the ProviderConnectionResponseOneOf2 interface.
 */
export function instanceOfProviderConnectionResponseOneOf2(value: object): value is ProviderConnectionResponseOneOf2 {
    if ((!('authType' in (value as Record<string, any>)) && !('auth_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['authType'] === undefined && (value as Record<string, any>)['auth_type'] === undefined)) return false;
    if ((!('hasCredentials' in (value as Record<string, any>)) && !('has_credentials' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasCredentials'] === undefined && (value as Record<string, any>)['has_credentials'] === undefined)) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'aws_comprehend_pii') return false;
    
    return true;
}

export function ProviderConnectionResponseOneOf2FromJSON(json: any): ProviderConnectionResponseOneOf2 {
    return ProviderConnectionResponseOneOf2FromJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderConnectionResponseOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'] == null ? undefined : json['access_key_id'],
        'authType': json['auth_type'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'hasCredentials': json['has_credentials'],
        'iamRoleArn': json['iam_role_arn'] == null ? undefined : json['iam_role_arn'],
        'language': json['language'],
        'orgId': json['org_id'],
        'region': json['region'],
        'provider': json['provider'],
    };
}

export function ProviderConnectionResponseOneOf2ToJSON(json: any): ProviderConnectionResponseOneOf2 {
    return ProviderConnectionResponseOneOf2ToJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf2ToJSONTyped(value?: ProviderConnectionResponseOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'auth_type': value['authType'],
        'endpoint': value['endpoint'],
        'external_id': value['externalId'],
        'has_credentials': value['hasCredentials'],
        'iam_role_arn': value['iamRoleArn'],
        'language': value['language'],
        'org_id': value['orgId'],
        'region': value['region'],
        'provider': value['provider'],
    };
}

