/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProviderConnectionResponseOneOf1
 */
export interface ProviderConnectionResponseOneOf1 {
    /**
     * 
     */
    endpoint: string;
    /**
     * Whether a bearer token is configured. The token value is never returned.
     */
    hasBearerToken: boolean;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    provider: ProviderConnectionResponseOneOf1ProviderEnum;
}


/**
 * @export
 */
export const ProviderConnectionResponseOneOf1ProviderEnum = {
    Tokenization: 'tokenization',
} as const;
export type ProviderConnectionResponseOneOf1ProviderEnum = typeof ProviderConnectionResponseOneOf1ProviderEnum[keyof typeof ProviderConnectionResponseOneOf1ProviderEnum];


/**
 * Check if a given object implements the ProviderConnectionResponseOneOf1 interface.
 */
export function instanceOfProviderConnectionResponseOneOf1(value: object): value is ProviderConnectionResponseOneOf1 {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if ((!('hasBearerToken' in (value as Record<string, any>)) && !('has_bearer_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasBearerToken'] === undefined && (value as Record<string, any>)['has_bearer_token'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'tokenization') return false;
    
    return true;
}

export function ProviderConnectionResponseOneOf1FromJSON(json: any): ProviderConnectionResponseOneOf1 {
    return ProviderConnectionResponseOneOf1FromJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderConnectionResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
        'hasBearerToken': json['has_bearer_token'],
        'orgId': json['org_id'],
        'provider': json['provider'],
    };
}

export function ProviderConnectionResponseOneOf1ToJSON(json: any): ProviderConnectionResponseOneOf1 {
    return ProviderConnectionResponseOneOf1ToJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf1ToJSONTyped(value?: ProviderConnectionResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'has_bearer_token': value['hasBearerToken'],
        'org_id': value['orgId'],
        'provider': value['provider'],
    };
}

