/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProviderConnectionResponseOneOf4
 */
export interface ProviderConnectionResponseOneOf4 {
    /**
     * 
     */
    accessKeyId?: string;
    /**
     * 
     */
    authType: string;
    /**
     * 
     */
    endpoint?: string;
    /**
     * 
     */
    externalId?: string;
    /**
     * 
     */
    guardrailIdentifier: string;
    /**
     * 
     */
    guardrailVersion: string;
    /**
     * 
     */
    hasCredentials: boolean;
    /**
     * 
     */
    iamRoleArn?: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    region: string;
    /**
     * 
     */
    provider: ProviderConnectionResponseOneOf4ProviderEnum;
}


/**
 * @export
 */
export const ProviderConnectionResponseOneOf4ProviderEnum = {
    AwsBedrockGuardrails: 'aws_bedrock_guardrails',
} as const;
export type ProviderConnectionResponseOneOf4ProviderEnum = typeof ProviderConnectionResponseOneOf4ProviderEnum[keyof typeof ProviderConnectionResponseOneOf4ProviderEnum];


/**
 * Check if a given object implements the ProviderConnectionResponseOneOf4 interface.
 */
export function instanceOfProviderConnectionResponseOneOf4(value: object): value is ProviderConnectionResponseOneOf4 {
    if ((!('authType' in (value as Record<string, any>)) && !('auth_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['authType'] === undefined && (value as Record<string, any>)['auth_type'] === undefined)) return false;
    if ((!('guardrailIdentifier' in (value as Record<string, any>)) && !('guardrail_identifier' in (value as Record<string, any>))) || ((value as Record<string, any>)['guardrailIdentifier'] === undefined && (value as Record<string, any>)['guardrail_identifier'] === undefined)) return false;
    if ((!('guardrailVersion' in (value as Record<string, any>)) && !('guardrail_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['guardrailVersion'] === undefined && (value as Record<string, any>)['guardrail_version'] === undefined)) return false;
    if ((!('hasCredentials' in (value as Record<string, any>)) && !('has_credentials' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasCredentials'] === undefined && (value as Record<string, any>)['has_credentials'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'aws_bedrock_guardrails') return false;
    
    return true;
}

export function ProviderConnectionResponseOneOf4FromJSON(json: any): ProviderConnectionResponseOneOf4 {
    return ProviderConnectionResponseOneOf4FromJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderConnectionResponseOneOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'] == null ? undefined : json['access_key_id'],
        'authType': json['auth_type'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'guardrailIdentifier': json['guardrail_identifier'],
        'guardrailVersion': json['guardrail_version'],
        'hasCredentials': json['has_credentials'],
        'iamRoleArn': json['iam_role_arn'] == null ? undefined : json['iam_role_arn'],
        'orgId': json['org_id'],
        'region': json['region'],
        'provider': json['provider'],
    };
}

export function ProviderConnectionResponseOneOf4ToJSON(json: any): ProviderConnectionResponseOneOf4 {
    return ProviderConnectionResponseOneOf4ToJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOf4ToJSONTyped(value?: ProviderConnectionResponseOneOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'auth_type': value['authType'],
        'endpoint': value['endpoint'],
        'external_id': value['externalId'],
        'guardrail_identifier': value['guardrailIdentifier'],
        'guardrail_version': value['guardrailVersion'],
        'has_credentials': value['hasCredentials'],
        'iam_role_arn': value['iamRoleArn'],
        'org_id': value['orgId'],
        'region': value['region'],
        'provider': value['provider'],
    };
}

