/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProviderConnectionResponseOneOf
 */
export interface ProviderConnectionResponseOneOf {
    /**
     * 
     */
    analyzerUrl: string;
    /**
     * 
     */
    anonymizerUrl: string;
    /**
     * Whether a bearer token is configured. The token value is never returned.
     */
    hasBearerToken: boolean;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    provider: ProviderConnectionResponseOneOfProviderEnum;
}


/**
 * @export
 */
export const ProviderConnectionResponseOneOfProviderEnum = {
    Presidio: 'presidio',
} as const;
export type ProviderConnectionResponseOneOfProviderEnum = typeof ProviderConnectionResponseOneOfProviderEnum[keyof typeof ProviderConnectionResponseOneOfProviderEnum];


/**
 * Check if a given object implements the ProviderConnectionResponseOneOf interface.
 */
export function instanceOfProviderConnectionResponseOneOf(value: object): value is ProviderConnectionResponseOneOf {
    if ((!('analyzerUrl' in (value as Record<string, any>)) && !('analyzer_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['analyzerUrl'] === undefined && (value as Record<string, any>)['analyzer_url'] === undefined)) return false;
    if ((!('anonymizerUrl' in (value as Record<string, any>)) && !('anonymizer_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['anonymizerUrl'] === undefined && (value as Record<string, any>)['anonymizer_url'] === undefined)) return false;
    if ((!('hasBearerToken' in (value as Record<string, any>)) && !('has_bearer_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasBearerToken'] === undefined && (value as Record<string, any>)['has_bearer_token'] === undefined)) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'presidio') return false;
    
    return true;
}

export function ProviderConnectionResponseOneOfFromJSON(json: any): ProviderConnectionResponseOneOf {
    return ProviderConnectionResponseOneOfFromJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderConnectionResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'analyzerUrl': json['analyzer_url'],
        'anonymizerUrl': json['anonymizer_url'],
        'hasBearerToken': json['has_bearer_token'],
        'language': json['language'],
        'orgId': json['org_id'],
        'provider': json['provider'],
    };
}

export function ProviderConnectionResponseOneOfToJSON(json: any): ProviderConnectionResponseOneOf {
    return ProviderConnectionResponseOneOfToJSONTyped(json, false);
}

export function ProviderConnectionResponseOneOfToJSONTyped(value?: ProviderConnectionResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analyzer_url': value['analyzerUrl'],
        'anonymizer_url': value['anonymizerUrl'],
        'has_bearer_token': value['hasBearerToken'],
        'language': value['language'],
        'org_id': value['orgId'],
        'provider': value['provider'],
    };
}

