/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentRuntimeCapabilities } from './AgentRuntimeCapabilities.js';
import {
    AgentRuntimeCapabilitiesFromJSON,
    AgentRuntimeCapabilitiesFromJSONTyped,
    AgentRuntimeCapabilitiesToJSON,
    AgentRuntimeCapabilitiesToJSONTyped,
} from './AgentRuntimeCapabilities.js';

/**
 * 
 * @export
 * @interface PutClientSettingsRequest
 */
export interface PutClientSettingsRequest {
    /**
     * 
     */
    capabilities: AgentRuntimeCapabilities;
    /**
     * Any subset of the client's slot keys (possibly empty). Each value is a
     * single Model Route or routing-policy alias.
     */
    preferences?: { [key: string]: string; };
}

/**
 * Check if a given object implements the PutClientSettingsRequest interface.
 */
export function instanceOfPutClientSettingsRequest(value: object): value is PutClientSettingsRequest {
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    return true;
}

export function PutClientSettingsRequestFromJSON(json: any): PutClientSettingsRequest {
    return PutClientSettingsRequestFromJSONTyped(json, false);
}

export function PutClientSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutClientSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'capabilities': AgentRuntimeCapabilitiesFromJSON(json['capabilities']),
        'preferences': json['preferences'] == null ? undefined : json['preferences'],
    };
}

export function PutClientSettingsRequestToJSON(json: any): PutClientSettingsRequest {
    return PutClientSettingsRequestToJSONTyped(json, false);
}

export function PutClientSettingsRequestToJSONTyped(value?: PutClientSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capabilities': AgentRuntimeCapabilitiesToJSON(value['capabilities']),
        'preferences': value['preferences'],
    };
}

