/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * `POST /admin/model-routes/rename`: rename a route in one step — every
 * target, and the route's route-group memberships with it (BCP-4580).
 * @export
 * @interface RenameModelRouteRequest
 */
export interface RenameModelRouteRequest {
    /**
     * Optional note explaining the rename (BCP-3998), stamped on every target.
     */
    changeNote?: string | null;
    /**
     * The route's current name.
     */
    modelAlias: string;
    /**
     * The new name. Any name no other route uses, including the name of a
     * model one of its targets points at.
     */
    newModelAlias: string;
}

/**
 * Check if a given object implements the RenameModelRouteRequest interface.
 */
export function instanceOfRenameModelRouteRequest(value: object): value is RenameModelRouteRequest {
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if ((!('newModelAlias' in (value as Record<string, any>)) && !('new_model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['newModelAlias'] === undefined && (value as Record<string, any>)['new_model_alias'] === undefined)) return false;
    return true;
}

export function RenameModelRouteRequestFromJSON(json: any): RenameModelRouteRequest {
    return RenameModelRouteRequestFromJSONTyped(json, false);
}

export function RenameModelRouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameModelRouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'modelAlias': json['model_alias'],
        'newModelAlias': json['new_model_alias'],
    };
}

export function RenameModelRouteRequestToJSON(json: any): RenameModelRouteRequest {
    return RenameModelRouteRequestToJSONTyped(json, false);
}

export function RenameModelRouteRequestToJSONTyped(value?: RenameModelRouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'model_alias': value['modelAlias'],
        'new_model_alias': value['newModelAlias'],
    };
}

