/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * `PUT /admin/model-mappings/reorder` acknowledgement.
 * @export
 * @interface ReorderedResponse
 */
export interface ReorderedResponse {
    /**
     * Always true.
     */
    ok: boolean;
}

/**
 * Check if a given object implements the ReorderedResponse interface.
 */
export function instanceOfReorderedResponse(value: object): value is ReorderedResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function ReorderedResponseFromJSON(json: any): ReorderedResponse {
    return ReorderedResponseFromJSONTyped(json, false);
}

export function ReorderedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
    };
}

export function ReorderedResponseToJSON(json: any): ReorderedResponse {
    return ReorderedResponseToJSONTyped(json, false);
}

export function ReorderedResponseToJSONTyped(value?: ReorderedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

