/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ReorderEntry } from './ReorderEntry.js';
import {
    ReorderEntryFromJSON,
    ReorderEntryFromJSONTyped,
    ReorderEntryToJSON,
    ReorderEntryToJSONTyped,
} from './ReorderEntry.js';

/**
 * 
 * @export
 * @interface ReorderModelMappingsRequest
 */
export interface ReorderModelMappingsRequest {
    /**
     * 
     */
    entries: Array<ReorderEntry>;
}

/**
 * Check if a given object implements the ReorderModelMappingsRequest interface.
 */
export function instanceOfReorderModelMappingsRequest(value: object): value is ReorderModelMappingsRequest {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function ReorderModelMappingsRequestFromJSON(json: any): ReorderModelMappingsRequest {
    return ReorderModelMappingsRequestFromJSONTyped(json, false);
}

export function ReorderModelMappingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderModelMappingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(ReorderEntryFromJSON)),
    };
}

export function ReorderModelMappingsRequestToJSON(json: any): ReorderModelMappingsRequest {
    return ReorderModelMappingsRequestToJSONTyped(json, false);
}

export function ReorderModelMappingsRequestToJSONTyped(value?: ReorderModelMappingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(ReorderEntryToJSON)),
    };
}

