/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PolicyAttributionResponse } from './PolicyAttributionResponse.js';
import {
    PolicyAttributionResponseFromJSON,
    PolicyAttributionResponseFromJSONTyped,
    PolicyAttributionResponseToJSON,
    PolicyAttributionResponseToJSONTyped,
} from './PolicyAttributionResponse.js';

/**
 * 
 * @export
 * @interface ResolvedProtectionRuleResponse
 */
export interface ResolvedProtectionRuleResponse {
    /**
     * 
     */
    actionScope: string;
    /**
     * 
     */
    attribution: PolicyAttributionResponse;
    /**
     * 
     */
    conditionEquals?: string | null;
    /**
     * 
     */
    conditionFieldPath?: string | null;
    /**
     * 
     */
    detectionEngineId?: string | null;
    /**
     * 
     */
    detectionEngineName?: string | null;
    /**
     * 
     */
    detectionType: string;
    /**
     * 
     */
    dryRun: boolean;
    /**
     * 
     */
    effectiveAction: string;
    /**
     * 
     */
    minConfidence: string;
    /**
     * 
     */
    policyId?: string | null;
    /**
     * 
     */
    runtimeStage: string;
    /**
     * 
     */
    targetFieldPath?: string | null;
    /**
     * 
     */
    toolName?: string | null;
    /**
     * 
     */
    toolNames?: Array<string>;
}

/**
 * Check if a given object implements the ResolvedProtectionRuleResponse interface.
 */
export function instanceOfResolvedProtectionRuleResponse(value: object): value is ResolvedProtectionRuleResponse {
    if ((!('actionScope' in (value as Record<string, any>)) && !('action_scope' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionScope'] === undefined && (value as Record<string, any>)['action_scope'] === undefined)) return false;
    if (!('attribution' in value) || value['attribution'] === undefined) return false;
    if ((!('detectionType' in (value as Record<string, any>)) && !('detection_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['detectionType'] === undefined && (value as Record<string, any>)['detection_type'] === undefined)) return false;
    if ((!('dryRun' in (value as Record<string, any>)) && !('dry_run' in (value as Record<string, any>))) || ((value as Record<string, any>)['dryRun'] === undefined && (value as Record<string, any>)['dry_run'] === undefined)) return false;
    if ((!('effectiveAction' in (value as Record<string, any>)) && !('effective_action' in (value as Record<string, any>))) || ((value as Record<string, any>)['effectiveAction'] === undefined && (value as Record<string, any>)['effective_action'] === undefined)) return false;
    if ((!('minConfidence' in (value as Record<string, any>)) && !('min_confidence' in (value as Record<string, any>))) || ((value as Record<string, any>)['minConfidence'] === undefined && (value as Record<string, any>)['min_confidence'] === undefined)) return false;
    if ((!('runtimeStage' in (value as Record<string, any>)) && !('runtime_stage' in (value as Record<string, any>))) || ((value as Record<string, any>)['runtimeStage'] === undefined && (value as Record<string, any>)['runtime_stage'] === undefined)) return false;
    return true;
}

export function ResolvedProtectionRuleResponseFromJSON(json: any): ResolvedProtectionRuleResponse {
    return ResolvedProtectionRuleResponseFromJSONTyped(json, false);
}

export function ResolvedProtectionRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedProtectionRuleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actionScope': json['action_scope'],
        'attribution': PolicyAttributionResponseFromJSON(json['attribution']),
        'conditionEquals': json['condition_equals'] === undefined ? undefined : json['condition_equals'] === null ? null : json['condition_equals'],
        'conditionFieldPath': json['condition_field_path'] === undefined ? undefined : json['condition_field_path'] === null ? null : json['condition_field_path'],
        'detectionEngineId': json['detection_engine_id'] === undefined ? undefined : json['detection_engine_id'] === null ? null : json['detection_engine_id'],
        'detectionEngineName': json['detection_engine_name'] === undefined ? undefined : json['detection_engine_name'] === null ? null : json['detection_engine_name'],
        'detectionType': json['detection_type'],
        'dryRun': json['dry_run'],
        'effectiveAction': json['effective_action'],
        'minConfidence': json['min_confidence'],
        'policyId': json['policy_id'] === undefined ? undefined : json['policy_id'] === null ? null : json['policy_id'],
        'runtimeStage': json['runtime_stage'],
        'targetFieldPath': json['target_field_path'] === undefined ? undefined : json['target_field_path'] === null ? null : json['target_field_path'],
        'toolName': json['tool_name'] === undefined ? undefined : json['tool_name'] === null ? null : json['tool_name'],
        'toolNames': json['tool_names'] == null ? undefined : json['tool_names'],
    };
}

export function ResolvedProtectionRuleResponseToJSON(json: any): ResolvedProtectionRuleResponse {
    return ResolvedProtectionRuleResponseToJSONTyped(json, false);
}

export function ResolvedProtectionRuleResponseToJSONTyped(value?: ResolvedProtectionRuleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_scope': value['actionScope'],
        'attribution': PolicyAttributionResponseToJSON(value['attribution']),
        'condition_equals': value['conditionEquals'],
        'condition_field_path': value['conditionFieldPath'],
        'detection_engine_id': value['detectionEngineId'],
        'detection_engine_name': value['detectionEngineName'],
        'detection_type': value['detectionType'],
        'dry_run': value['dryRun'],
        'effective_action': value['effectiveAction'],
        'min_confidence': value['minConfidence'],
        'policy_id': value['policyId'],
        'runtime_stage': value['runtimeStage'],
        'target_field_path': value['targetFieldPath'],
        'tool_name': value['toolName'],
        'tool_names': value['toolNames'],
    };
}

