/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Aligns with design §4 — only two ref types are ever stored.
 * @export
 * @interface ResolvedRef
 */
export interface ResolvedRef {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    type: ResolvedRefTypeEnum;
}


/**
 * @export
 */
export const ResolvedRefTypeEnum = {
    McpServer: 'mcp_server',
    Application: 'application',
} as const;
export type ResolvedRefTypeEnum = typeof ResolvedRefTypeEnum[keyof typeof ResolvedRefTypeEnum];


/**
 * Check if a given object implements the ResolvedRef interface.
 */
export function instanceOfResolvedRef(value: object): value is ResolvedRef {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResolvedRefFromJSON(json: any): ResolvedRef {
    return ResolvedRefFromJSONTyped(json, false);
}

export function ResolvedRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedRef {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
    };
}

export function ResolvedRefToJSON(json: any): ResolvedRef {
    return ResolvedRefToJSONTyped(json, false);
}

export function ResolvedRefToJSONTyped(value?: ResolvedRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
    };
}

