/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RoutingSlot
 */
export interface RoutingSlot {
    /**
     * Free-text routing guidance shown to the determiner — e.g. "code and
     * debugging" or "long-form writing". Helps the determiner pick this slot
     * by purpose, not just by index/label. Stored inside the `slots` JSONB,
     * so no column/migration is needed.
     */
    description?: string | null;
    /**
     * 
     */
    label?: string | null;
    /**
     * 
     */
    modelAlias: string;
}

/**
 * Check if a given object implements the RoutingSlot interface.
 */
export function instanceOfRoutingSlot(value: object): value is RoutingSlot {
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    return true;
}

export function RoutingSlotFromJSON(json: any): RoutingSlot {
    return RoutingSlotFromJSONTyped(json, false);
}

export function RoutingSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingSlot {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'label': json['label'] === undefined ? undefined : json['label'] === null ? null : json['label'],
        'modelAlias': json['model_alias'],
    };
}

export function RoutingSlotToJSON(json: any): RoutingSlot {
    return RoutingSlotToJSONTyped(json, false);
}

export function RoutingSlotToJSONTyped(value?: RoutingSlot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'label': value['label'],
        'model_alias': value['modelAlias'],
    };
}

