/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { RoutingSlot } from './RoutingSlot.js';
import {
    RoutingSlotFromJSON,
    RoutingSlotFromJSONTyped,
    RoutingSlotToJSON,
    RoutingSlotToJSONTyped,
} from './RoutingSlot.js';
import type { Posture } from './Posture.js';
import {
    PostureFromJSON,
    PostureFromJSONTyped,
    PostureToJSON,
    PostureToJSONTyped,
} from './Posture.js';

/**
 * 
 * @export
 * @interface RoutingPolicy
 */
export interface RoutingPolicy {
    /**
     * 
     */
    contextBreakpoints: Array<number>;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    defaultSlotOnFailure: number;
    /**
     * 
     */
    description?: string | null;
    /**
     * The LLM that picks a slot. Optional because a policy may be saved before
     * one is chosen; the picker falls back to the context-size floor when it
     * is absent.
     */
    determinerModelAlias?: string | null;
    /**
     * Optional override for the determiner's instruction preamble. `None`
     * (or empty) falls back to the built-in default (see `routing::determiner`).
     * The slot catalog, request-metadata block, and JSON-output schema are
     * always appended by the gateway so the structured-output contract holds
     * regardless of what an admin writes here.
     */
    determinerPrompt?: string | null;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    modelAlias: string;
    /**
     * 
     */
    orgId: string;
    /**
     * How eagerly this policy steps up when the router is unsure.
     */
    posture: Posture;
    /**
     * 
     */
    routerInputMaxChars: number;
    /**
     * 
     */
    slots: Array<RoutingSlot>;
    /**
     * 
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the RoutingPolicy interface.
 */
export function instanceOfRoutingPolicy(value: object): value is RoutingPolicy {
    if ((!('contextBreakpoints' in (value as Record<string, any>)) && !('context_breakpoints' in (value as Record<string, any>))) || ((value as Record<string, any>)['contextBreakpoints'] === undefined && (value as Record<string, any>)['context_breakpoints'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('defaultSlotOnFailure' in (value as Record<string, any>)) && !('default_slot_on_failure' in (value as Record<string, any>))) || ((value as Record<string, any>)['defaultSlotOnFailure'] === undefined && (value as Record<string, any>)['default_slot_on_failure'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('posture' in value) || value['posture'] === undefined) return false;
    if ((!('routerInputMaxChars' in (value as Record<string, any>)) && !('router_input_max_chars' in (value as Record<string, any>))) || ((value as Record<string, any>)['routerInputMaxChars'] === undefined && (value as Record<string, any>)['router_input_max_chars'] === undefined)) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function RoutingPolicyFromJSON(json: any): RoutingPolicy {
    return RoutingPolicyFromJSONTyped(json, false);
}

export function RoutingPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'contextBreakpoints': json['context_breakpoints'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'defaultSlotOnFailure': json['default_slot_on_failure'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'determinerModelAlias': json['determiner_model_alias'] === undefined ? undefined : json['determiner_model_alias'] === null ? null : json['determiner_model_alias'],
        'determinerPrompt': json['determiner_prompt'] === undefined ? undefined : json['determiner_prompt'] === null ? null : json['determiner_prompt'],
        'enabled': json['enabled'],
        'id': json['id'],
        'modelAlias': json['model_alias'],
        'orgId': json['org_id'],
        'posture': PostureFromJSON(json['posture']),
        'routerInputMaxChars': json['router_input_max_chars'],
        'slots': ((json['slots'] as Array<any>).map(RoutingSlotFromJSON)),
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function RoutingPolicyToJSON(json: any): RoutingPolicy {
    return RoutingPolicyToJSONTyped(json, false);
}

export function RoutingPolicyToJSONTyped(value?: RoutingPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context_breakpoints': value['contextBreakpoints'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'default_slot_on_failure': value['defaultSlotOnFailure'],
        'description': value['description'],
        'determiner_model_alias': value['determinerModelAlias'],
        'determiner_prompt': value['determinerPrompt'],
        'enabled': value['enabled'],
        'id': value['id'],
        'model_alias': value['modelAlias'],
        'org_id': value['orgId'],
        'posture': PostureToJSON(value['posture']),
        'router_input_max_chars': value['routerInputMaxChars'],
        'slots': ((value['slots'] as Array<any>).map(RoutingSlotToJSON)),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

