/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { RoutingSlot } from './RoutingSlot.js';
import {
    RoutingSlotFromJSON,
    RoutingSlotFromJSONTyped,
    RoutingSlotToJSON,
    RoutingSlotToJSONTyped,
} from './RoutingSlot.js';
import type { Posture } from './Posture.js';
import {
    PostureFromJSON,
    PostureFromJSONTyped,
    PostureToJSON,
    PostureToJSONTyped,
} from './Posture.js';

/**
 * 
 * @export
 * @interface RoutingPolicyDraft
 */
export interface RoutingPolicyDraft {
    /**
     * 
     */
    contextBreakpoints?: Array<number>;
    /**
     * 
     */
    defaultSlotOnFailure?: number;
    /**
     * 
     */
    description?: string | null;
    /**
     * 
     */
    determinerModelAlias?: string | null;
    /**
     * 
     */
    determinerPrompt?: string | null;
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    modelAlias: string;
    /**
     * 
     */
    posture?: Posture;
    /**
     * 
     */
    routerInputMaxChars?: number;
    /**
     * 
     */
    slots: Array<RoutingSlot>;
}



/**
 * Check if a given object implements the RoutingPolicyDraft interface.
 */
export function instanceOfRoutingPolicyDraft(value: object): value is RoutingPolicyDraft {
    if ((!('modelAlias' in (value as Record<string, any>)) && !('model_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelAlias'] === undefined && (value as Record<string, any>)['model_alias'] === undefined)) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    return true;
}

export function RoutingPolicyDraftFromJSON(json: any): RoutingPolicyDraft {
    return RoutingPolicyDraftFromJSONTyped(json, false);
}

export function RoutingPolicyDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingPolicyDraft {
    if (json == null) {
        return json;
    }
    return {
        
        'contextBreakpoints': json['context_breakpoints'] == null ? undefined : json['context_breakpoints'],
        'defaultSlotOnFailure': json['default_slot_on_failure'] == null ? undefined : json['default_slot_on_failure'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'determinerModelAlias': json['determiner_model_alias'] === undefined ? undefined : json['determiner_model_alias'] === null ? null : json['determiner_model_alias'],
        'determinerPrompt': json['determiner_prompt'] === undefined ? undefined : json['determiner_prompt'] === null ? null : json['determiner_prompt'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'modelAlias': json['model_alias'],
        'posture': json['posture'] == null ? undefined : PostureFromJSON(json['posture']),
        'routerInputMaxChars': json['router_input_max_chars'] == null ? undefined : json['router_input_max_chars'],
        'slots': ((json['slots'] as Array<any>).map(RoutingSlotFromJSON)),
    };
}

export function RoutingPolicyDraftToJSON(json: any): RoutingPolicyDraft {
    return RoutingPolicyDraftToJSONTyped(json, false);
}

export function RoutingPolicyDraftToJSONTyped(value?: RoutingPolicyDraft | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context_breakpoints': value['contextBreakpoints'],
        'default_slot_on_failure': value['defaultSlotOnFailure'],
        'description': value['description'],
        'determiner_model_alias': value['determinerModelAlias'],
        'determiner_prompt': value['determinerPrompt'],
        'enabled': value['enabled'],
        'model_alias': value['modelAlias'],
        'posture': PostureToJSON(value['posture']),
        'router_input_max_chars': value['routerInputMaxChars'],
        'slots': ((value['slots'] as Array<any>).map(RoutingSlotToJSON)),
    };
}

