/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * What an admin sends to create or replace a rule.
 * @export
 * @interface RoutingRuleDraft
 */
export interface RoutingRuleDraft {
    /**
     * 
     */
    denySlots?: Array<number>;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    enabled?: boolean;
    /**
     * 
     */
    floorSlot?: number | null;
    /**
     * 
     */
    name: string;
}

/**
 * Check if a given object implements the RoutingRuleDraft interface.
 */
export function instanceOfRoutingRuleDraft(value: object): value is RoutingRuleDraft {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoutingRuleDraftFromJSON(json: any): RoutingRuleDraft {
    return RoutingRuleDraftFromJSONTyped(json, false);
}

export function RoutingRuleDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingRuleDraft {
    if (json == null) {
        return json;
    }
    return {
        
        'denySlots': json['deny_slots'] == null ? undefined : json['deny_slots'],
        'description': json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'floorSlot': json['floor_slot'] === undefined ? undefined : json['floor_slot'] === null ? null : json['floor_slot'],
        'name': json['name'],
    };
}

export function RoutingRuleDraftToJSON(json: any): RoutingRuleDraft {
    return RoutingRuleDraftToJSONTyped(json, false);
}

export function RoutingRuleDraftToJSONTyped(value?: RoutingRuleDraft | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deny_slots': value['denySlots'],
        'description': value['description'],
        'enabled': value['enabled'],
        'floor_slot': value['floorSlot'],
        'name': value['name'],
    };
}

