/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * Public service-connection shape exposed from server endpoints.
 * @export
 * @interface ServerConnectionResponse
 */
export interface ServerConnectionResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    mcpServerId: string;
    /**
     * 
     */
    userId?: string | null;
    /**
     * 
     */
    applicationId?: string | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    errorMessage?: string | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    connectedAt?: Date | null;
    /**
     * 
     */
    lastAccessedAt?: Date | null;
    /**
     * 
     */
    connectedByUserId?: string | null;
    /**
     * 
     */
    accountEmail?: string | null;
}

/**
 * Check if a given object implements the ServerConnectionResponse interface.
 */
export function instanceOfServerConnectionResponse(value: object): value is ServerConnectionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('mcpServerId' in (value as Record<string, any>)) && !('mcp_server_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerId'] === undefined && (value as Record<string, any>)['mcp_server_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function ServerConnectionResponseFromJSON(json: any): ServerConnectionResponse {
    return ServerConnectionResponseFromJSONTyped(json, false);
}

export function ServerConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mcpServerId': json['mcp_server_id'],
        'userId': json['user_id'] === undefined ? undefined : json['user_id'] === null ? null : json['user_id'],
        'applicationId': json['application_id'] === undefined ? undefined : json['application_id'] === null ? null : json['application_id'],
        'status': json['status'],
        'errorMessage': json['error_message'] === undefined ? undefined : json['error_message'] === null ? null : json['error_message'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'connectedAt': json['connected_at'] === undefined ? undefined : json['connected_at'] === null ? null : (parseDateTime(json['connected_at'])),
        'lastAccessedAt': json['last_accessed_at'] === undefined ? undefined : json['last_accessed_at'] === null ? null : (parseDateTime(json['last_accessed_at'])),
        'connectedByUserId': json['connected_by_user_id'] === undefined ? undefined : json['connected_by_user_id'] === null ? null : json['connected_by_user_id'],
        'accountEmail': json['account_email'] === undefined ? undefined : json['account_email'] === null ? null : json['account_email'],
    };
}

export function ServerConnectionResponseToJSON(json: any): ServerConnectionResponse {
    return ServerConnectionResponseToJSONTyped(json, false);
}

export function ServerConnectionResponseToJSONTyped(value?: ServerConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mcp_server_id': value['mcpServerId'],
        'user_id': value['userId'],
        'application_id': value['applicationId'],
        'status': value['status'],
        'error_message': value['errorMessage'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'connected_at': value['connectedAt'] == null ? value['connectedAt'] : serializeDateTime(value['connectedAt']),
        'last_accessed_at': value['lastAccessedAt'] == null ? value['lastAccessedAt'] : serializeDateTime(value['lastAccessedAt']),
        'connected_by_user_id': value['connectedByUserId'],
        'account_email': value['accountEmail'],
    };
}

