/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { MCPServerDirectoryBase } from './MCPServerDirectoryBase.js';
import {
    MCPServerDirectoryBaseFromJSON,
    MCPServerDirectoryBaseFromJSONTyped,
    MCPServerDirectoryBaseToJSON,
    MCPServerDirectoryBaseToJSONTyped,
} from './MCPServerDirectoryBase.js';
import type { AttentionTier } from './AttentionTier.js';
import {
    AttentionTierFromJSON,
    AttentionTierFromJSONTyped,
    AttentionTierToJSON,
    AttentionTierToJSONTyped,
} from './AttentionTier.js';
import type { ConnectionStatus } from './ConnectionStatus.js';
import {
    ConnectionStatusFromJSON,
    ConnectionStatusFromJSONTyped,
    ConnectionStatusToJSON,
    ConnectionStatusToJSONTyped,
} from './ConnectionStatus.js';
import type { ServerConnectionResponse } from './ServerConnectionResponse.js';
import {
    ServerConnectionResponseFromJSON,
    ServerConnectionResponseFromJSONTyped,
    ServerConnectionResponseToJSON,
    ServerConnectionResponseToJSONTyped,
} from './ServerConnectionResponse.js';
import type { PublishBlocker } from './PublishBlocker.js';
import {
    PublishBlockerFromJSON,
    PublishBlockerFromJSONTyped,
    PublishBlockerToJSON,
    PublishBlockerToJSONTyped,
} from './PublishBlocker.js';

/**
 * Response model for MCP server with computed fields.
 * 
 * This model includes both database fields and computed fields like
 * connection_status, url, and proxy_url that are added at runtime.
 * @export
 * @interface ServerResponse
 */
export interface ServerResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    oauthBaseUrlOverride: string | null;
    /**
     * 
     */
    clientId: string | null;
    /**
     * 
     */
    clientSecret: string | null;
    /**
     * 
     */
    usesManagedCredentials: boolean | null;
    /**
     * 
     */
    scopes: Array<string> | null;
    /**
     * 
     */
    organizationId: string | null;
    /**
     * 
     */
    mcpServerDirectoryId: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    meta: any | null;
    /**
     * 
     */
    toolsFetchStatus: string;
    /**
     * 
     */
    toolsFetchError: any | null;
    /**
     * 
     */
    toolsFetchedAt: Date | null;
    /**
     * 
     */
    toolsFetchRequestedAt: Date | null;
    /**
     * 
     */
    publishedAt: Date | null;
    /**
     * 
     */
    mcpServerDirectory: MCPServerDirectoryBase;
    /**
     * 
     */
    mcpServerServiceConnection: ServerConnectionResponse | null;
    /**
     * 
     */
    connectionStatus: ConnectionStatus | null;
    /**
     * 
     */
    url: string | null;
    /**
     * 
     */
    proxyUrl: string | null;
    /**
     * 
     */
    canManagePolicies: boolean | null;
    /**
     * 
     */
    attentionTier: AttentionTier | null;
    /**
     * 
     */
    publishBlockers: Array<PublishBlocker> | null;
    /**
     * 
     */
    cascadedFields: Array<string> | null;
    /**
     * 
     */
    deletedAt: Date | null;
    /**
     * 
     */
    readonly toolsCount: number;
    /**
     * 
     */
    readonly resourcesCount: number;
}



/**
 * Check if a given object implements the ServerResponse interface.
 */
export function instanceOfServerResponse(value: object): value is ServerResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if ((!('oauthBaseUrlOverride' in (value as Record<string, any>)) && !('oauth_base_url_override' in (value as Record<string, any>))) || ((value as Record<string, any>)['oauthBaseUrlOverride'] === undefined && (value as Record<string, any>)['oauth_base_url_override'] === undefined)) return false;
    if ((!('clientId' in (value as Record<string, any>)) && !('client_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['clientId'] === undefined && (value as Record<string, any>)['client_id'] === undefined)) return false;
    if ((!('clientSecret' in (value as Record<string, any>)) && !('client_secret' in (value as Record<string, any>))) || ((value as Record<string, any>)['clientSecret'] === undefined && (value as Record<string, any>)['client_secret'] === undefined)) return false;
    if ((!('usesManagedCredentials' in (value as Record<string, any>)) && !('uses_managed_credentials' in (value as Record<string, any>))) || ((value as Record<string, any>)['usesManagedCredentials'] === undefined && (value as Record<string, any>)['uses_managed_credentials'] === undefined)) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if ((!('organizationId' in (value as Record<string, any>)) && !('organization_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['organizationId'] === undefined && (value as Record<string, any>)['organization_id'] === undefined)) return false;
    if ((!('mcpServerDirectoryId' in (value as Record<string, any>)) && !('mcp_server_directory_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerDirectoryId'] === undefined && (value as Record<string, any>)['mcp_server_directory_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if ((!('toolsFetchStatus' in (value as Record<string, any>)) && !('tools_fetch_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolsFetchStatus'] === undefined && (value as Record<string, any>)['tools_fetch_status'] === undefined)) return false;
    if ((!('toolsFetchError' in (value as Record<string, any>)) && !('tools_fetch_error' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolsFetchError'] === undefined && (value as Record<string, any>)['tools_fetch_error'] === undefined)) return false;
    if ((!('toolsFetchedAt' in (value as Record<string, any>)) && !('tools_fetched_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolsFetchedAt'] === undefined && (value as Record<string, any>)['tools_fetched_at'] === undefined)) return false;
    if ((!('toolsFetchRequestedAt' in (value as Record<string, any>)) && !('tools_fetch_requested_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolsFetchRequestedAt'] === undefined && (value as Record<string, any>)['tools_fetch_requested_at'] === undefined)) return false;
    if ((!('publishedAt' in (value as Record<string, any>)) && !('published_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['publishedAt'] === undefined && (value as Record<string, any>)['published_at'] === undefined)) return false;
    if ((!('mcpServerDirectory' in (value as Record<string, any>)) && !('mcp_server_directory' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerDirectory'] === undefined && (value as Record<string, any>)['mcp_server_directory'] === undefined)) return false;
    if ((!('mcpServerServiceConnection' in (value as Record<string, any>)) && !('mcp_server_service_connection' in (value as Record<string, any>))) || ((value as Record<string, any>)['mcpServerServiceConnection'] === undefined && (value as Record<string, any>)['mcp_server_service_connection'] === undefined)) return false;
    if ((!('connectionStatus' in (value as Record<string, any>)) && !('connection_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['connectionStatus'] === undefined && (value as Record<string, any>)['connection_status'] === undefined)) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if ((!('proxyUrl' in (value as Record<string, any>)) && !('proxy_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['proxyUrl'] === undefined && (value as Record<string, any>)['proxy_url'] === undefined)) return false;
    if ((!('canManagePolicies' in (value as Record<string, any>)) && !('can_manage_policies' in (value as Record<string, any>))) || ((value as Record<string, any>)['canManagePolicies'] === undefined && (value as Record<string, any>)['can_manage_policies'] === undefined)) return false;
    if ((!('attentionTier' in (value as Record<string, any>)) && !('attention_tier' in (value as Record<string, any>))) || ((value as Record<string, any>)['attentionTier'] === undefined && (value as Record<string, any>)['attention_tier'] === undefined)) return false;
    if ((!('publishBlockers' in (value as Record<string, any>)) && !('publish_blockers' in (value as Record<string, any>))) || ((value as Record<string, any>)['publishBlockers'] === undefined && (value as Record<string, any>)['publish_blockers'] === undefined)) return false;
    if ((!('cascadedFields' in (value as Record<string, any>)) && !('cascaded_fields' in (value as Record<string, any>))) || ((value as Record<string, any>)['cascadedFields'] === undefined && (value as Record<string, any>)['cascaded_fields'] === undefined)) return false;
    if ((!('deletedAt' in (value as Record<string, any>)) && !('deleted_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['deletedAt'] === undefined && (value as Record<string, any>)['deleted_at'] === undefined)) return false;
    if ((!('toolsCount' in (value as Record<string, any>)) && !('tools_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['toolsCount'] === undefined && (value as Record<string, any>)['tools_count'] === undefined)) return false;
    if ((!('resourcesCount' in (value as Record<string, any>)) && !('resources_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['resourcesCount'] === undefined && (value as Record<string, any>)['resources_count'] === undefined)) return false;
    return true;
}

export function ServerResponseFromJSON(json: any): ServerResponse {
    return ServerResponseFromJSONTyped(json, false);
}

export function ServerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'name': json['name'],
        'slug': json['slug'],
        'oauthBaseUrlOverride': json['oauth_base_url_override'],
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
        'usesManagedCredentials': json['uses_managed_credentials'],
        'scopes': json['scopes'] == null ? null : json['scopes'],
        'organizationId': json['organization_id'],
        'mcpServerDirectoryId': json['mcp_server_directory_id'],
        'status': json['status'],
        'meta': json['meta'],
        'toolsFetchStatus': json['tools_fetch_status'],
        'toolsFetchError': json['tools_fetch_error'],
        'toolsFetchedAt': (json['tools_fetched_at'] == null ? null : parseDateTime(json['tools_fetched_at'])),
        'toolsFetchRequestedAt': (json['tools_fetch_requested_at'] == null ? null : parseDateTime(json['tools_fetch_requested_at'])),
        'publishedAt': (json['published_at'] == null ? null : parseDateTime(json['published_at'])),
        'mcpServerDirectory': MCPServerDirectoryBaseFromJSON(json['mcp_server_directory']),
        'mcpServerServiceConnection': ServerConnectionResponseFromJSON(json['mcp_server_service_connection']),
        'connectionStatus': ConnectionStatusFromJSON(json['connection_status']),
        'url': json['url'],
        'proxyUrl': json['proxy_url'],
        'canManagePolicies': json['can_manage_policies'],
        'attentionTier': AttentionTierFromJSON(json['attention_tier']),
        'publishBlockers': (json['publish_blockers'] == null ? null : (json['publish_blockers'] as Array<any>).map(PublishBlockerFromJSON)),
        'cascadedFields': json['cascaded_fields'] == null ? null : json['cascaded_fields'],
        'deletedAt': (json['deleted_at'] == null ? null : parseDateTime(json['deleted_at'])),
        'toolsCount': json['tools_count'],
        'resourcesCount': json['resources_count'],
    };
}

export function ServerResponseToJSON(json: any): ServerResponse {
    return ServerResponseToJSONTyped(json, false);
}

export function ServerResponseToJSONTyped(value?: Omit<ServerResponse, 'toolsCount'|'resourcesCount'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'name': value['name'],
        'slug': value['slug'],
        'oauth_base_url_override': value['oauthBaseUrlOverride'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'uses_managed_credentials': value['usesManagedCredentials'],
        'scopes': value['scopes'],
        'organization_id': value['organizationId'],
        'mcp_server_directory_id': value['mcpServerDirectoryId'],
        'status': value['status'],
        'meta': value['meta'],
        'tools_fetch_status': value['toolsFetchStatus'],
        'tools_fetch_error': value['toolsFetchError'],
        'tools_fetched_at': value['toolsFetchedAt'] == null ? value['toolsFetchedAt'] : serializeDateTime(value['toolsFetchedAt']),
        'tools_fetch_requested_at': value['toolsFetchRequestedAt'] == null ? value['toolsFetchRequestedAt'] : serializeDateTime(value['toolsFetchRequestedAt']),
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : serializeDateTime(value['publishedAt']),
        'mcp_server_directory': MCPServerDirectoryBaseToJSON(value['mcpServerDirectory']),
        'mcp_server_service_connection': ServerConnectionResponseToJSON(value['mcpServerServiceConnection']),
        'connection_status': ConnectionStatusToJSON(value['connectionStatus']),
        'url': value['url'],
        'proxy_url': value['proxyUrl'],
        'can_manage_policies': value['canManagePolicies'],
        'attention_tier': AttentionTierToJSON(value['attentionTier']),
        'publish_blockers': (value['publishBlockers'] == null ? null : (value['publishBlockers'] as Array<any>).map(PublishBlockerToJSON)),
        'cascaded_fields': value['cascadedFields'],
        'deleted_at': value['deletedAt'] == null ? value['deletedAt'] : serializeDateTime(value['deletedAt']),
    };
}

