/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PolicyRevisionSummary } from './PolicyRevisionSummary.js';
import {
    PolicyRevisionSummaryFromJSON,
    PolicyRevisionSummaryFromJSONTyped,
    PolicyRevisionSummaryToJSON,
    PolicyRevisionSummaryToJSONTyped,
} from './PolicyRevisionSummary.js';

/**
 * Cursor-paged page of policy revisions scoped to one MCP server (BCP-4458).
 * 
 * Backs ``GET /admin/v2/policy-revisions`` — one source instead of the
 * per-policy fan-out the client used to do. No ``total``/``pages``: this is
 * keyset, not offset, pagination, so there is deliberately no ``COUNT``.
 * @export
 * @interface ServerPolicyRevisionsPage
 */
export interface ServerPolicyRevisionsPage {
    /**
     * 
     */
    data: Array<PolicyRevisionSummary>;
    /**
     * Opaque cursor for the next page; null when there are no more results.
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the ServerPolicyRevisionsPage interface.
 */
export function instanceOfServerPolicyRevisionsPage(value: object): value is ServerPolicyRevisionsPage {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ServerPolicyRevisionsPageFromJSON(json: any): ServerPolicyRevisionsPage {
    return ServerPolicyRevisionsPageFromJSONTyped(json, false);
}

export function ServerPolicyRevisionsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerPolicyRevisionsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PolicyRevisionSummaryFromJSON)),
        'nextCursor': json['next_cursor'] === undefined ? undefined : json['next_cursor'] === null ? null : json['next_cursor'],
    };
}

export function ServerPolicyRevisionsPageToJSON(json: any): ServerPolicyRevisionsPage {
    return ServerPolicyRevisionsPageToJSONTyped(json, false);
}

export function ServerPolicyRevisionsPageToJSONTyped(value?: ServerPolicyRevisionsPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PolicyRevisionSummaryToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

