/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServerSource = {
    Barndoor: 'barndoor',
    ThirdParty: 'third_party',
    Internal: 'internal',
    CustomThirdParty: 'custom_third_party',
    CustomInternal: 'custom_internal',
    Local: 'local',
    Embedded: 'embedded',
} as const;
export type ServerSource = typeof ServerSource[keyof typeof ServerSource];


export function instanceOfServerSource(value: any): boolean {
    for (const key in ServerSource) {
        if (Object.prototype.hasOwnProperty.call(ServerSource, key)) {
            if (ServerSource[key as keyof typeof ServerSource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServerSourceFromJSON(json: any): ServerSource {
    return ServerSourceFromJSONTyped(json, false);
}

export function ServerSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerSource {
    return json as ServerSource;
}

export function ServerSourceToJSON(value?: ServerSource | null): any {
    return value as any;
}

export function ServerSourceToJSONTyped(value: any, ignoreDiscriminator: boolean): ServerSource {
    return value as ServerSource;
}

