/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SetApiKeyDisabledRequest
 */
export interface SetApiKeyDisabledRequest {
    /**
     * 
     */
    disabled: boolean;
}

/**
 * Check if a given object implements the SetApiKeyDisabledRequest interface.
 */
export function instanceOfSetApiKeyDisabledRequest(value: object): value is SetApiKeyDisabledRequest {
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    return true;
}

export function SetApiKeyDisabledRequestFromJSON(json: any): SetApiKeyDisabledRequest {
    return SetApiKeyDisabledRequestFromJSONTyped(json, false);
}

export function SetApiKeyDisabledRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetApiKeyDisabledRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'],
    };
}

export function SetApiKeyDisabledRequestToJSON(json: any): SetApiKeyDisabledRequest {
    return SetApiKeyDisabledRequestToJSONTyped(json, false);
}

export function SetApiKeyDisabledRequestToJSONTyped(value?: SetApiKeyDisabledRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
    };
}

