/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StaleReason = {
    CatalogRemoved: 'catalog_removed',
} as const;
export type StaleReason = typeof StaleReason[keyof typeof StaleReason];


export function instanceOfStaleReason(value: any): boolean {
    for (const key in StaleReason) {
        if (Object.prototype.hasOwnProperty.call(StaleReason, key)) {
            if (StaleReason[key as keyof typeof StaleReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StaleReasonFromJSON(json: any): StaleReason {
    return StaleReasonFromJSONTyped(json, false);
}

export function StaleReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaleReason {
    return json as StaleReason;
}

export function StaleReasonToJSON(value?: StaleReason | null): any {
    return value as any;
}

export function StaleReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): StaleReason {
    return value as StaleReason;
}

