/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ResolvedProtectionResponse } from './ResolvedProtectionResponse.js';
import {
    ResolvedProtectionResponseFromJSON,
    ResolvedProtectionResponseFromJSONTyped,
    ResolvedProtectionResponseToJSON,
    ResolvedProtectionResponseToJSONTyped,
} from './ResolvedProtectionResponse.js';
import type { TestFindingResponse } from './TestFindingResponse.js';
import {
    TestFindingResponseFromJSON,
    TestFindingResponseFromJSONTyped,
    TestFindingResponseToJSON,
    TestFindingResponseToJSONTyped,
} from './TestFindingResponse.js';

/**
 * 
 * @export
 * @interface TestProcessTextResponse
 */
export interface TestProcessTextResponse {
    /**
     * 
     */
    blockReason?: string | null;
    /**
     * 
     */
    durationMs: number;
    /**
     * 
     */
    findings: Array<TestFindingResponse>;
    /**
     * 
     */
    processedStructuredPayloadJson?: string | null;
    /**
     * 
     */
    processedText: string;
    /**
     * 
     */
    resolvedPolicy: ResolvedProtectionResponse;
    /**
     * 
     */
    verdict: string;
}

/**
 * Check if a given object implements the TestProcessTextResponse interface.
 */
export function instanceOfTestProcessTextResponse(value: object): value is TestProcessTextResponse {
    if ((!('durationMs' in (value as Record<string, any>)) && !('duration_ms' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationMs'] === undefined && (value as Record<string, any>)['duration_ms'] === undefined)) return false;
    if (!('findings' in value) || value['findings'] === undefined) return false;
    if ((!('processedText' in (value as Record<string, any>)) && !('processed_text' in (value as Record<string, any>))) || ((value as Record<string, any>)['processedText'] === undefined && (value as Record<string, any>)['processed_text'] === undefined)) return false;
    if ((!('resolvedPolicy' in (value as Record<string, any>)) && !('resolved_policy' in (value as Record<string, any>))) || ((value as Record<string, any>)['resolvedPolicy'] === undefined && (value as Record<string, any>)['resolved_policy'] === undefined)) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    return true;
}

export function TestProcessTextResponseFromJSON(json: any): TestProcessTextResponse {
    return TestProcessTextResponseFromJSONTyped(json, false);
}

export function TestProcessTextResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestProcessTextResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'blockReason': json['block_reason'] === undefined ? undefined : json['block_reason'] === null ? null : json['block_reason'],
        'durationMs': json['duration_ms'],
        'findings': ((json['findings'] as Array<any>).map(TestFindingResponseFromJSON)),
        'processedStructuredPayloadJson': json['processed_structured_payload_json'] === undefined ? undefined : json['processed_structured_payload_json'] === null ? null : json['processed_structured_payload_json'],
        'processedText': json['processed_text'],
        'resolvedPolicy': ResolvedProtectionResponseFromJSON(json['resolved_policy']),
        'verdict': json['verdict'],
    };
}

export function TestProcessTextResponseToJSON(json: any): TestProcessTextResponse {
    return TestProcessTextResponseToJSONTyped(json, false);
}

export function TestProcessTextResponseToJSONTyped(value?: TestProcessTextResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'block_reason': value['blockReason'],
        'duration_ms': value['durationMs'],
        'findings': ((value['findings'] as Array<any>).map(TestFindingResponseToJSON)),
        'processed_structured_payload_json': value['processedStructuredPayloadJson'],
        'processed_text': value['processedText'],
        'resolved_policy': ResolvedProtectionResponseToJSON(value['resolvedPolicy']),
        'verdict': value['verdict'],
    };
}

