/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TokenizationConnectionResponse
 */
export interface TokenizationConnectionResponse {
    /**
     * 
     */
    endpoint: string;
    /**
     * Whether a bearer token is configured. The token value is never returned.
     */
    hasBearerToken: boolean;
    /**
     * 
     */
    orgId: string;
}

/**
 * Check if a given object implements the TokenizationConnectionResponse interface.
 */
export function instanceOfTokenizationConnectionResponse(value: object): value is TokenizationConnectionResponse {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if ((!('hasBearerToken' in (value as Record<string, any>)) && !('has_bearer_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasBearerToken'] === undefined && (value as Record<string, any>)['has_bearer_token'] === undefined)) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    return true;
}

export function TokenizationConnectionResponseFromJSON(json: any): TokenizationConnectionResponse {
    return TokenizationConnectionResponseFromJSONTyped(json, false);
}

export function TokenizationConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenizationConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
        'hasBearerToken': json['has_bearer_token'],
        'orgId': json['org_id'],
    };
}

export function TokenizationConnectionResponseToJSON(json: any): TokenizationConnectionResponse {
    return TokenizationConnectionResponseToJSONTyped(json, false);
}

export function TokenizationConnectionResponseToJSONTyped(value?: TokenizationConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'has_bearer_token': value['hasBearerToken'],
        'org_id': value['orgId'],
    };
}

