/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TrafficType = {
    All: 'all',
    Llm: 'llm',
    Mcp: 'mcp',
} as const;
export type TrafficType = typeof TrafficType[keyof typeof TrafficType];


export function instanceOfTrafficType(value: any): boolean {
    for (const key in TrafficType) {
        if (Object.prototype.hasOwnProperty.call(TrafficType, key)) {
            if (TrafficType[key as keyof typeof TrafficType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TrafficTypeFromJSON(json: any): TrafficType {
    return TrafficTypeFromJSONTyped(json, false);
}

export function TrafficTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrafficType {
    return json as TrafficType;
}

export function TrafficTypeToJSON(value?: TrafficType | null): any {
    return value as any;
}

export function TrafficTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TrafficType {
    return value as TrafficType;
}

