/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateDetectionEngineRequest
 */
export interface UpdateDetectionEngineRequest {
    /**
     * 
     */
    config?: any | null;
    /**
     * 
     */
    enabledDetectionTypes?: Array<string> | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    providerConnectionName?: string | null;
    /**
     * 
     */
    providerType?: string | null;
}

/**
 * Check if a given object implements the UpdateDetectionEngineRequest interface.
 */
export function instanceOfUpdateDetectionEngineRequest(value: object): value is UpdateDetectionEngineRequest {
    return true;
}

export function UpdateDetectionEngineRequestFromJSON(json: any): UpdateDetectionEngineRequest {
    return UpdateDetectionEngineRequestFromJSONTyped(json, false);
}

export function UpdateDetectionEngineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDetectionEngineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] === undefined ? undefined : json['config'] === null ? null : json['config'],
        'enabledDetectionTypes': json['enabled_detection_types'] === undefined ? undefined : json['enabled_detection_types'] === null ? null : json['enabled_detection_types'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'providerConnectionName': json['provider_connection_name'] === undefined ? undefined : json['provider_connection_name'] === null ? null : json['provider_connection_name'],
        'providerType': json['provider_type'] === undefined ? undefined : json['provider_type'] === null ? null : json['provider_type'],
    };
}

export function UpdateDetectionEngineRequestToJSON(json: any): UpdateDetectionEngineRequest {
    return UpdateDetectionEngineRequestToJSONTyped(json, false);
}

export function UpdateDetectionEngineRequestToJSONTyped(value?: UpdateDetectionEngineRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'enabled_detection_types': value['enabledDetectionTypes'],
        'name': value['name'],
        'provider_connection_name': value['providerConnectionName'],
        'provider_type': value['providerType'],
    };
}

