/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateRouteGroupRequest
 */
export interface UpdateRouteGroupRequest {
    /**
     * Optional free-text note explaining why this edit was made. Omitting it
     * clears any previous note — unlike `description` directly above, which
     * is a standing property of the group rather than an account of one
     * change.
     */
    changeNote?: string | null;
    /**
     * 
     */
    description?: string | null;
    /**
     * Replaces the membership wholesale when present. Absent leaves it alone
     * — a rename must not have to restate the members.
     */
    modelAliases?: Array<string> | null;
    /**
     * 
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateRouteGroupRequest interface.
 */
export function instanceOfUpdateRouteGroupRequest(value: object): value is UpdateRouteGroupRequest {
    return true;
}

export function UpdateRouteGroupRequestFromJSON(json: any): UpdateRouteGroupRequest {
    return UpdateRouteGroupRequestFromJSONTyped(json, false);
}

export function UpdateRouteGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRouteGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'modelAliases': json['model_aliases'] === undefined ? undefined : json['model_aliases'] === null ? null : json['model_aliases'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}

export function UpdateRouteGroupRequestToJSON(json: any): UpdateRouteGroupRequest {
    return UpdateRouteGroupRequestToJSONTyped(json, false);
}

export function UpdateRouteGroupRequestToJSONTyped(value?: UpdateRouteGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'description': value['description'],
        'model_aliases': value['modelAliases'],
        'name': value['name'],
    };
}

