/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { LongContextTierRequest } from './LongContextTierRequest.js';
import {
    LongContextTierRequestFromJSON,
    LongContextTierRequestFromJSONTyped,
    LongContextTierRequestToJSON,
    LongContextTierRequestToJSONTyped,
} from './LongContextTierRequest.js';
import type { PricingSyncMode } from './PricingSyncMode.js';
import {
    PricingSyncModeFromJSON,
    PricingSyncModeFromJSONTyped,
    PricingSyncModeToJSON,
    PricingSyncModeToJSONTyped,
} from './PricingSyncMode.js';

/**
 * 
 * @export
 * @interface UpdatePricingRequest
 */
export interface UpdatePricingRequest {
    /**
     * Update prompt-cache rates. Same NULL semantics as
     * `CreatePricingRequest`: omitted = leave existing value alone;
     * JSON `null` = explicitly clear the override.
     */
    cacheReadCostPerMillionTokens?: number | null;
    /**
     * 
     */
    cacheWriteCostPerMillionTokens?: number | null;
    /**
     * 
     */
    changeReason?: string | null;
    /**
     * Reschedule the activation date. Past values are rejected by the
     * db layer's `update_scheduled` guard, but a future timestamp is
     * fine and a near-`now()` timestamp effectively "activates now".
     */
    effectiveFrom?: Date | null;
    /**
     * 
     */
    inputCostPerMillionTokens?: number | null;
    /**
     * Update the long-context surcharge (BCP-3904). Same three-state
     * semantics as the cache rates: omitted = leave the tier alone, JSON
     * `null` = remove the tier entirely, an object = set it.
     * 
     * The tier moves as a unit, so `null` clears the threshold and every
     * tier rate together — there is no way to null out one tier rate while
     * keeping the others, which is what the DB constraint requires anyway.
     */
    longContext?: LongContextTierRequest | null;
    /**
     * 
     */
    outputCostPerMillionTokens?: number | null;
    /**
     * Omit (or pass `null`) to leave the mode unchanged.
     */
    syncMode?: PricingSyncMode | null;
}



/**
 * Check if a given object implements the UpdatePricingRequest interface.
 */
export function instanceOfUpdatePricingRequest(value: object): value is UpdatePricingRequest {
    return true;
}

export function UpdatePricingRequestFromJSON(json: any): UpdatePricingRequest {
    return UpdatePricingRequestFromJSONTyped(json, false);
}

export function UpdatePricingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePricingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheReadCostPerMillionTokens': json['cache_read_cost_per_million_tokens'] === undefined ? undefined : json['cache_read_cost_per_million_tokens'] === null ? null : json['cache_read_cost_per_million_tokens'],
        'cacheWriteCostPerMillionTokens': json['cache_write_cost_per_million_tokens'] === undefined ? undefined : json['cache_write_cost_per_million_tokens'] === null ? null : json['cache_write_cost_per_million_tokens'],
        'changeReason': json['change_reason'] === undefined ? undefined : json['change_reason'] === null ? null : json['change_reason'],
        'effectiveFrom': json['effective_from'] === undefined ? undefined : json['effective_from'] === null ? null : (parseDateTime(json['effective_from'])),
        'inputCostPerMillionTokens': json['input_cost_per_million_tokens'] === undefined ? undefined : json['input_cost_per_million_tokens'] === null ? null : json['input_cost_per_million_tokens'],
        'longContext': json['long_context'] === undefined ? undefined : json['long_context'] === null ? null : LongContextTierRequestFromJSON(json['long_context']),
        'outputCostPerMillionTokens': json['output_cost_per_million_tokens'] === undefined ? undefined : json['output_cost_per_million_tokens'] === null ? null : json['output_cost_per_million_tokens'],
        'syncMode': json['sync_mode'] === undefined ? undefined : json['sync_mode'] === null ? null : PricingSyncModeFromJSON(json['sync_mode']),
    };
}

export function UpdatePricingRequestToJSON(json: any): UpdatePricingRequest {
    return UpdatePricingRequestToJSONTyped(json, false);
}

export function UpdatePricingRequestToJSONTyped(value?: UpdatePricingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cache_read_cost_per_million_tokens': value['cacheReadCostPerMillionTokens'],
        'cache_write_cost_per_million_tokens': value['cacheWriteCostPerMillionTokens'],
        'change_reason': value['changeReason'],
        'effective_from': value['effectiveFrom'] == null ? value['effectiveFrom'] : serializeDateTime(value['effectiveFrom']),
        'input_cost_per_million_tokens': value['inputCostPerMillionTokens'],
        'long_context': LongContextTierRequestToJSON(value['longContext']),
        'output_cost_per_million_tokens': value['outputCostPerMillionTokens'],
        'sync_mode': PricingSyncModeToJSON(value['syncMode']),
    };
}

