/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * `PATCH` semantics for an optional numeric metric — see
 * [`super::deserialize_explicit_null`].
 * @export
 * @interface UpdateRateLimitRequest
 */
export interface UpdateRateLimitRequest {
    /**
     * Optional free-text note explaining why this edit was made. Omitting it
     * clears any previous note — deliberately *not* the tri-state merge-patch
     * treatment the fields above get, because the note describes the latest
     * change and carrying an old one forward would explain the wrong edit.
     */
    changeNote?: string | null;
    /**
     * 
     */
    enabled?: boolean | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    requestsPerMinute?: number | null;
    /**
     * Tri-state, so an entity-bound policy can be unbound back to "all"
     * (BCP-3955) rather than silently keeping its old binding.
     */
    scopeId?: string | null;
    /**
     * 
     */
    scopeType?: string | null;
    /**
     * 
     */
    scopeValue?: string | null;
    /**
     * 
     */
    targetMcpServerId?: string | null;
    /**
     * 
     */
    targetModelAlias?: string | null;
    /**
     * BCP-4056: the Target columns are tri-state on update for the same
     * reason the scope columns are — a policy that gained a target must be
     * able to lose it again. Safe to retarget in place (unlike a budget,
     * whose period counter would be orphaned) because a rate-limit window is
     * 60s and self-heals.
     */
    targetProviderId?: string | null;
    /**
     * 
     */
    targetUpstreamModel?: string | null;
    /**
     * 
     */
    tokensPerMinute?: number | null;
    /**
     * 
     */
    trafficType?: string | null;
}

/**
 * Check if a given object implements the UpdateRateLimitRequest interface.
 */
export function instanceOfUpdateRateLimitRequest(value: object): value is UpdateRateLimitRequest {
    return true;
}

export function UpdateRateLimitRequestFromJSON(json: any): UpdateRateLimitRequest {
    return UpdateRateLimitRequestFromJSONTyped(json, false);
}

export function UpdateRateLimitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRateLimitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'enabled': json['enabled'] === undefined ? undefined : json['enabled'] === null ? null : json['enabled'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'requestsPerMinute': json['requests_per_minute'] === undefined ? undefined : json['requests_per_minute'] === null ? null : json['requests_per_minute'],
        'scopeId': json['scope_id'] === undefined ? undefined : json['scope_id'] === null ? null : json['scope_id'],
        'scopeType': json['scope_type'] === undefined ? undefined : json['scope_type'] === null ? null : json['scope_type'],
        'scopeValue': json['scope_value'] === undefined ? undefined : json['scope_value'] === null ? null : json['scope_value'],
        'targetMcpServerId': json['target_mcp_server_id'] === undefined ? undefined : json['target_mcp_server_id'] === null ? null : json['target_mcp_server_id'],
        'targetModelAlias': json['target_model_alias'] === undefined ? undefined : json['target_model_alias'] === null ? null : json['target_model_alias'],
        'targetProviderId': json['target_provider_id'] === undefined ? undefined : json['target_provider_id'] === null ? null : json['target_provider_id'],
        'targetUpstreamModel': json['target_upstream_model'] === undefined ? undefined : json['target_upstream_model'] === null ? null : json['target_upstream_model'],
        'tokensPerMinute': json['tokens_per_minute'] === undefined ? undefined : json['tokens_per_minute'] === null ? null : json['tokens_per_minute'],
        'trafficType': json['traffic_type'] === undefined ? undefined : json['traffic_type'] === null ? null : json['traffic_type'],
    };
}

export function UpdateRateLimitRequestToJSON(json: any): UpdateRateLimitRequest {
    return UpdateRateLimitRequestToJSONTyped(json, false);
}

export function UpdateRateLimitRequestToJSONTyped(value?: UpdateRateLimitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'enabled': value['enabled'],
        'name': value['name'],
        'requests_per_minute': value['requestsPerMinute'],
        'scope_id': value['scopeId'],
        'scope_type': value['scopeType'],
        'scope_value': value['scopeValue'],
        'target_mcp_server_id': value['targetMcpServerId'],
        'target_model_alias': value['targetModelAlias'],
        'target_provider_id': value['targetProviderId'],
        'target_upstream_model': value['targetUpstreamModel'],
        'tokens_per_minute': value['tokensPerMinute'],
        'traffic_type': value['trafficType'],
    };
}

