/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ModelAccessTarget } from './ModelAccessTarget.js';
import {
    ModelAccessTargetFromJSON,
    ModelAccessTargetFromJSONTyped,
    ModelAccessTargetToJSON,
    ModelAccessTargetToJSONTyped,
} from './ModelAccessTarget.js';

/**
 * 
 * @export
 * @interface UpdateModelAccessRequest
 */
export interface UpdateModelAccessRequest {
    /**
     * Optional free-text note explaining why this edit was made. Omitting it
     * clears any previous note — deliberately *not* the tri-state treatment
     * the scope fields above get, because the note describes the latest
     * change and carrying an old one forward would explain the wrong edit.
     */
    changeNote?: string | null;
    /**
     * 
     */
    enabled?: boolean | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    policyType?: string | null;
    /**
     * Tri-state (see [`deserialize_explicit_null`]). A policy bound to one
     * entity is unbound by sending `null` — that is how the admin UI moves an
     * `api_key`-scoped policy back to "All API Keys". A plain `Option<Uuid>`
     * made that indistinguishable from omitting the field, so the update
     * silently kept the old binding (BCP-3955).
     */
    scopeId?: string | null;
    /**
     * 
     */
    scopeType?: string | null;
    /**
     * 
     */
    scopeValue?: string | null;
    /**
     * 
     */
    targets?: Array<ModelAccessTarget> | null;
    /**
     * 
     */
    trafficType?: string | null;
}

/**
 * Check if a given object implements the UpdateModelAccessRequest interface.
 */
export function instanceOfUpdateModelAccessRequest(value: object): value is UpdateModelAccessRequest {
    return true;
}

export function UpdateModelAccessRequestFromJSON(json: any): UpdateModelAccessRequest {
    return UpdateModelAccessRequestFromJSONTyped(json, false);
}

export function UpdateModelAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateModelAccessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'changeNote': json['change_note'] === undefined ? undefined : json['change_note'] === null ? null : json['change_note'],
        'enabled': json['enabled'] === undefined ? undefined : json['enabled'] === null ? null : json['enabled'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'policyType': json['policy_type'] === undefined ? undefined : json['policy_type'] === null ? null : json['policy_type'],
        'scopeId': json['scope_id'] === undefined ? undefined : json['scope_id'] === null ? null : json['scope_id'],
        'scopeType': json['scope_type'] === undefined ? undefined : json['scope_type'] === null ? null : json['scope_type'],
        'scopeValue': json['scope_value'] === undefined ? undefined : json['scope_value'] === null ? null : json['scope_value'],
        'targets': json['targets'] === undefined ? undefined : json['targets'] === null ? null : ((json['targets'] as Array<any>).map(ModelAccessTargetFromJSON)),
        'trafficType': json['traffic_type'] === undefined ? undefined : json['traffic_type'] === null ? null : json['traffic_type'],
    };
}

export function UpdateModelAccessRequestToJSON(json: any): UpdateModelAccessRequest {
    return UpdateModelAccessRequestToJSONTyped(json, false);
}

export function UpdateModelAccessRequestToJSONTyped(value?: UpdateModelAccessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_note': value['changeNote'],
        'enabled': value['enabled'],
        'name': value['name'],
        'policy_type': value['policyType'],
        'scope_id': value['scopeId'],
        'scope_type': value['scopeType'],
        'scope_value': value['scopeValue'],
        'targets': value['targets'] == null ? undefined : ((value['targets'] as Array<any>).map(ModelAccessTargetToJSON)),
        'traffic_type': value['trafficType'],
    };
}

