/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertConnectionRequestOneOf1
 */
export interface UpsertConnectionRequestOneOf1 {
    /**
     * Supply to set or rotate the token; omit to leave unchanged.
     */
    bearerToken?: string;
    /**
     * 
     */
    endpoint?: string;
    /**
     * 
     */
    location?: string;
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    provider: UpsertConnectionRequestOneOf1ProviderEnum;
}


/**
 * @export
 */
export const UpsertConnectionRequestOneOf1ProviderEnum = {
    GoogleDlp: 'google_dlp',
} as const;
export type UpsertConnectionRequestOneOf1ProviderEnum = typeof UpsertConnectionRequestOneOf1ProviderEnum[keyof typeof UpsertConnectionRequestOneOf1ProviderEnum];


/**
 * Check if a given object implements the UpsertConnectionRequestOneOf1 interface.
 */
export function instanceOfUpsertConnectionRequestOneOf1(value: object): value is UpsertConnectionRequestOneOf1 {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'google_dlp') return false;
    
    return true;
}

export function UpsertConnectionRequestOneOf1FromJSON(json: any): UpsertConnectionRequestOneOf1 {
    return UpsertConnectionRequestOneOf1FromJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertConnectionRequestOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'bearerToken': json['bearer_token'] == null ? undefined : json['bearer_token'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'location': json['location'] == null ? undefined : json['location'],
        'projectId': json['project_id'],
        'provider': json['provider'],
    };
}

export function UpsertConnectionRequestOneOf1ToJSON(json: any): UpsertConnectionRequestOneOf1 {
    return UpsertConnectionRequestOneOf1ToJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf1ToJSONTyped(value?: UpsertConnectionRequestOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bearer_token': value['bearerToken'],
        'endpoint': value['endpoint'],
        'location': value['location'],
        'project_id': value['projectId'],
        'provider': value['provider'],
    };
}

