/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertConnectionRequestOneOf4
 */
export interface UpsertConnectionRequestOneOf4 {
    /**
     * Supply to set or rotate the API key; omit to leave unchanged.
     */
    apiKey?: string;
    /**
     * 
     */
    apiVersion?: string;
    /**
     * 
     */
    endpoint: string;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    provider: UpsertConnectionRequestOneOf4ProviderEnum;
}


/**
 * @export
 */
export const UpsertConnectionRequestOneOf4ProviderEnum = {
    AzureAiLanguagePii: 'azure_ai_language_pii',
} as const;
export type UpsertConnectionRequestOneOf4ProviderEnum = typeof UpsertConnectionRequestOneOf4ProviderEnum[keyof typeof UpsertConnectionRequestOneOf4ProviderEnum];


/**
 * Check if a given object implements the UpsertConnectionRequestOneOf4 interface.
 */
export function instanceOfUpsertConnectionRequestOneOf4(value: object): value is UpsertConnectionRequestOneOf4 {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'azure_ai_language_pii') return false;
    
    return true;
}

export function UpsertConnectionRequestOneOf4FromJSON(json: any): UpsertConnectionRequestOneOf4 {
    return UpsertConnectionRequestOneOf4FromJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertConnectionRequestOneOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'endpoint': json['endpoint'],
        'language': json['language'] == null ? undefined : json['language'],
        'provider': json['provider'],
    };
}

export function UpsertConnectionRequestOneOf4ToJSON(json: any): UpsertConnectionRequestOneOf4 {
    return UpsertConnectionRequestOneOf4ToJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf4ToJSONTyped(value?: UpsertConnectionRequestOneOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'api_version': value['apiVersion'],
        'endpoint': value['endpoint'],
        'language': value['language'],
        'provider': value['provider'],
    };
}

