/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertPresidioRequest
 */
export interface UpsertPresidioRequest {
    /**
     * 
     */
    analyzerUrl: string;
    /**
     * 
     */
    anonymizerUrl?: string | null;
    /**
     * Supply to set or rotate the token; omit to leave unchanged.
     */
    bearerToken?: string | null;
    /**
     * 
     */
    language?: string;
}

/**
 * Check if a given object implements the UpsertPresidioRequest interface.
 */
export function instanceOfUpsertPresidioRequest(value: object): value is UpsertPresidioRequest {
    if ((!('analyzerUrl' in (value as Record<string, any>)) && !('analyzer_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['analyzerUrl'] === undefined && (value as Record<string, any>)['analyzer_url'] === undefined)) return false;
    return true;
}

export function UpsertPresidioRequestFromJSON(json: any): UpsertPresidioRequest {
    return UpsertPresidioRequestFromJSONTyped(json, false);
}

export function UpsertPresidioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertPresidioRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'analyzerUrl': json['analyzer_url'],
        'anonymizerUrl': json['anonymizer_url'] === undefined ? undefined : json['anonymizer_url'] === null ? null : json['anonymizer_url'],
        'bearerToken': json['bearer_token'] === undefined ? undefined : json['bearer_token'] === null ? null : json['bearer_token'],
        'language': json['language'] == null ? undefined : json['language'],
    };
}

export function UpsertPresidioRequestToJSON(json: any): UpsertPresidioRequest {
    return UpsertPresidioRequestToJSONTyped(json, false);
}

export function UpsertPresidioRequestToJSONTyped(value?: UpsertPresidioRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analyzer_url': value['analyzerUrl'],
        'anonymizer_url': value['anonymizerUrl'],
        'bearer_token': value['bearerToken'],
        'language': value['language'],
    };
}

