/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertAwsComprehendPiiRequest
 */
export interface UpsertAwsComprehendPiiRequest {
    /**
     * 
     */
    accessKeyId?: string | null;
    /**
     * 
     */
    authType?: string | null;
    /**
     * 
     */
    endpoint?: string | null;
    /**
     * 
     */
    externalId?: string | null;
    /**
     * 
     */
    iamRoleArn?: string | null;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    region?: string;
    /**
     * Supply to set or rotate the AWS secret; omit to leave unchanged.
     */
    secretAccessKey?: string | null;
    /**
     * Optional AWS session token stored with the secret access key.
     */
    sessionToken?: string | null;
}

/**
 * Check if a given object implements the UpsertAwsComprehendPiiRequest interface.
 */
export function instanceOfUpsertAwsComprehendPiiRequest(value: object): value is UpsertAwsComprehendPiiRequest {
    return true;
}

export function UpsertAwsComprehendPiiRequestFromJSON(json: any): UpsertAwsComprehendPiiRequest {
    return UpsertAwsComprehendPiiRequestFromJSONTyped(json, false);
}

export function UpsertAwsComprehendPiiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertAwsComprehendPiiRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'] === undefined ? undefined : json['access_key_id'] === null ? null : json['access_key_id'],
        'authType': json['auth_type'] === undefined ? undefined : json['auth_type'] === null ? null : json['auth_type'],
        'endpoint': json['endpoint'] === undefined ? undefined : json['endpoint'] === null ? null : json['endpoint'],
        'externalId': json['external_id'] === undefined ? undefined : json['external_id'] === null ? null : json['external_id'],
        'iamRoleArn': json['iam_role_arn'] === undefined ? undefined : json['iam_role_arn'] === null ? null : json['iam_role_arn'],
        'language': json['language'] == null ? undefined : json['language'],
        'region': json['region'] == null ? undefined : json['region'],
        'secretAccessKey': json['secret_access_key'] === undefined ? undefined : json['secret_access_key'] === null ? null : json['secret_access_key'],
        'sessionToken': json['session_token'] === undefined ? undefined : json['session_token'] === null ? null : json['session_token'],
    };
}

export function UpsertAwsComprehendPiiRequestToJSON(json: any): UpsertAwsComprehendPiiRequest {
    return UpsertAwsComprehendPiiRequestToJSONTyped(json, false);
}

export function UpsertAwsComprehendPiiRequestToJSONTyped(value?: UpsertAwsComprehendPiiRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'auth_type': value['authType'],
        'endpoint': value['endpoint'],
        'external_id': value['externalId'],
        'iam_role_arn': value['iamRoleArn'],
        'language': value['language'],
        'region': value['region'],
        'secret_access_key': value['secretAccessKey'],
        'session_token': value['sessionToken'],
    };
}

