/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertConnectionRequestOneOf5
 */
export interface UpsertConnectionRequestOneOf5 {
    /**
     * Supply to set or rotate the API key; omit to leave unchanged.
     */
    apiKey?: string;
    /**
     * 
     */
    apiVersion?: string;
    /**
     * 
     */
    endpoint: string;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    provider: UpsertConnectionRequestOneOf5ProviderEnum;
}


/**
 * @export
 */
export const UpsertConnectionRequestOneOf5ProviderEnum = {
    AzureAiLanguagePii: 'azure_ai_language_pii',
} as const;
export type UpsertConnectionRequestOneOf5ProviderEnum = typeof UpsertConnectionRequestOneOf5ProviderEnum[keyof typeof UpsertConnectionRequestOneOf5ProviderEnum];


/**
 * Check if a given object implements the UpsertConnectionRequestOneOf5 interface.
 */
export function instanceOfUpsertConnectionRequestOneOf5(value: object): value is UpsertConnectionRequestOneOf5 {
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'azure_ai_language_pii') return false;
    
    return true;
}

export function UpsertConnectionRequestOneOf5FromJSON(json: any): UpsertConnectionRequestOneOf5 {
    return UpsertConnectionRequestOneOf5FromJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertConnectionRequestOneOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'endpoint': json['endpoint'],
        'language': json['language'] == null ? undefined : json['language'],
        'provider': json['provider'],
    };
}

export function UpsertConnectionRequestOneOf5ToJSON(json: any): UpsertConnectionRequestOneOf5 {
    return UpsertConnectionRequestOneOf5ToJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOf5ToJSONTyped(value?: UpsertConnectionRequestOneOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'api_version': value['apiVersion'],
        'endpoint': value['endpoint'],
        'language': value['language'],
        'provider': value['provider'],
    };
}

