/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpsertConnectionRequestOneOf
 */
export interface UpsertConnectionRequestOneOf {
    /**
     * 
     */
    analyzerUrl: string;
    /**
     * 
     */
    anonymizerUrl?: string;
    /**
     * Supply to set or rotate the token; omit to leave unchanged.
     */
    bearerToken?: string;
    /**
     * 
     */
    language?: string;
    /**
     * 
     */
    provider: UpsertConnectionRequestOneOfProviderEnum;
}


/**
 * @export
 */
export const UpsertConnectionRequestOneOfProviderEnum = {
    Presidio: 'presidio',
} as const;
export type UpsertConnectionRequestOneOfProviderEnum = typeof UpsertConnectionRequestOneOfProviderEnum[keyof typeof UpsertConnectionRequestOneOfProviderEnum];


/**
 * Check if a given object implements the UpsertConnectionRequestOneOf interface.
 */
export function instanceOfUpsertConnectionRequestOneOf(value: object): value is UpsertConnectionRequestOneOf {
    if ((!('analyzerUrl' in (value as Record<string, any>)) && !('analyzer_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['analyzerUrl'] === undefined && (value as Record<string, any>)['analyzer_url'] === undefined)) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (value['provider'] !== 'presidio') return false;
    
    return true;
}

export function UpsertConnectionRequestOneOfFromJSON(json: any): UpsertConnectionRequestOneOf {
    return UpsertConnectionRequestOneOfFromJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertConnectionRequestOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'analyzerUrl': json['analyzer_url'],
        'anonymizerUrl': json['anonymizer_url'] == null ? undefined : json['anonymizer_url'],
        'bearerToken': json['bearer_token'] == null ? undefined : json['bearer_token'],
        'language': json['language'] == null ? undefined : json['language'],
        'provider': json['provider'],
    };
}

export function UpsertConnectionRequestOneOfToJSON(json: any): UpsertConnectionRequestOneOf {
    return UpsertConnectionRequestOneOfToJSONTyped(json, false);
}

export function UpsertConnectionRequestOneOfToJSONTyped(value?: UpsertConnectionRequestOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analyzer_url': value['analyzerUrl'],
        'anonymizer_url': value['anonymizerUrl'],
        'bearer_token': value['bearerToken'],
        'language': value['language'],
        'provider': value['provider'],
    };
}

