/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ScopeType } from './ScopeType.js';
import {
    ScopeTypeFromJSON,
    ScopeTypeFromJSONTyped,
    ScopeTypeToJSON,
    ScopeTypeToJSONTyped,
} from './ScopeType.js';
import type { BudgetAction } from './BudgetAction.js';
import {
    BudgetActionFromJSON,
    BudgetActionFromJSONTyped,
    BudgetActionToJSON,
    BudgetActionToJSONTyped,
} from './BudgetAction.js';
import type { BudgetPeriod } from './BudgetPeriod.js';
import {
    BudgetPeriodFromJSON,
    BudgetPeriodFromJSONTyped,
    BudgetPeriodToJSON,
    BudgetPeriodToJSONTyped,
} from './BudgetPeriod.js';
import type { TrafficType } from './TrafficType.js';
import {
    TrafficTypeFromJSON,
    TrafficTypeFromJSONTyped,
    TrafficTypeToJSON,
    TrafficTypeToJSONTyped,
} from './TrafficType.js';

/**
 * An admin-API response for an entity whose core type lives in
 * `ai_governance` and so cannot carry portal-only columns.
 * 
 * `TokenBudget` and `RateLimitPolicy` are read by the enforcement path on
 * every request; hanging five display-only fields off them would put portal
 * concerns in the hot path's type and force every governance consumer to
 * carry them. Wrapping instead keeps the enforcement reads
 * (`get_enabled_by_org` and friends) returning the bare governance type,
 * while the admin reads return this.
 * 
 * Both halves are `#[serde(flatten)]`, so the wire shape stays the flat
 * object the portal already consumes — same choice `AdminModelPricing` makes.
 * @export
 * @interface WithAttributionTokenBudget
 */
export interface WithAttributionTokenBudget {
    /**
     * 
     */
    createdByEmail?: string;
    /**
     * 
     */
    createdByName?: string;
    /**
     * 
     */
    createdByUserId?: string;
    /**
     * Optional free text explaining *why* the last change was made
     * ("Raised for the Q3 batch job", "Vendor deprecated the old endpoint").
     * 
     * Admin-authored and rendered in the portal, so it is untrusted input:
     * length-capped here, escaped on render.
     */
    lastChangeNote?: string;
    /**
     * When the change named by `last_modified_by_*` happened.
     * 
     * Its own column rather than the row's `updated_at`, because `updated_at`
     * is bumped by writes nobody is attributed for -- pairing the two would
     * date a named admin's edit to a background job's clock. See the V75
     * migration for the full reasoning.
     */
    lastModifiedAt?: Date;
    /**
     * 
     */
    lastModifiedByEmail?: string;
    /**
     * 
     */
    lastModifiedByName?: string;
    /**
     * 
     */
    lastModifiedByUserId?: string;
    /**
     * 
     */
    actionOnExhaust: BudgetAction;
    /**
     * 
     */
    alertThresholds: Array<number>;
    /**
     * Optional spending cap in the configured currency.
     * When set, the budget is enforced on estimated cost in addition to tokens.
     */
    costLimit?: number | null;
    /**
     * When the budget was created. Populated on the admin API path (where it
     * is surfaced in the dashboard); left `None` on the hot enforcement path
     * and in fixtures, which don't need it. `#[serde(default)]` keeps older
     * payloads without the field deserializing cleanly.
     */
    createdAt?: Date | null;
    /**
     * ISO 4217 currency code (e.g. "USD"). Defaults to "USD".
     */
    currency?: string;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    id: string;
    /**
     * BCP-3814 membership filter: when set, this budget only applies to
     * requesters whose IdP group membership includes this group name.
     * 
     * Only meaningful on a broad user-scoped budget (`scope_type == User`
     * with `scope_id` and `scope_value` both `None`), where the counter
     * qualifier already resolves to the requesting user's id — so one budget
     * row gives every *member of the group* their own independent allowance,
     * and a user joining the group is enforced on their next request with no
     * admin action. DB-enforced by
     * `token_budgets_member_of_group_requires_broad_user` (V65, tightened to
     * exclude `scope_value` by V67).
     * 
     * `None` ⇒ the budget applies org-wide (the pre-BCP-3814 behaviour).
     * Contrast with a `ScopeType::Group` budget, which keys its counter by
     * the group name and so *pools* one allowance across all members.
     */
    memberOfGroup?: string | null;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    period: BudgetPeriod;
    /**
     * 
     */
    scopeId?: string | null;
    /**
     * 
     */
    scopeType: ScopeType;
    /**
     * 
     */
    scopeValue?: string | null;
    /**
     * BCP-4053 Target dimension: when set, the budget only fires on requests
     * routed to this MCP server. The MCP-traffic counterpart of
     * `target_provider_id`, and mutually exclusive with all three LLM target
     * columns (DB-enforced by `token_budgets_mcp_target_exclusive_check`) —
     * no single request carries both an MCP server and an LLM route, so a
     * row naming both could never match.
     * 
     * Distinct from a `ScopeType::McpServer` budget, which puts the server on
     * the *identity* axis and so cannot be combined with a user or group.
     * As a target it composes freely with any scope, which is what makes
     * "this user's cap on this server" expressible.
     */
    targetMcpServerId?: string | null;
    /**
     * BCP-2813 Target dimension: when set, the budget only fires when the
     * requested model alias (`request.model`) equals this value. Mutually
     * exclusive with the other two `target_*` fields.
     */
    targetModelAlias?: string | null;
    /**
     * BCP-2813 Target dimension: when set, the budget only fires on routes
     * whose provider id equals this value. May be combined with
     * `target_upstream_model` to cap a single model on this provider;
     * mutually exclusive with `target_model_alias` (DB-enforced by
     * `token_budgets_alias_target_exclusive_check`).
     */
    targetProviderId?: string | null;
    /**
     * BCP-2813 Target dimension refining `target_provider_id`: when set,
     * the budget only fires on routes whose resolved upstream model name
     * equals this value (string match). Always set alongside a provider
     * (V54 CHECK-enforced) — a bare upstream name would string every
     * provider serving that model into one cap.
     */
    targetUpstreamModel?: string | null;
    /**
     * 
     */
    tokenLimit: number;
    /**
     * 
     */
    trafficType: TrafficType;
}



/**
 * Check if a given object implements the WithAttributionTokenBudget interface.
 */
export function instanceOfWithAttributionTokenBudget(value: object): value is WithAttributionTokenBudget {
    if ((!('actionOnExhaust' in (value as Record<string, any>)) && !('action_on_exhaust' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionOnExhaust'] === undefined && (value as Record<string, any>)['action_on_exhaust'] === undefined)) return false;
    if ((!('alertThresholds' in (value as Record<string, any>)) && !('alert_thresholds' in (value as Record<string, any>))) || ((value as Record<string, any>)['alertThresholds'] === undefined && (value as Record<string, any>)['alert_thresholds'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if ((!('scopeType' in (value as Record<string, any>)) && !('scope_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['scopeType'] === undefined && (value as Record<string, any>)['scope_type'] === undefined)) return false;
    if ((!('tokenLimit' in (value as Record<string, any>)) && !('token_limit' in (value as Record<string, any>))) || ((value as Record<string, any>)['tokenLimit'] === undefined && (value as Record<string, any>)['token_limit'] === undefined)) return false;
    if ((!('trafficType' in (value as Record<string, any>)) && !('traffic_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['trafficType'] === undefined && (value as Record<string, any>)['traffic_type'] === undefined)) return false;
    return true;
}

export function WithAttributionTokenBudgetFromJSON(json: any): WithAttributionTokenBudget {
    return WithAttributionTokenBudgetFromJSONTyped(json, false);
}

export function WithAttributionTokenBudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithAttributionTokenBudget {
    if (json == null) {
        return json;
    }
    return {
        
        'createdByEmail': json['created_by_email'] == null ? undefined : json['created_by_email'],
        'createdByName': json['created_by_name'] == null ? undefined : json['created_by_name'],
        'createdByUserId': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'lastChangeNote': json['last_change_note'] == null ? undefined : json['last_change_note'],
        'lastModifiedAt': json['last_modified_at'] == null ? undefined : (parseDateTime(json['last_modified_at'])),
        'lastModifiedByEmail': json['last_modified_by_email'] == null ? undefined : json['last_modified_by_email'],
        'lastModifiedByName': json['last_modified_by_name'] == null ? undefined : json['last_modified_by_name'],
        'lastModifiedByUserId': json['last_modified_by_user_id'] == null ? undefined : json['last_modified_by_user_id'],
        'actionOnExhaust': BudgetActionFromJSON(json['action_on_exhaust']),
        'alertThresholds': json['alert_thresholds'],
        'costLimit': json['cost_limit'] === undefined ? undefined : json['cost_limit'] === null ? null : json['cost_limit'],
        'createdAt': json['created_at'] === undefined ? undefined : json['created_at'] === null ? null : (parseDateTime(json['created_at'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'enabled': json['enabled'],
        'id': json['id'],
        'memberOfGroup': json['member_of_group'] === undefined ? undefined : json['member_of_group'] === null ? null : json['member_of_group'],
        'name': json['name'],
        'orgId': json['org_id'],
        'period': BudgetPeriodFromJSON(json['period']),
        'scopeId': json['scope_id'] === undefined ? undefined : json['scope_id'] === null ? null : json['scope_id'],
        'scopeType': ScopeTypeFromJSON(json['scope_type']),
        'scopeValue': json['scope_value'] === undefined ? undefined : json['scope_value'] === null ? null : json['scope_value'],
        'targetMcpServerId': json['target_mcp_server_id'] === undefined ? undefined : json['target_mcp_server_id'] === null ? null : json['target_mcp_server_id'],
        'targetModelAlias': json['target_model_alias'] === undefined ? undefined : json['target_model_alias'] === null ? null : json['target_model_alias'],
        'targetProviderId': json['target_provider_id'] === undefined ? undefined : json['target_provider_id'] === null ? null : json['target_provider_id'],
        'targetUpstreamModel': json['target_upstream_model'] === undefined ? undefined : json['target_upstream_model'] === null ? null : json['target_upstream_model'],
        'tokenLimit': json['token_limit'],
        'trafficType': TrafficTypeFromJSON(json['traffic_type']),
    };
}

export function WithAttributionTokenBudgetToJSON(json: any): WithAttributionTokenBudget {
    return WithAttributionTokenBudgetToJSONTyped(json, false);
}

export function WithAttributionTokenBudgetToJSONTyped(value?: WithAttributionTokenBudget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by_email': value['createdByEmail'],
        'created_by_name': value['createdByName'],
        'created_by_user_id': value['createdByUserId'],
        'last_change_note': value['lastChangeNote'],
        'last_modified_at': value['lastModifiedAt'] == null ? value['lastModifiedAt'] : serializeDateTime(value['lastModifiedAt']),
        'last_modified_by_email': value['lastModifiedByEmail'],
        'last_modified_by_name': value['lastModifiedByName'],
        'last_modified_by_user_id': value['lastModifiedByUserId'],
        'action_on_exhaust': BudgetActionToJSON(value['actionOnExhaust']),
        'alert_thresholds': value['alertThresholds'],
        'cost_limit': value['costLimit'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'currency': value['currency'],
        'enabled': value['enabled'],
        'id': value['id'],
        'member_of_group': value['memberOfGroup'],
        'name': value['name'],
        'org_id': value['orgId'],
        'period': BudgetPeriodToJSON(value['period']),
        'scope_id': value['scopeId'],
        'scope_type': ScopeTypeToJSON(value['scopeType']),
        'scope_value': value['scopeValue'],
        'target_mcp_server_id': value['targetMcpServerId'],
        'target_model_alias': value['targetModelAlias'],
        'target_provider_id': value['targetProviderId'],
        'target_upstream_model': value['targetUpstreamModel'],
        'token_limit': value['tokenLimit'],
        'traffic_type': TrafficTypeToJSON(value['trafficType']),
    };
}

