/* tslint:disable */
/* eslint-disable */
/**
 * Barndoor.ai Public API
 * Unified public API specification for Barndoor.ai platform
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ModelAccessTarget } from './ModelAccessTarget.js';
import {
    ModelAccessTargetFromJSON,
    ModelAccessTargetFromJSONTyped,
    ModelAccessTargetToJSON,
    ModelAccessTargetToJSONTyped,
} from './ModelAccessTarget.js';

/**
 * An admin-API response for an entity whose core type lives in
 * `ai_governance` and so cannot carry portal-only columns.
 * 
 * `TokenBudget` and `RateLimitPolicy` are read by the enforcement path on
 * every request; hanging five display-only fields off them would put portal
 * concerns in the hot path's type and force every governance consumer to
 * carry them. Wrapping instead keeps the enforcement reads
 * (`get_enabled_by_org` and friends) returning the bare governance type,
 * while the admin reads return this.
 * 
 * Both halves are `#[serde(flatten)]`, so the wire shape stays the flat
 * object the portal already consumes — same choice `AdminModelPricing` makes.
 * @export
 * @interface WithAttributionModelAccessPolicy
 */
export interface WithAttributionModelAccessPolicy {
    /**
     * 
     */
    createdByEmail?: string;
    /**
     * 
     */
    createdByName?: string;
    /**
     * 
     */
    createdByUserId?: string;
    /**
     * Optional free text explaining *why* the last change was made
     * ("Raised for the Q3 batch job", "Vendor deprecated the old endpoint").
     * 
     * Admin-authored and rendered in the portal, so it is untrusted input:
     * length-capped here, escaped on render.
     */
    lastChangeNote?: string;
    /**
     * When the change named by `last_modified_by_*` happened.
     * 
     * Its own column rather than the row's `updated_at`, because `updated_at`
     * is bumped by writes nobody is attributed for -- pairing the two would
     * date a named admin's edit to a background job's clock. See the V75
     * migration for the full reasoning.
     */
    lastModifiedAt?: Date;
    /**
     * 
     */
    lastModifiedByEmail?: string;
    /**
     * 
     */
    lastModifiedByName?: string;
    /**
     * 
     */
    lastModifiedByUserId?: string;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    orgId: string;
    /**
     * 
     */
    policyType: string;
    /**
     * 
     */
    scopeId?: string | null;
    /**
     * 
     */
    scopeType: string;
    /**
     * 
     */
    scopeValue?: string | null;
    /**
     * 
     */
    targets: Array<ModelAccessTarget>;
    /**
     * 
     */
    trafficType: string;
}

/**
 * Check if a given object implements the WithAttributionModelAccessPolicy interface.
 */
export function instanceOfWithAttributionModelAccessPolicy(value: object): value is WithAttributionModelAccessPolicy {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if ((!('policyType' in (value as Record<string, any>)) && !('policy_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['policyType'] === undefined && (value as Record<string, any>)['policy_type'] === undefined)) return false;
    if ((!('scopeType' in (value as Record<string, any>)) && !('scope_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['scopeType'] === undefined && (value as Record<string, any>)['scope_type'] === undefined)) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    if ((!('trafficType' in (value as Record<string, any>)) && !('traffic_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['trafficType'] === undefined && (value as Record<string, any>)['traffic_type'] === undefined)) return false;
    return true;
}

export function WithAttributionModelAccessPolicyFromJSON(json: any): WithAttributionModelAccessPolicy {
    return WithAttributionModelAccessPolicyFromJSONTyped(json, false);
}

export function WithAttributionModelAccessPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithAttributionModelAccessPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'createdByEmail': json['created_by_email'] == null ? undefined : json['created_by_email'],
        'createdByName': json['created_by_name'] == null ? undefined : json['created_by_name'],
        'createdByUserId': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'lastChangeNote': json['last_change_note'] == null ? undefined : json['last_change_note'],
        'lastModifiedAt': json['last_modified_at'] == null ? undefined : (parseDateTime(json['last_modified_at'])),
        'lastModifiedByEmail': json['last_modified_by_email'] == null ? undefined : json['last_modified_by_email'],
        'lastModifiedByName': json['last_modified_by_name'] == null ? undefined : json['last_modified_by_name'],
        'lastModifiedByUserId': json['last_modified_by_user_id'] == null ? undefined : json['last_modified_by_user_id'],
        'enabled': json['enabled'],
        'id': json['id'],
        'name': json['name'],
        'orgId': json['org_id'],
        'policyType': json['policy_type'],
        'scopeId': json['scope_id'] === undefined ? undefined : json['scope_id'] === null ? null : json['scope_id'],
        'scopeType': json['scope_type'],
        'scopeValue': json['scope_value'] === undefined ? undefined : json['scope_value'] === null ? null : json['scope_value'],
        'targets': ((json['targets'] as Array<any>).map(ModelAccessTargetFromJSON)),
        'trafficType': json['traffic_type'],
    };
}

export function WithAttributionModelAccessPolicyToJSON(json: any): WithAttributionModelAccessPolicy {
    return WithAttributionModelAccessPolicyToJSONTyped(json, false);
}

export function WithAttributionModelAccessPolicyToJSONTyped(value?: WithAttributionModelAccessPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by_email': value['createdByEmail'],
        'created_by_name': value['createdByName'],
        'created_by_user_id': value['createdByUserId'],
        'last_change_note': value['lastChangeNote'],
        'last_modified_at': value['lastModifiedAt'] == null ? value['lastModifiedAt'] : serializeDateTime(value['lastModifiedAt']),
        'last_modified_by_email': value['lastModifiedByEmail'],
        'last_modified_by_name': value['lastModifiedByName'],
        'last_modified_by_user_id': value['lastModifiedByUserId'],
        'enabled': value['enabled'],
        'id': value['id'],
        'name': value['name'],
        'org_id': value['orgId'],
        'policy_type': value['policyType'],
        'scope_id': value['scopeId'],
        'scope_type': value['scopeType'],
        'scope_value': value['scopeValue'],
        'targets': ((value['targets'] as Array<any>).map(ModelAccessTargetToJSON)),
        'traffic_type': value['trafficType'],
    };
}

